#!/usr/bin/env node
/** Compila un lote arbitrario de blueprints Tier 1 aprobados en eventos RMXP.
 * Uso: node tools/apply_tier1_batch.mjs --input content/lote.json --backup nombre
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { marshalLoad,marshalDump,RHash,RObject,RString,RSymbol } from "../web/js/marshal.js";
import { parseMap,parseTileset,tableGet } from "../web/js/rmxp.js";
const ROOT=path.resolve(path.dirname(fileURLToPath(import.meta.url)),".."),GAME=path.join(ROOT,"pokemon_fire_ash"),DATA=path.join(GAME,"Data");
const inputAt=process.argv.indexOf("--input"),backupAt=process.argv.indexOf("--backup");
const INPUT=path.resolve(inputAt>=0?process.argv[inputAt+1]:path.join(ROOT,"content","atlas_tier1_blueprints_approved.json"));
const BLUEPRINTS=JSON.parse(fs.readFileSync(INPUT,"utf8")).blueprints;
const backupName=backupAt>=0?process.argv[backupAt+1]:`tier1_${path.basename(INPUT,".json")}_originals`;
const BACKUP=path.join(GAME,"PokeModBackups",backupName),VERIFY=process.argv.includes("--verify"),MARKER="PokeMod Tier1:";
const SEAL_COUNT=103;
const decisionVariable=(b)=>104+(Number(b.flags.globalSwitches[0].id)-708);
const S=(v)=>RString.fromText(String(v)),Sym=(v)=>new RSymbol(String(v)),iv=(o,n)=>o?.getIvar?.(n),txt=(v)=>v instanceof RString?v.text:String(v??""),sym=(v)=>v instanceof RSymbol?v.name:String(v??""),hget=(h,n)=>h?.pairs?.find(([k])=>sym(k)===n)?.[1],pad=(n)=>String(n).padStart(3,"0");
const read=(f)=>marshalLoad(fs.readFileSync(path.join(DATA,f))),write=(f,v)=>fs.writeFileSync(path.join(DATA,f),Buffer.from(marshalDump(v)));
function backup(){fs.mkdirSync(BACKUP,{recursive:true});for(const f of ["System.rxdata","MapInfos.rxdata","trainers.dat",...BLUEPRINTS.map((b)=>`Map${pad(b.mapId)}.rxdata`)]){const src=path.join(DATA,f),dst=path.join(BACKUP,f);if(!fs.existsSync(dst))fs.copyFileSync(src,dst);}fs.writeFileSync(path.join(BACKUP,"LEEME.txt"),`Originales anteriores a compilar ${path.basename(INPUT)}. Restaura estos archivos para revertir este lote.\n`);}
function cmd(code,params=[],indent=0){return new RObject("RPG::EventCommand",[["@code",code],["@indent",indent],["@parameters",params]]);}
function condition({sw=0,self=""}={}){return new RObject("RPG::Event::Page::Condition",[["@switch1_valid",!!sw],["@switch1_id",sw||1],["@switch2_valid",false],["@switch2_id",1],["@variable_valid",false],["@variable_id",1],["@variable_value",0],["@self_switch_valid",!!self],["@self_switch_ch",S(self||"A")]]);}
function graphic(name="",dir=2,pattern=1){return new RObject("RPG::Event::Page::Graphic",[["@tile_id",0],["@character_name",S(name)],["@character_hue",0],["@direction",dir],["@pattern",pattern],["@opacity",255],["@blend_type",0]]);}
function route(){return new RObject("RPG::MoveRoute",[["@repeat",true],["@skippable",false],["@list",[]]]);}
function page({cond=condition(),gfx=graphic(),through=true,list=[cmd(0)]}={}){return new RObject("RPG::Event::Page",[["@condition",cond],["@graphic",gfx],["@move_type",0],["@move_speed",3],["@move_frequency",3],["@move_route",route()],["@walk_anime",true],["@step_anime",false],["@direction_fix",false],["@through",through],["@always_on_top",false],["@trigger",0],["@list",list]]);}
function event(id,name,x,y,pages){return new RObject("RPG::Event",[["@id",id],["@name",S(name)],["@x",x],["@y",y],["@pages",pages]]);}
function wrap(input,max=43){const out=[];for(const para of String(input).split("\n")){let line="";for(const word of para.split(/\s+/)){if(!line)line=word;else if(`${line} ${word}`.length<=max)line+=` ${word}`;else{out.push(line);line=word;}}if(line)out.push(line);}return out.length?out:["..."];}
function texts(lines,indent=0){const all=(Array.isArray(lines)?lines:[lines]).flatMap((x)=>wrap(x));return[cmd(101,[S("")],indent),...all.map((x)=>cmd(401,[S(x)],indent))];}
function scripts(lines,indent=0){const all=Array.isArray(lines)?lines:[lines];return[cmd(355,[S(all[0]||"")],indent),...all.slice(1).map((x)=>cmd(655,[S(x)],indent))];}
function selfOn(letter="A",indent=0){return cmd(123,[S(letter),0],indent);}
function setSwitch(id,indent=0){return cmd(121,[id,id,0],indent);}
function setVariable(id,value,indent=0){return cmd(122,[id,id,0,0,value],indent);}
function addVariable(id,value,indent=0){return cmd(122,[id,id,1,0,value],indent);}
function dataSymbols(file){const d=read(file),s=new Set();for(const[k]of d.pairs)if(k instanceof RSymbol)s.add(k.name);return s;}
const tilesetRaw=read("Tilesets.rxdata"),tilesets=new Map();for(let i=1;i<tilesetRaw.length;i++)if(tilesetRaw[i])tilesets.set(i,parseTileset(tilesetRaw[i]));
function openCell(p,t,x,y){if(x<1||y<1||x>=p.width-1||y>=p.height-1)return false;let bits=0;for(let z=0;z<p.table.z;z++){const tile=tableGet(p.table,x,y,z);if(tile>0&&tile<t.passages.data.length)bits|=t.passages.data[tile]&15;}return bits===0;}
function largest(map){const p=parseMap(map),t=tilesets.get(p.tilesetId),seen=new Set(),parts=[];for(let y=1;y<p.height-1;y++)for(let x=1;x<p.width-1;x++){const k=`${x},${y}`;if(seen.has(k)||!openCell(p,t,x,y))continue;const q=[[x,y]];seen.add(k);for(let j=0;j<q.length;j++){const[a,b]=q[j];for(const[c,d]of[[a+1,b],[a-1,b],[a,b+1],[a,b-1]]){const z=`${c},${d}`;if(!seen.has(z)&&openCell(p,t,c,d)){seen.add(z);q.push([c,d]);}}}parts.push(q);}parts.sort((a,b)=>b.length-a.length);return parts[0]||[];}
function spread(map,count,excluded){const ban=new Set(excluded.map((p)=>p.join(","))),cells=largest(map).filter((p)=>!ban.has(p.join(",")));if(cells.length<count)throw new Error(`No hay ${count} posiciones libres`);const chosen=[cells[Math.floor(cells.length/2)]],used=new Set([chosen[0].join(",")]);while(chosen.length<count){let best,score=-1;for(const c of cells){if(used.has(c.join(",")))continue;const d=Math.min(...chosen.map((p)=>(p[0]-c[0])**2+(p[1]-c[1])**2));if(d>score){score=d;best=c;}}chosen.push(best);used.add(best.join(","));}return chosen;}
function npcEvent(id,npc,pos,flag){const gfx=()=>graphic(npc.sprite);return event(id,`${MARKER} NPC ${npc.name}`,pos[0],pos[1],[page({gfx:gfx(),list:[...texts(npc.dialogue.before),...texts(npc.dialogue.optional),cmd(0)]}),page({cond:condition({sw:flag}),gfx:gfx(),list:[...texts(npc.dialogue.after),cmd(0)]})]);}
function healerEvent(id,pos,title){return event(id,`${MARKER} Curación ${title}`,pos[0],pos[1],[page({gfx:graphic("NPC 16"),list:[...texts(["Este episodio puede ser exigente. Puedo restaurar a todo tu equipo antes de continuar."]),cmd(102,[[S("Curar equipo"),S("Ahora no")],2]),cmd(402,[0,S("Curar equipo")]),cmd(314,[0],1),...texts(["Listo. La salida al puerto permanece abierta."],1),cmd(402,[1,S("Ahora no")]),cmd(404),cmd(0)]})]);}
function conductorEvent(id,b,pos,flag,decisionVar){const call=`pbTrainerBattle(:${b.battle.trainerType},${JSON.stringify(b.battle.trainerName)},nil,${b.battle.doubleBattle},0,true)`;const first=[...texts([b.title,b.narrative.premise,b.narrative.setup]),...scripts(["pbFadeOutIn { }"]),cmd(106,[12]),...texts([b.narrative.escalation,b.narrative.reversal]),cmd(102,[b.cutscene.decision.options.map(S),b.cutscene.decision.options.length]),cmd(402,[0,S(b.cutscene.decision.options[0])]),setVariable(decisionVar,0,1),...texts([b.cutscene.decision.immediateDifferences[0]],1),cmd(402,[1,S(b.cutscene.decision.options[1])]),setVariable(decisionVar,1,1),...texts([b.cutscene.decision.immediateDifferences[1]],1),cmd(404),...texts([b.battle.storyToldByTeam,b.battle.counterplayHint]),...scripts([`pbTrainerIntro(:${b.battle.trainerType})`]),cmd(111,[12,S(call)]),...texts([b.narrative.resolution,`Has obtenido ${b.reward.narrativeToken}.`,b.reward.futurePayoff],1),...scripts([`pbReceiveItem(:${b.reward.item})`],1),setSwitch(flag,1),addVariable(SEAL_COUNT,1,1),selfOn("A",1),cmd(411),...texts([b.cutscene.failurePath],1),cmd(412),...scripts(["pbTrainerEnd"]),cmd(0)];
 const done=[...texts([b.narrative.globalConnection,...b.npcs.flatMap((n)=>n.dialogue.after.slice(0,1))]),cmd(102,[[S("Revancha"),S("Salir")],2]),cmd(402,[0,S("Revancha")]),...scripts([`pbTrainerIntro(:${b.battle.trainerType})`],1),cmd(111,[12,S(call)],1),...texts(["La revancha queda registrada sin repetir sello ni recompensa."],2),cmd(411,[],1),...texts(["Puedes intentarlo nuevamente cuando estés preparado."],2),cmd(412,[],1),...scripts(["pbTrainerEnd"],1),cmd(402,[1,S("Salir")]),cmd(404),cmd(0)];const gfx=()=>graphic(b.battle.sprite);return event(id,`${MARKER} Conductor ${b.title}`,pos[0],pos[1],[page({gfx:gfx(),list:first}),page({cond:condition({sw:flag}),gfx:gfx(),list:done})]);}
function trainerPokemon(p){const pairs=[[Sym("species"),Sym(p.species)],[Sym("level"),p.level],[Sym("moves"),p.moves.map(Sym)]];if(p.item)pairs.push([Sym("item"),Sym(p.item)]);return new RHash(pairs);}
function trainerObject(b,id){const key=[Sym(b.battle.trainerType),S(b.battle.trainerName),0];return new RObject("GameData::Trainer",[["@id",key],["@id_number",id],["@trainer_type",key[0]],["@real_name",key[1]],["@version",0],["@items",[Sym("FULLRESTORE"),Sym("FULLRESTORE")]],["@real_lose_text",S(b.cutscene.failurePath)],["@numpkmn",0],["@guara",0],["@pokemon",b.battle.team.map(trainerPokemon)]]);}
function trainerMatch(key,b){return Array.isArray(key)&&sym(key[0])===b.battle.trainerType&&txt(key[1])===b.battle.trainerName&&Number(key[2])===0;}
function installSystem(){const s=read("System.rxdata"),sw=iv(s,"switches")||[],vars=iv(s,"variables")||[];vars[SEAL_COUNT]=S("POKEMOD ATLAS NARRATIVE SEALS");for(let i=0;i<BLUEPRINTS.length;i++){const b=BLUEPRINTS[i],flag=b.flags.globalSwitches[0].id;sw[flag]=S(b.flags.globalSwitches[0].name);vars[decisionVariable(b)]=S(`POKEMOD ATLAS DECISION ${String(flag-707).padStart(2,"0")}`);}s.setIvar("switches",sw);s.setIvar("variables",vars);write("System.rxdata",s);}
function installInfos(){const infos=read("MapInfos.rxdata");for(const b of BLUEPRINTS){const obj=infos.pairs.find(([k])=>Number(k)===b.mapId)?.[1];if(!obj)throw new Error(`MapInfos sin ${b.mapId}`);obj.setIvar("name",S(b.title));}write("MapInfos.rxdata",infos);}
function installTrainers(){const species=dataSymbols("species.dat"),moves=dataSymbols("moves.dat"),items=dataSymbols("items.dat"),types=dataSymbols("trainer_types.dat"),d=read("trainers.dat");for(const b of BLUEPRINTS){if(!types.has(b.battle.trainerType))throw new Error(`Tipo inválido ${b.battle.trainerType}`);for(const p of b.battle.team){if(!species.has(p.species)||p.moves.some((m)=>!moves.has(m))||(p.item&&!items.has(p.item)))throw new Error(`Datos inválidos en ${b.title}/${p.species}`);}}let next=Math.max(-1,...d.pairs.filter(([k])=>typeof k==="number").map(([k])=>k))+1;for(const b of BLUEPRINTS){const existing=d.pairs.find(([k])=>trainerMatch(k,b));if(existing){const old=existing[1],id=Number(iv(old,"id_number")),obj=trainerObject(b,id);for(const pair of d.pairs)if(pair[1]===old||trainerMatch(pair[0],b)||(typeof pair[0]==="number"&&pair[0]===id))pair[1]=obj;continue;}const obj=trainerObject(b,next),key=iv(obj,"id");d.pairs.push([next,obj],[key,obj]);next++;}write("trainers.dat",d);}
function installMaps(){for(let i=0;i<BLUEPRINTS.length;i++){const b=BLUEPRINTS[i],file=`Map${pad(b.mapId)}.rxdata`,map=read(file),events=iv(map,"events");events.pairs=events.pairs.filter(([,ev])=>!txt(iv(ev,"name")).startsWith(MARKER));const occupied=events.pairs.map(([,ev])=>[Number(iv(ev,"x")),Number(iv(ev,"y"))]),pos=spread(map,5,occupied),flag=b.flags.globalSwitches[0].id;const additions=[conductorEvent(200,b,pos[0],flag,decisionVariable(b)),...b.npcs.slice(0,3).map((n,j)=>npcEvent(201+j,n,pos[1+j],flag)),healerEvent(204,pos[4],b.title)];for(const ev of additions)events.pairs.push([Number(iv(ev,"id")),ev]);write(file,map);}}
function commandsOf(ev){const out=[];for(const p of iv(ev,"pages")||[])for(const c of iv(p,"list")||[])out.push(c);return out;}
function verify(){const errors=[],ok=(v,m)=>{if(!v)errors.push(m);};const s=read("System.rxdata"),sw=iv(s,"switches"),vars=iv(s,"variables"),infos=read("MapInfos.rxdata"),trainers=read("trainers.dat");ok(txt(vars[SEAL_COUNT]).includes("SEALS"),"falta contador de sellos");for(let i=0;i<BLUEPRINTS.length;i++){const b=BLUEPRINTS[i],flag=b.flags.globalSwitches[0].id;ok(txt(sw[flag])===b.flags.globalSwitches[0].name,`${b.mapId}: flag incorrecta`);ok(txt(vars[decisionVariable(b)]).includes("DECISION"),`${b.mapId}: variable de decisión ausente`);ok(txt(infos.pairs.find(([k])=>Number(k)===b.mapId)?.[1]?.getIvar("name"))===b.title,`${b.mapId}: nombre incorrecto`);const map=read(`Map${pad(b.mapId)}.rxdata`),events=iv(map,"events").pairs.map(([,e])=>e),added=events.filter((e)=>txt(iv(e,"name")).startsWith(MARKER));ok(added.length===5,`${b.mapId}: ${added.length}/5 eventos artesanales`);ok(events.some((e)=>txt(iv(e,"name"))==="Return to Puerto Horizonte"),`${b.mapId}: sin retorno`);const conductor=added.find((e)=>txt(iv(e,"name")).includes("Conductor")),code=conductor?commandsOf(conductor):[];const ruby=code.filter((c)=>[111,355,655].includes(Number(iv(c,"code")))).map((c)=>txt(iv(c,"parameters")?.[Number(iv(c,"code"))===111?1:0])).join("\n");ok(ruby.includes(",0,true)"),`${b.mapId}: batalla no permite perder`);ok(!/674|675|NO ITEM/.test(ruby),`${b.mapId}: intento de bloquear Mochila`);const self=code.find((c)=>Number(iv(c,"code"))===123);ok(self&&Number(iv(self,"parameters")[1])===0,`${b.mapId}: self-switch incorrecto`);const pair=trainers.pairs.find(([k])=>trainerMatch(k,b));ok(!!pair,`${b.mapId}: entrenador ausente`);if(pair){const party=iv(pair[1],"pokemon")||[];ok(party.length===6,`${b.mapId}: equipo incompleto`);for(let j=0;j<Math.min(party.length,b.battle.team.length);j++){const got=party[j],want=b.battle.team[j],moves=(hget(got,"moves")||[]).map(sym);ok(sym(hget(got,"species"))===want.species,`${b.mapId}: especie ${j+1} desactualizada`);ok(Number(hget(got,"level"))===want.level,`${b.mapId}: nivel ${j+1} desactualizado`);ok(JSON.stringify(moves)===JSON.stringify(want.moves),`${b.mapId}: movimientos ${j+1} desactualizados`);ok(sym(hget(got,"item"))===(want.item||""),`${b.mapId}: objeto ${j+1} desactualizado`);}}}if(errors.length)throw new Error(`Tier 1 inválido (${errors.length}):\n- ${errors.join("\n- ")}`);console.log(`Verificación OK: ${BLUEPRINTS.length} episodios Tier 1, ${BLUEPRINTS.length*3} NPCs, ${BLUEPRINTS.length} jefes narrativos, decisiones persistentes y retorno libre.`);}
if(!VERIFY){backup();installSystem();installInfos();installTrainers();installMaps();console.log(`Tier 1 compilado desde ${path.relative(ROOT,INPUT)}. Backup: ${path.relative(ROOT,BACKUP)}`);}verify();
