#!/usr/bin/env node
/** Fase C: anclas 26-30 y primera escalada jugable por encima de nivel 100. */
import {D,N,P,writeBatch} from "./tier1_blueprint_helpers.mjs";
const rows=[
{
id:1646,flag:733,title:"La Estatua que Ensayaba Ciudades",promise:"Una estatua arqueológica talla cada noche una civilización futura distinta y obliga al pueblo a decidir si sus habitantes son profecías, propuestas o personas usadas como argumentos.",
identity:"Casa de ruta convertida en taller arqueológico costero, con una estatua central, archivos y herramientas de restauración",visual:["El relieve central muestra edificios que cambian después de cada asamblea.","Tres capas de piedra usan técnicas pertenecientes a siglos incompatibles.","Los pasillos dejan una ruta jugable completa alrededor de la pieza acordonada."],ambient:["Golpes de cincel suenan cuando nadie está trabajando.","Tras la decisión, la piedra conserva capas etiquetadas o un espacio deliberadamente vacío."],
narrative:{premise:"Alda restaura una estatua que registra ciudades todavía inexistentes después de cada decisión comunitaria.",centralQuestion:"¿Una imagen detallada del futuro merece autoridad sobre quienes tendrán que vivir dentro de ella?",setup:"El consejo quiere construir la última ciudad tallada porque parece resolver todos sus problemas.",escalation:"Nuno descubre figuras sin rostro tapiadas dentro de cada versión descartada.",reversal:"Iria demuestra que la estatua no predice: simula planes y borra del relieve a quienes expresan desacuerdo.",resolution:"El jugador decide convertirla en mesa pública de propuestas o preservar sus capas como advertencia dejando el centro sin terminar.",globalConnection:"El sello veintiséis revela que Atlas confunde consenso con ausencia visible de disidencia."},
voice:{tone:"arqueológico, reverente y cívico",lexicon:["estrato","relieve","traza","asamblea","cincel","propuesta","vacío"],sentenceRule:"Alda fecha; Nuno habla desde el oficio; Iria pregunta quién falta en cada imagen."},
npcs:[
N("Alda Estrato","trchar008","arqueóloga responsable","Dirige la restauración y presentó la primera talla como descubrimiento histórico.","Sabe que la pieza reacciona al presente, pero teme perder años de prestigio al llamarla simulación.","Conservar el hallazgo sin entregar el urbanismo a una piedra.","Que admitir el error destruya la confianza en toda la excavación.","Fecha cada certeza y añade cuándo dejó de sostenerla.",D(["Capa uno: hace mil años. Corrección: la piedra la talló el martes.","Llamé ciudad futura a lo que quizá era una respuesta automática.","La arqueología escucha restos; yo hice que este resto dictara planos."],["La nueva torre apareció después de la votación.","Detengan el cincel; está borrando a los vecinos que se abstuvieron."],["El museo distingue hallazgo, simulación y propuesta.","Mi error quedó en la placa con la misma letra que mi nombre.","La estatua conserva valor sin ocupar el asiento del consejo."],["Una fecha exacta no convierte una interpretación en hecho.","Restaurar también puede significar dejar visible la duda."])),
N("Nuno Argamasa","trchar009","cantero local","Reconoce técnicas de construcción en los relieves futuros.","Quiere usar soluciones de la estatua para dar trabajo al pueblo, aunque sus figuras sin rostro le inquietan.","Probar ideas útiles mediante maquetas y no obediencia.","Que rechazar el plano mantenga viviendas inseguras.","Evalúa cada promesa por peso, drenaje y manos necesarias.",D(["Ese arco aguanta la lluvia; la plaza no aguanta a quien protesta.","Puedo copiar una junta de piedra sin copiar la ciudad entera.","El relieve promete empleo y no talla quién carga los bloques."],["La pared nueva no tiene puerta de servicio.","Voy a sacar una maqueta, no una orden de obra."],["Probamos el drenaje y descartamos la plaza cerrada.","El taller paga manos presentes, no habitantes imaginarios.","Dejé una marca de cantero donde la estatua había borrado una cara."],["Una ciudad empieza por dónde descansa la cuadrilla.","La piedra soporta peso; el barrio soporta consecuencias."])),
N("Iria Índice","NPC 04","archivista joven","Compara actas de asamblea con cambios del relieve.","Su prueba depende de registrar opiniones privadas que prometió mantener anónimas.","Demostrar el sesgo sin exponer a los disidentes.","Que el consejo desprecie su hallazgo por ocultar datos.","Pregunta quién falta antes de describir quién aparece.",D(["¿Quién no está? Tres familias desaparecieron del relieve tras votar en contra.","Puedo probar el patrón sin publicar sus nombres.","La ciudad parece pacífica porque la estatua elimina el desacuerdo."],["Otra figura pierde rostro; cubran el acta privada.","¿Podemos conservar la diferencia sin conservar la identidad?"],["El archivo publica cantidades y protege voces.","La estatua dejó de ser oráculo y ganó contexto.","Mi índice incluye una categoría nueva: ausencia fabricada."],["¿Un plano perfecto admite una puerta que nadie diseñó?", "Lo que falta también necesita procedencia."]))
],
battle:{trainerName:"Custodio del Relieve",trainerType:"RUINMANIAC",sprite:"trchar028",storyToldByTeam:"El equipo avanza desde fragmentos interpretados hasta guardianes capaces de conservar capas, propuestas y espacios no resueltos.",counterplayHint:"Roca, Tierra, Psíquico y Acero permiten respuestas con Agua, Planta, Hielo, Fuego y Siniestro; niveles 100–106 inauguran la progresión extendida sin trucos invencibles.",canLose:true,bagAllowed:true,doubleBattle:false,team:[
P("SIGILYPH",100,"inscripción observada",["PSYCHIC","AIRSLASH","ENERGYBALL","ROOST"],"LEFTOVERS","Abre como símbolo cuyo contexto todavía falta."),
P("RUNERIGUS",101,"rostros borrados",["SHADOWBALL","EARTHQUAKE","WILLOWISP","PROTECT"],"LEFTOVERS","Conserva huellas de quienes la simulación omitió."),
P("CLAYDOL",102,"maqueta urbana",["PSYCHIC","EARTHPOWER","ICEBEAM","STEALTHROCK"],"LEFTOVERS","Representa un modelo útil solo cuando puede probarse."),
P("GOLURK",103,"trabajo monumental",["SHADOWPUNCH","EARTHQUAKE","ICEPUNCH","DRAINPUNCH"],"ASSAULTVEST","Hace visible el esfuerzo detrás de la ciudad ideal."),
P("BRONZONG",104,"estratos incompatibles",["PSYCHIC","FLASHCANNON","EARTHQUAKE","PROTECT"],"LEFTOVERS","Guarda varias edades sin forzarlas a formar una profecía."),
P("CELEBI",106,"futuro como propuesta",["PSYCHIC","ENERGYBALL","DAZZLINGGLEAM","RECOVER"],"LIFEORB","Cierra ofreciendo posibilidades sin borrar el presente.") ]},
decision:{question:"¿Qué función tendrá la estatua?",options:["Mesa pública de propuestas","Archivo de capas inconclusas"],immediateDifferences:["Nuno extrae maquetas y la asamblea prueba cada idea.","Alda etiqueta versiones y protege un vacío central."],laterDifferences:["Otros sectores podrán adaptar soluciones sin obedecer el plano completo.","El Archivo Final leerá la pieza como advertencia contra futuros únicos."]},
reward:{item:"HARDSTONE",narrativeToken:"Sello del Estrato Futuro",globalEffect:"Atlas conserva desacuerdo visible dentro de sus simulaciones.",futurePayoff:"La convergencia mostrará una mesa de propuestas o un relieve deliberadamente incompleto.",whyMeaningful:"La Piedra Dura representa material verificable, no autoridad profética."},
steps:["La estatua cambia después de una votación del consejo.","Nuno encuentra una solución útil junto a una plaza sin salidas.","Iria demuestra que el relieve borra votos disidentes.","El jugador elige mesa de propuestas o archivo inconcluso.","Las capas convocan al Custodio del Relieve.","La batalla de nivel extendido mantiene curación, Mochila y retirada.","Alda cambia la placa y registra el sello.","Una sección vacía permanece visible sin intentar completarse."]
},
{
id:1671,flag:734,title:"La Mina de las Decisiones Sólidas",promise:"Una mina produce gemas nacidas de decisiones irreversibles y convierte cada renuncia del pueblo en riqueza, hasta que los túneles empiezan a exigir elecciones cada vez más crueles.",
identity:"Casa comunal sobre una mina prismática, con balanzas, turnos obreros y vetas que forman bifurcaciones",visual:["Cada cristal contiene la silueta de un camino no elegido.","Los soportes muestran nombres de decisiones en lugar de números de veta.","Una tolva separa mineral extraído de fragmentos desprendidos naturalmente."],ambient:["Las vetas crujen cuando alguien dice para siempre.","Tras la decisión, la maquinaria se detiene o solo recoge cristales liberados."],
narrative:{premise:"La mina de Dara paga la reconstrucción vendiendo minerales que aparecen cuando alguien toma una decisión irreversible.",centralQuestion:"¿Puede una comunidad beneficiarse de sus decisiones sin empezar a fabricar sacrificios para mantener la producción?",setup:"Bren renuncia a volver con su familia y una veta valiosa surge bajo el turno nocturno.",escalation:"La empresa propone contratos vitalicios porque producen cristales más puros.",reversal:"Ona descubre que cada gema solidifica una posibilidad descartada y debilita la capacidad de cambiar de opinión cerca de la mina.",resolution:"El jugador decide cerrar las vetas activas y restaurar túneles o recoger únicamente fragmentos que se desprendan sin provocar decisiones.",globalConnection:"El sello veintisiete revela que Atlas obtiene estabilidad mineralizando la posibilidad de rectificar."},
voice:{tone:"obrero, directo y responsable",lexicon:["veta","turno","cuña","renuncia","fragmento","contrato","rectificar"],sentenceRule:"Dara contabiliza; Bren habla con verbos de trabajo; Ona describe posibilidades como presión geológica."},
npcs:[
N("Dara Veta","trchar008","administradora cooperativa","Usó los minerales para financiar hogares y equipos de seguridad.","La mina sostuvo al pueblo y ahora depende de contratos que vuelven permanente cualquier elección.","Cerrar el incentivo cruel sin abandonar salarios ni reparación.","Que la transición convierta una victoria comunitaria en desempleo.","Nombra ingreso, costo y quién soporta cada uno.",D(["Ingresó una gema. Costó una despedida. El balance no estaba completo.","Pagamos techos con decisiones que nadie podía revisar.","La cooperativa dejó de serlo cuando la veta empezó a elegir socios."],["Se suspende el contrato vitalicio; el turno cobra igual.","Nadie toma decisiones junto al frente de extracción."],["El fondo mineral paga restauración y salarios de transición.","Publicamos qué decisión originó cada lote consentido.","La cooperativa recuperó el derecho a cambiar de plan."],["Un buen balance permite cerrar la mina.","El salario no debe depender de una herida permanente."])),
N("Bren Cuña","trchar009","capataz del turno nocturno","Su renuncia produjo la veta más rentable del mes.","Defiende el trabajo y usa la gema para evitar admitir que quiere volver con su familia.","Recuperar la posibilidad de rectificar sin negar a su cuadrilla.","Que romper su decisión derrumbe literalmente el túnel.","Describe emociones mediante herramientas y tareas.",D(["Clavé una cuña en el camino de vuelta y la roca respondió.","La gema paga veinte turnos; mi silencio paga el resto.","No sé si quiero volver. La mina convirtió no sé en nunca."],["Retiren la cuña del frente; esta decisión necesita aire.","El soporte aguanta sin mi promesa."],["Escribí a mi familia sin jurar resultado.","La cuadrilla aprendió a asegurar roca, no destinos.","Mi gema queda en el museo con una bisagra al lado."],["Una herramienta sirve porque también puede guardarse.","El turno termina aunque la veta siga abierta."])),
N("Ona Presión","NPC 05","geóloga de seguridad","Mide cómo las vetas alteran la voluntad cerca de los túneles.","Calló resultados tempranos para terminar una campaña de muestreo concluyente.","Probar el efecto y devolver opciones cuanto antes.","Que datos incompletos permitan negar todo el peligro.","Da una medición y la decisión práctica que permite.",D(["Presión alta, duda baja: alejamos la sala de contratos hoy.","Esperé una muestra perfecta mientras tres personas firmaban para siempre.","La veta no lee mentes; endurece la salida menos elegida."],["La presión sube con la palabra irreversible.","Recojan solo el fragmento ya suelto."],["Los sensores publican datos en cada entrada.","Mi informe incluye el costo de haber esperado.","La geología volvió a describir roca, no a justificar contratos."],["Una medición incierta puede sostener una pausa segura.","Rectificar también libera presión."]))
],
battle:{trainerName:"Regente de las Vetas",trainerType:"HIKER",sprite:"trchar009",storyToldByTeam:"El equipo recorre brillo, extracción y permanencia hasta una guardiana que devuelve movilidad a las decisiones solidificadas.",counterplayHint:"Roca y Acero sufren ante Agua, Planta, Tierra y Lucha; el rango 101–107 permite crecimiento postgame con objetos y reintento.",canLose:true,bagAllowed:true,doubleBattle:false,team:[
P("SABLEYE",101,"valor oculto",["DARKPULSE","SHADOWBALL","POWERGEM","WILLOWISP"],"LEFTOVERS","Encuentra riqueza donde nadie registró el costo."),
P("CARBINK",102,"decisión cristalizada",["POWERGEM","DAZZLINGGLEAM","PSYCHIC","STEALTHROCK"],"LEFTOVERS","Encierra una posibilidad descartada."),
P("GIGALITH",103,"producción pesada",["STONEEDGE","EARTHQUAKE","SUPERPOWER","HEAVYSLAM"],"ASSAULTVEST","Representa infraestructura que depende de extraer más."),
P("CRADILY",104,"túnel restaurado",["GIGADRAIN","POWERGEM","EARTHPOWER","RECOVER"],"LEFTOVERS","Devuelve vida a cámaras abandonadas."),
P("METAGROSS",105,"contrato rígido",["METEORMASH","PSYCHIC","EARTHQUAKE","BULLETPUNCH"],"ASSAULTVEST","Hace visible la fuerza de una decisión convertida en sistema."),
P("DIANCIE",107,"posibilidad liberada",["POWERGEM","DAZZLINGGLEAM","PSYCHIC","CALMMIND"],"LIFEORB","Cierra transformando presión sin exigir sacrificio.") ]},
decision:{question:"¿Cómo continuará la economía minera?",options:["Cerrar vetas y restaurar túneles","Recoger solo fragmentos desprendidos"],immediateDifferences:["Dara usa el fondo común para una transición laboral.","Ona instala tolvas pasivas lejos de salas de decisión."],laterDifferences:["La mina se convertirá en vivero subterráneo y archivo obrero.","Los ingresos serán menores pero ninguna gema dependerá de una renuncia provocada."]},
reward:{item:"EVERSTONE",narrativeToken:"Sello de la Rectificación",globalEffect:"Atlas deja de convertir decisiones revisables en materia permanente.",futurePayoff:"El final reconocerá una mina restaurada o una recolección pasiva supervisada.",whyMeaningful:"La Piedra Eterna deja de exigir permanencia y recuerda que incluso conservar algo debe ser elegido."},
steps:["Una veta surge cuando Bren dice nunca volveré.","Dara presenta contratos que aumentarían la producción.","Ona demuestra que la mina reduce la capacidad de rectificar.","El jugador elige cierre restaurativo o recolección pasiva.","Los cristales convocan al Regente de las Vetas.","La batalla extendida ofrece curación y salida.","La cooperativa cambia el modelo y registra el sello.","Bren retira una cuña sin que el túnel se derrumbe."]
},
{
id:1696,flag:735,title:"El Peaje de los Sueños Prestados",promise:"Una estación onírica conecta dimensiones cobrando recuerdos tranquilos como peaje, y sus viajeros despiertan a salvo pero incapaces de descansar en sus propias vidas.",
identity:"Gimnasio convertido en terminal de sueño, con camas-andén, ventanillas de niebla y puertas pintadas",visual:["Cada billete muestra una siesta que su dueño ya no recuerda.","Las puertas dimensionales solo se ven en reflejos de almohadas.","Una sala gratuita permanece cerrada por falta de recuerdos cobrables."],ambient:["Anuncios susurrados cambian según quién cierra los ojos.","Tras la decisión, el murmullo cobra energía comunitaria o las puertas se apagan."],
narrative:{premise:"La terminal de Soren permite viajar entre sectores durante el sueño a cambio de un recuerdo de descanso.",centralQuestion:"¿Una ruta imprescindible sigue siendo voluntaria cuando el precio reduce la capacidad de recuperarse y decidir?",setup:"Mela usa el servicio para visitar a su hermano y ya no puede dormir sin comprar otro billete.",escalation:"Los peajes alimentan una dimensión intermedia que empieza a vender sueños reciclados.",reversal:"Yara descubre que las puertas pueden sostenerse con turnos cortos de sueño compartido y no necesitan extraer recuerdos completos.",resolution:"El jugador decide crear una cooperativa con aportes limitados y revocables o cerrar la terminal hasta encontrar energía no cognitiva.",globalConnection:"El sello veintiocho revela que Atlas financia conexiones consumiendo la recuperación de quienes más dependen de ellas."},
voice:{tone:"onírico, lírico y concreto",lexicon:["sueño","peaje","andén","vigilia","almohada","umbral","descanso"],sentenceRule:"Soren anuncia; Mela habla desde el cansancio; Yara separa sueño, recuerdo y energía."},
npcs:[
N("Soren Andén","trchar028","administrador onírico","Mantiene la única ruta rápida entre familias separadas.","Llama voluntario al peaje aunque sabe que muchos viajeros no tienen alternativa.","Conservar conexión sin extraer descanso acumulativamente.","Que cerrar la terminal vuelva a aislar a quienes ya confían en ella.","Anuncia consecuencias como horarios de salida.",D(["Próxima partida: al cerrar los ojos. Llegada: antes de sentirse descansado.","Cobré siestas pequeñas hasta formar una deuda enorme.","La terminal conecta hogares y desconecta a sus viajeros de la noche."],["Servicio suspendido en el andén tres.","Nadie paga otro recuerdo durante la prueba."],["Cada aporte tiene límite, registro y devolución posible.","Los horarios incluyen días sin servicio.","Aprendí a anunciar también cuándo una ruta no debe abrir."],["Un tren vacío puede estar cuidando a sus pasajeros.","La puntualidad no justifica llegar agotado."])),
N("Mela Vigilia","NPC 04","viajera frecuente","Cruza cada noche para cuidar a su hermano en otro sector.","Necesita la ruta y oculta su agotamiento para que no la cierren.","Visitar a su familia sin perder capacidad de vivir despierta.","Que admitir dependencia la convierta en razón para clausurar todo.","Cuenta las noches y olvida los adjetivos.",D(["Siete noches. Tres visitas. Ninguna mañana completa.","Recuerdo la cama, no la sensación de haber dormido.","Dije que estaba bien porque la alternativa era no verlo."],["Ocho noches. Esta vez no cruzo sola.","Mi billete intenta llevarse la última siesta tranquila."],["Visito menos y despierto sabiendo dónde estoy.","Mi hermano participa en el horario, no solo me espera.","La novena noche tuvo sueño propio."],["El cansancio vuelve todas las puertas urgentes.","Descansar también es una forma de llegar."])),
N("Yara Hipnagoga","trchar008","investigadora del umbral","Mide la energía de sueños compartidos.","Probó el modelo alternativo usando voluntarios sin explicar cuánto recordarían.","Crear un sistema transparente con aportes pequeños.","Que toda investigación onírica repita la extracción bajo otro nombre.","Diferencia energía, contenido y consentimiento.",D(["Energía: suficiente. Contenido: innecesario. Consentimiento: mal explicado.","La puerta necesita sincronía, no la infancia de nadie.","Mi prueba funcionó y aun así debo repetirla con reglas justas."],["Corten el contenido; mantengan solo el pulso.","La niebla responde a seis siestas breves."],["El protocolo prohíbe almacenar imágenes personales.","Cada participante ve y retira su aporte.","La terminal funciona menos horas y cuesta menos vida."],["Un sueño compartido no tiene que ser un secreto compartido.","La ciencia también debe despertarse a tiempo."]))
],
battle:{trainerName:"Revisora del Umbral",trainerType:"PSYCHIC_F",sprite:"trchar069",storyToldByTeam:"El equipo avanza desde somnolencia inducida y sueños almacenados hacia guardianes que protegen descanso y tránsito por igual.",counterplayHint:"Psíquico domina, pero Siniestro, Fantasma, Bicho y cambios de estado ofrecen respuestas; niveles 102–108 mantienen curación y Mochila disponibles.",canLose:true,bagAllowed:true,doubleBattle:false,team:[
P("HYPNO",102,"cobrador de imágenes",["PSYCHIC","SHADOWBALL","FOCUSBLAST","HYPNOSIS"],"FOCUSSASH","Representa el peaje que confunde sueño con propiedad."),
P("MUSHARNA",103,"depósito onírico",["PSYCHIC","DAZZLINGGLEAM","ENERGYBALL","MOONLIGHT"],"LEFTOVERS","Guarda recuerdos que la puerta no necesita."),
P("KOMALA",104,"descanso inaccesible",["BODYSLAM","EARTHQUAKE","SUCKERPUNCH","PROTECT"],"LEFTOVERS","Encarna la recuperación que los viajeros pierden."),
P("GOTHITELLE",105,"estación intermedia",["PSYCHIC","THUNDERBOLT","DARKPULSE","CALMMIND"],"LEFTOVERS","Mantiene rutas mediante reglas que nadie ve."),
P("DARKRAI",106,"deuda de vigilia",["DARKPULSE","SHADOWBALL","SLUDGEBOMB","NASTYPLOT"],"LIFEORB","Hace visible el daño de consumir descanso repetidamente."),
P("CRESSELIA",108,"ruta reparadora",["PSYCHIC","ICEBEAM","MOONLIGHT","CALMMIND"],"LEFTOVERS","Cierra demostrando que conexión y descanso pueden coexistir.") ]},
decision:{question:"¿Qué futuro tendrá la terminal onírica?",options:["Cooperativa de aportes limitados","Cerrar hasta hallar otra energía"],immediateDifferences:["Yara instala turnos, límites y eliminación inmediata de contenido.","Soren apaga las puertas y coordina transporte convencional."],laterDifferences:["Las rutas abrirán pocas noches con supervisión de viajeros.","La investigación buscará energía no cognitiva sin cobrar recuerdos."]},
reward:{item:"PSYCHICSEED",narrativeToken:"Sello de la Vigilia",globalEffect:"Atlas deja de financiar rutas con recuerdos de descanso.",futurePayoff:"La convergencia recibirá una terminal cooperativa o una ruta convencional reforzada.",whyMeaningful:"La Semilla Psique representa energía limitada que puede plantarse sin entregar una biografía."},
steps:["Mela entrega un recuerdo de descanso y olvida cómo se sentía.","Soren abre una puerta alimentada por peajes acumulados.","Yara demuestra que el contenido personal es innecesario.","El jugador elige cooperativa limitada o cierre temporal.","La niebla convoca a la Revisora del Umbral.","La prueba extendida mantiene objetos y retirada.","La terminal aplica la decisión y entrega el sello.","Mela despierta de una siesta que no fue cobrada."]
},
{
id:1721,flag:736,title:"El Campeón de las Dos Banderas",promise:"Dos ligas pacíficas reclaman al mismo campeón como fundamento legal y deben negociar una legitimidad que no convierta a una persona en trofeo diplomático.",
identity:"Caverna magnética transformada en cámara neutral, con dos podios, banderas y un campo sin emblemas",visual:["Las placas de campeón encajan entre sí pero ocultan una firma personal.","Las banderas se atraen y separan según el tono de la negociación.","El campo central tiene dos entradas y ninguna cabecera."],ambient:["Dos himnos comparten compás sin terminar la misma melodía.","Tras la decisión, suena una rotación acordada o un tema de circuito independiente."],
narrative:{premise:"Mira ganó dos finales durante una convergencia y ambas ligas usan su título para validar tratados y patrocinio.",centralQuestion:"¿Puede una institución compartir legitimidad sin repartirse la vida de quien la representa?",setup:"Darel y Suma evitan una guerra, pero presentan calendarios incompatibles en nombre de Mira.",escalation:"El campo magnético intenta duplicar físicamente el trofeo y divide recuerdos de la final.",reversal:"Mira revela que nunca solicitó ninguno de los títulos: aceptó para impedir que las ligas combatieran.",resolution:"El jugador decide crear un título rotativo con veto personal o permitir que Mira renuncie y funde un circuito neutral.",globalConnection:"El sello veintinueve demuestra que Atlas estabiliza instituciones obligando a una figura a representar versiones incompatibles."},
voice:{tone:"diplomático, ambicioso y personal",lexicon:["delegación","bandera","mandato","calendario","veto","circuito","firma"],sentenceRule:"Mira habla en primera persona; Darel formula tratados; Suma traduce símbolos en consecuencias."},
npcs:[
N("Mira Sinpodio","trchar069","campeona disputada","Ganó ambas finales y vive entre calendarios institucionales.","Sostuvo la paz aceptando títulos que ya no le permiten una vida propia.","Elegir qué representa y cuándo dejar de hacerlo.","Que su renuncia reactive el conflicto que evitó.","Empieza cada respuesta con yo, corrigiendo años de lenguaje institucional.",D(["Yo gané dos combates. Ellos redactaron dos destinos.","Yo acepté las banderas para que nadie levantara otra cosa.","Yo no soy el territorio entre sus ligas."],["Yo autorizo esta prueba, no la apropiación de mi equipo.","Yo puedo detener la ceremonia."],["Yo elegí el calendario y también días sin título.","Yo firmé como persona antes que campeona.","Yo confío en que la paz sobreviva a mi ausencia."],["Yo también puedo perder sin volverme crisis diplomática.","Yo quiero un combate que no ratifique ningún tratado."])),
N("Darel Cláusula","trchar028","delegado de la liga oriental","Redactó el acuerdo que reconoce a Mira como campeona común.","Protege la paz, pero convirtió su consentimiento inicial en mandato indefinido.","Construir legitimidad basada en reglas revisables.","Que una cláusula personal derrumbe acuerdos regionales.","Presenta una cláusula y nombra quién puede vetarla.",D(["Cláusula tercera: representación conjunta. Falta el veto de la representada.","Usé una firma de emergencia como permiso permanente.","La liga necesita ley; no necesita poseer a Mira."],["Enmienda inmediata: la ceremonia se detiene si ella lo pide.","Retiro el calendario presentado sin consulta."],["El tratado sobrevive con cargo rotativo y consentimiento anual.","Publicamos la cláusula que permitió renunciar.","La institución aprendió a no usar una persona como cimiento."],["Una paz robusta admite reemplazos.","Toda firma tiene fecha y contexto."])),
N("Suma Estandarte","trchar008","diplomática de la liga occidental","Custodia símbolos y protocolo de la segunda liga.","Defiende tradición y sabe que el trofeo duplicado está alterando recuerdos públicos.","Separar memoria compartida de propaganda institucional.","Que retirar la bandera sea leído como rendición.","Traduce cada símbolo a un costo cotidiano.",D(["Esta bandera significa unidad; para Mira significa otro mes sin hogar.","El trofeo recuerda una final distinta según quién lo sostiene.","Un símbolo útil no debería exigir una biografía completa."],["Bajo la bandera mientras discutimos su mandato.","El imán está partiendo el recuerdo de la final."],["Las banderas visitan el circuito, no siguen a Mira.","El museo muestra ambas versiones con sus diferencias.","Retirar un símbolo evitó que se convirtiera en frontera."],["Una ceremonia larga también consume días reales.","El respeto se nota cuando un podio puede quedar vacío."]))
],
battle:{trainerName:"Árbitra de Dos Ligas",trainerType:"CHAMPION",sprite:"trchar069",storyToldByTeam:"El equipo reúne seis funciones de campeón provenientes de regiones distintas y termina demostrando que cooperación no requiere una única bandera.",counterplayHint:"La cobertura es amplia, pero cada integrante tiene debilidades comunes y no comparte una condición abusiva; niveles 104–110 permiten preparación postgame y uso libre de objetos.",canLose:true,bagAllowed:true,doubleBattle:false,team:[
P("BRAVIARY",104,"estandarte oriental",["BRAVEBIRD","CLOSECOMBAT","UTURN","ROOST"],"FOCUSSASH","Abre con orgullo institucional visible."),
P("MILOTIC",105,"diplomacia paciente",["SURF","ICEBEAM","DRAGONPULSE","RECOVER"],"LEFTOVERS","Sostiene conversaciones largas sin ceder identidad."),
P("LUCARIO",106,"mandato personal",["AURASPHERE","FLASHCANNON","EXTREMESPEED","SWORDSDANCE"],"LIFEORB","Lee la voluntad detrás del protocolo."),
P("AEGISLASH",107,"título y defensa",["KINGSSHIELD","SHADOWBALL","FLASHCANNON","SACREDSWORD"],"LEFTOVERS","Representa una institución capaz de limitar su poder."),
P("DRAGAPULT",108,"circuito móvil",["DRAGONPULSE","SHADOWBALL","FLAMETHROWER","UTURN"],"LIFEORB","Cruza fronteras sin convertirse en propiedad regional."),
P("CHARIZARD",110,"campeón por elección",["FLAMETHROWER","AIRSLASH","DRAGONPULSE","ROOST"],"LIFEORB","Cierra con una figura icónica que combate sin ratificar banderas.") ]},
decision:{question:"¿Cómo resolverán los dos títulos?",options:["Título rotativo con veto personal","Renuncia y circuito neutral"],immediateDifferences:["Darel añade consentimiento anual y calendario elegido por Mira.","Suma retira ambas placas y financia un circuito sin bandera."],laterDifferences:["Otras figuras podrán compartir cargos sin mandato permanente.","Las ligas medirán legitimidad por reglas y no por poseer al campeón."]},
reward:{item:"FRONTIERPASS",narrativeToken:"Sello de la Delegación",globalEffect:"Atlas deja de usar personas como anclas institucionales obligatorias.",futurePayoff:"El final invitará a una campeona rotativa o a un circuito neutral.",whyMeaningful:"El Pase Frontera abre tránsito entre ligas sin transferir propiedad sobre quien lo usa."},
steps:["Las delegaciones colocan dos placas sobre el mismo podio.","Mira declara que nunca pidió los títulos.","El campo divide el recuerdo de la final en dos versiones.","El jugador elige rotación con veto o circuito neutral.","Los himnos convocan a la Árbitra de Dos Ligas.","La batalla extendida admite preparación, Mochila y derrota segura.","Los delegados reescriben el tratado y registran el sello.","Mira abandona el podio antes de decidir si vuelve al campo."]
},
{
id:1746,flag:737,title:"La Academia del Error Permitido",promise:"Una academia presume de dificultad perfecta mientras castiga la experimentación, hasta que sus mejores alumnos demuestran que un desafío justo debe enseñar por qué se perdió y permitir volver con otra estrategia.",
identity:"Ruta elevada convertida en academia táctica al aire libre, con aulas-campo, paneles de análisis y estaciones de curación",visual:["Los marcadores antiguos solo registran derrotas; los nuevos anotan decisiones.","Una vitrina exhibe objetos prohibidos sin explicar su contrajuego.","Tres rutas llevan al mismo campo con distinta información previa."],ambient:["Un timbre severo se suaviza cuando alguien pide una pista.","Tras la decisión, las aulas anuncian nivel, reglas y rutas de reintento."],
narrative:{premise:"Rector Kade llama excelencia a desafíos que ocultan información y ridiculizan a quien usa apoyo.",centralQuestion:"¿La dificultad mide aprendizaje cuando el jugador no puede distinguir un error táctico de una regla escondida?",setup:"Lina domina los exámenes memorizando trampas y teme no saber adaptarse fuera de ellos.",escalation:"Un simulacro cambia reglas después de empezar y bloquea la graduación de todo un grupo.",reversal:"Boro demuestra que las notas altas correlacionan con acceso previo a soluciones filtradas, no con mejor razonamiento.",resolution:"El jugador decide crear niveles de desafío transparentes con pistas opcionales o reemplazar el ranking por laboratorios cooperativos de contrajuego.",globalConnection:"El sello treinta revela que Atlas usa frustración repetida como filtro porque confunde permanencia con mérito."},
voice:{tone:"analítico, deportivo y pedagógico",lexicon:["apertura","contrajuego","intento","pista","regla","revisión","graduación"],sentenceRule:"Kade sentencia; Lina verbaliza decisiones; Boro compara resultados y acceso."},
npcs:[
N("Kade Umbral","trchar028","rector táctico","Diseñó la academia para preparar entrenadores contra amenazas extremas.","Cree que revelar reglas debilita al alumno y usa humillación para proteger su reputación.","Conservar exigencia sin convertir desconocimiento en culpa.","Que la transparencia revele que varios exámenes eran arbitrarios.","Formula máximas absolutas y luego enfrenta sus excepciones.",D(["La dificultad no explica. Esa fue mi máxima y mi coartada.","Llamé preparación a recordar dónde escondí la regla.","Si una pista destruye el examen, quizá el examen no medía estrategia."],["La prueba anunciará cada condición antes del turno uno.","Nadie pierde acceso a la enfermería por pedir ayuda."],["Publicamos versiones, objetivos y contrajuego esperado.","La excelencia sobrevivió a dejar de burlarse del intento.","Mi evaluación incluye claridad del diseñador."],["Un muro alto no enseña escalada por sí mismo.","La sorpresa sirve en aventura; no siempre en calificación."])),
N("Lina Reintento","trchar008","alumna de máximo rango","Memorizó cada trampa y guía a compañeros en secreto.","Sus resultados dependen de repetir soluciones exactas y teme perder identidad si el sistema cambia.","Aprender a explicar decisiones y adaptar equipos.","Descubrir que su rango medía acceso y memoria.","Nombra apertura, respuesta y alternativa.",D(["Apertura: señuelo. Respuesta: cambio. Alternativa: nunca nos dejaron probarla.","Sé dónde cae cada trampa y no sé por qué funciona.","Ayudé a otros en secreto porque la academia llamaba trampa a enseñar."],["Regla visible: seis Pokémon, objetos permitidos, retirada segura.","Mi alternativa falló y ahora puedo explicar dónde."],["Mi rango se convirtió en tutoría voluntaria.","Diseñé una prueba con tres respuestas válidas.","Perder un intento dejó de borrar el análisis."],["Una guía no juega por ti; te deja formular otra pregunta.","El reintento vale cuando cambia una decisión."])),
N("Boro Muestra","trchar246","analista educativo","Auditó resultados y acceso a soluciones filtradas.","Esperó datos concluyentes mientras cohortes completas quedaban fuera.","Medir aprendizaje sin reducirlo a victorias.","Que la reforma use sus cifras como otra clasificación rígida.","Da comparación, límite y acción inmediata.",D(["Mismo equipo, distinta filtración: cuarenta puntos de diferencia.","La muestra no explica todo; explica suficiente para pausar el ranking.","Esperé significancia mientras los alumnos perdían semestres."],["Condición cambiada: examen inválido, no alumno fallido.","Registren decisiones y no solo resultado."],["El tablero muestra progreso, pistas usadas y estrategias nuevas.","Mis datos no asignan valor personal.","La academia publica también fallos de diseño."],["Medir ayuda si sabemos qué dejamos fuera.","Una victoria puede ser copia; una derrota puede ser aprendizaje."]))
],
battle:{trainerName:"Examinadora Transparente",trainerType:"COOLTRAINER_F",sprite:"trchar008",storyToldByTeam:"El equipo presenta aperturas tácticas reconocibles, respuestas múltiples y una prueba final exigente sin reglas ocultas.",counterplayHint:"Se anuncian clima, prioridad, hazards y cobertura; eliminación de campo, cambios, estados y objetos ofrecen varias rutas en niveles 106–112.",canLose:true,bagAllowed:true,doubleBattle:false,team:[
P("SKARMORY",106,"apertura de hazards",["STEALTHROCK","BRAVEBIRD","ROOST","WHIRLWIND"],"LEFTOVERS","Enseña control de campo con herramientas visibles."),
P("ROTOM",107,"pivote anunciado",["THUNDERBOLT","SHADOWBALL","WILLOWISP","VOLTSWITCH"],"LEFTOVERS","Premia anticipar cambios sin exigir adivinación ciega."),
P("GASTRODON",108,"respuesta defensiva",["SURF","EARTHPOWER","ICEBEAM","RECOVER"],"LEFTOVERS","Ofrece un muro con debilidad clara a Planta."),
P("WEAVILE",109,"presión y prioridad",["ICICLECRASH","NIGHTSLASH","ICESHARD","BRICKBREAK"],"FOCUSSASH","Castiga descuidos sin encerrar el combate."),
P("VOLCARONA",110,"condición de victoria",["FIERYDANCE","BUGBUZZ","GIGADRAIN","QUIVERDANCE"],"LIFEORB","Exige responder a preparación visible."),
P("GARCHOMP",112,"examen adaptable",["DRAGONCLAW","EARTHQUAKE","STONEEDGE","SWORDSDANCE"],"LIFEORB","Cierra con potencia directa y contrajuego común.") ]},
decision:{question:"¿Cómo medirá aprendizaje la academia?",options:["Niveles transparentes con pistas","Laboratorios cooperativos sin ranking"],immediateDifferences:["Kade publica reglas, dificultad y pistas opcionales.","Lina convierte exámenes en problemas de equipo revisables."],laterDifferences:["Cada alumno elegirá exigencia sin perder acceso a progreso.","Los sectores compartirán estrategias y fallos de diseño sin jerarquía única."]},
reward:{item:"EXPCHARM",narrativeToken:"Sello del Contrajuego",globalEffect:"Atlas distingue desafío justo de crueldad informativa.",futurePayoff:"La convergencia ofrecerá niveles transparentes o un laboratorio cooperativo.",whyMeaningful:"El Amuleto Exp. acompaña el crecimiento hasta nivel 150 y premia aprender, no repetir castigo."},
steps:["Un simulacro cambia reglas después de comenzar.","Lina revela que memorizó trampas en lugar de principios.","Boro muestra la relación entre filtraciones y rango.","El jugador elige niveles transparentes o laboratorios cooperativos.","Los paneles convocan a la Examinadora Transparente.","La batalla de nivel 106–112 permite Mochila, curación y salida.","La academia publica su reforma y entrega el sello.","Un alumno pierde, anota una alternativa y conserva su progreso."]
}
];
writeBatch(7,rows,"atlas_tier1_blueprints_batch07.json");
