#!/usr/bin/env node
/**
 * Tier 2 curados: macrociclo 06 (25 rutas, mapas 1733–1933) y macrociclo 07
 * (10 rutas, mapas 1940–2015). Completan las 120 rutas Tier 2 de Atlas Mil.
 *
 * Voces: sectores 29–40 de `content/atlas_narrative_seeds.json` (Bahía Relámpago
 * hasta Umbral Mil), con los ejes de crossover ya aprobados. Cada NPC conserva
 * motivación, conflicto, error reconocido y líneas propias; las parejas Pokémon
 * se citan con su nombre de presentación y no como un símbolo de datos.
 */
import fs from "node:fs";
import path from "node:path";
import { ROOT } from "./lib/fire_ash_registry.mjs";

const sentence = (text) => /[.!?…]$/.test(text) ? text : `${text}.`;
function N(name, sprite, role, partner, partnerName, want, error, before, after) {
  return {
    name, sprite, role, partnerPokemon: partner,
    motivation: sentence(`Quiere ${want}`),
    conflict: sentence(`Su error anterior fue que ${error}`),
    dialogue: { before: before.map(sentence), after: after.map(sentence) },
    partnerName,
  };
}
const R = (mapId, title, promise, objective, mechanic, npcs, decision, consequence, reward) => ({ mapId, title, promise, objective, mechanic, npcs, decision, consequence, reward });

const specs06 = [
  R(1733, "La Antena que Negociaba el Viento",
    "Dos gremios de mensajería se disputan la antena de la torre y la venta privada de la franja de calma retrasa a quien no puede pagarla.",
    "Publicar ventanas de vuelo medibles y repartir la franja de calma sin privilegios secretos.",
    ["Turnos de ráfaga", ["Medir el viento antes de fijar el turno.", "Anunciar cada ventana en la torre y en el puerto.", "Devolver la franja de calma al reparto común si sobra."], "Las antenas de emergencia y el regreso al puerto nunca se alquilan."], [
      N("Zalo Viento", "trchar008", "coordinador de aerovías", "UNFEZANT", "Unfezant", "ordenar el cielo con horarios que cualquiera pueda leer", "vendió la franja de calma a un gremio y llamó al resto retraso",
        ["La torre solo anuncia las ventanas que pagan los gremios grandes", "me apresuré: vendí la franja de calma y taché los retrasos del cartel", "redactaré un cuadro público con viento, ventana y espera estimada"],
        ["las ventanas cuelgan del cartel y ningún gremio compra la hora tranquila", "Unfezant patrulla la franja sin pedir el sello de nadie", "el cuadro se revisará cada tormenta, no cada contrato"]),
      N("Yessa Mesa", "NPC 04", "embajadora de dos ligas", "SWANNA", "Swanna", "firmar un tratado de vuelo que las dos ligas respeten sin elegir campeón", "redactó tratados tan ambiciosos que ninguna liga quiso firmarlos",
        ["Cada liga me devuelve el borrador con una exigencia imposible", "tardé en reconocer que pedía juramentos donde bastaban ventanas", "propondré tres artículos cortos y dejaré el resto para el próximo consejo"],
        ["el tratado quedó en una página y firmaron las dos ligas", "Swanna traslada los pliegos sin elegir bando", "cuando cambie el viento, el tratado admite un anexo breve"])],
    ["¿Quién publicará las ventanas de vuelo?", ["Autoridad portuaria única", "Consejo rotatorio de gremios"]],
    ["el cuarto de la antena pasa a manos del puerto", "cada gremio rotará la custodia del cartel"],
    ["STICKYBARB", "Fija la ventana de viento acordada para que ningún gremio la capture en secreto."]),
  R(1740, "El Consejo que Compartía un Campeón",
    "Dos ligas reclaman al mismo campeón sin querer combatir y las biografías oficiales se corrigen entre sí cada semana.",
    "Conservar una biografía original intacta y repartir copias selladas que ninguna liga pueda reescribir.",
    ["Registro doble", ["Fotografiar el original antes de repartir copias.", "Nunca editar las palabras del propio campeón.", "Publicar quién custodia el original cada temporada."], "La caja pública del ayuntamiento permanece cerrada con dos llaves."], [
      N("Emba Sellado", "trchar009", "archivista de ligas", "MANDIBUZZ", "Mandibuzz", "custodiar una biografía que ninguna liga pueda editar", "permitió que cada liga corrigiera la misma página",
        ["Mi archivo guarda tres versiones del mismo discurso de victoria", "me apresuré: abrí la página común y cada liga la corrigió a su gusto", "separaré original, copia sellada y errata pública"],
        ["el original descansa en la caja y las copias llevan fecha", "Mandibuzz vigila el fondo de la caja sin leer los sellos", "cada errata pedirá firmas de las dos ligas"]),
      N("Tico Sigilo", "NPC 04", "diplomático de pasillos", "LIEPARD", "Liepard", "resolver la disputa sin que el campeón deba elegir bandera", "convenció al campeón de leer un bando delante del otro",
        ["El campeón me pidió no volver a elegir entre sus maestros", "tardé en reconocer que convertí su silencio en una declaración", "preguntaré antes y hablaré después, en ese orden"],
        ["el campeón no firmó ninguna bandera y el consejo lo respeta", "Liepard entra y sale por la puerta que nadie custodia", "las próximas visitas tendrán preguntas enviadas por escrito"])],
    ["¿Dónde vivirá la biografía del campeón?", ["Original en caja pública", "Copias selladas en cada liga"]],
    ["la caja pública recibe el original y sus llaves quedan separadas", "las ligas custodian copias y el original viaja cada invierno"],
    ["RAZORFANG", "Corta de raíz una reclamación que intenta comerse la historia de su protagonista."]),
  R(1751, "La Academia que Vendía Dificultad",
    "Una academia del centro comercial vende crueldad disfrazada de reto y expulsa a quien pregunta por la contrajugada.",
    "Publicar la contrajugada de cada ejercicio antes de venderlo como dificultad.",
    ["Evaluación de contrajuego", ["Cada ejercicio declara su contrajugada.", "La dificultad se publica con mapa y tiempos.", "El alumno puede detener el ejercicio sin sanción."], "El área de descanso nunca forma parte del programa de reto."], [
      N("Nive Redoble", "trchar008", "entrenadora jefa", "GRAPPLOCT", "Grapploct", "vender entrenamiento exigente sin aplastar al alumno", "etiquetó como nivel experto un ejercicio sin salida posible",
        ["Los carteles dicen nivel experto y nadie explica cómo salir", "me precipité: vendí dificultad sin revisar si el alumno podía rendirse", "colocaré la contrajugada junto al precio de cada programa"],
        ["cada programa cuelga su contrajugada y su tiempos de salida", "Grapploct se retira cuando el alumno levanta la mano", "las versiones difíciles tendrán también su mapa de retirada"]),
      N("Coto Marcador", "NPC 04", "analista deportivo", "PANGORO", "Pangoro", "medir progreso real en vez de sufrimiento acumulado", "contó como progreso cada sesión abandonada a gritos",
        ["Mis gráficas suben cuando alguien se retira destrozado", "tardé en reconocer que medía aguante y no aprendizaje", "separaré rendimiento, descanso y curva de error"],
        ["los informes distinguen descanso de retroceso", "Pangoro marca cada pausa sin penalizarla", "el seguimiento incluirá preguntas, no solo cronómetros"])],
    ["¿Qué se publicará en el cartel del centro?", ["Mapa de contrajugadas", "Solo el nivel de exigencia"]],
    ["el centro comercial exhibe la lista completa de contrajugadas", "los alumnos exigen anexos antes de cada nuevo programa"],
    ["SOFTSAND", "Da peso a un entrenamiento exigente que no necesita hundir a nadie para demostrarlo."]),
  R(1758, "El Análisis que Fichaba a los Jugadores",
    "Los exploradores de la costa reducen jugadores a estadísticas y venden predicciones de carácter que condicionan a los equipos.",
    "Separar el análisis deportivo del carácter y permitir que cada jugador lea su propio expediente.",
    ["Hoja de lectura doble", ["La hoja de datos no viaja junto a la de carácter.", "El jugador puede leer y anotar su expediente.", "Toda predicción caduca al terminar la temporada."], "El cuarto de análisis cierra sin expedientes a la vista."], [
      N("Sera Gráfica", "trchar009", "scout de costa", "PERSIAN", "Persian", "descubrir talento sin vender retratos de personalidad", "comerció con notas de carácter que los equipos usaron para presionar",
        ["Un club me pidió la hoja de carácter antes que las de datos", "me apresuré: vendí mis notas y las llamé lectura de juego", "devolveré cada nota de carácter a su protagonista"],
        ["los expedientes de carácter vuelven firmados por sus dueños", "Persian se sienta sobre las carpetas cerradas", "las predicciones se archivarán con fecha de caducidad"]),
      N("Ciro Promedio", "NPC 04", "consejero del instituto", "LUMINEON", "Lumineon", "que los jóvenes jueguen sin un rótulo pegado a la espalda", "dejó que el boletín deportivo publicara apodos de diagnóstico",
        ["Los apodos del boletín llegaron antes que los diplomas", "tardé en reconocer que un apodo explica menos de lo que marca", "publicaré logros concretos y retiraré diagnósticos"],
        ["el boletín cita jugadas, no etiquetas", "Lumineon acompaña a los alumnos a leer sus datos", "cada temporada los apodos caducan con las predicciones"])],
    ["¿Cómo se guardará el análisis?", ["Datos y carácter separados", "Un solo expediente completo"]],
    ["el cuarto de análisis abre dos archivadores con llaves distintas", "los clubes firman un acuerdo de lectura con caducidad"],
    ["SHARPBEAK", "Apunta a la jugada que ningún número de la hoja había anunciado."]),
  R(1765, "El Mapa de Tinta que Explicaba Atajos",
    "Un mapa de tinta traza atajos que arruinan la primera visita de quien llega nuevo y los veteranos borran los desvíos amables.",
    "Dibujar la línea novata y la línea experta sin que ninguna oculte a la otra.",
    ["Doble lectura del mapa", ["Marcar requisitos junto a cada atajo.", "Mantener el desvío amable dibujado.", "Permitir corregir con tinta lavable."], "La boca de la cueva conserva un mapa completo en lámina rígida."], [
      N("Brisa Cuaderno", "trchar008", "cartógrafa de cueva", "WOOBAT", "Woobat", "mapas que sirvan también a quien llega temeroso", "redibujó los atajos encima de los desvíos lentos",
        ["Los novatos entran por el atajo y salen rendidos", "me apresuré: taché los desvíos lentos para limpiar el plano", "dibujaré la cueva en dos lecturas y separaré la tinta"],
        ["el plano muestra línea novata y línea experta en capas", "Woobat ecolocaliza los bordes que la tinta lavable respeta", "las correcciones llevarán fecha y autor"]),
      N("Rulo Atajo", "NPC 04", "guía de escalada", "GOLURK", "Golurk", "mostrar atajos sin convertirlos en trampa", "ocultó los requisitos de un atajo para que pareciera corto",
        ["Mi atajo favorito exige fuerza que no todos llevan encima", "tardé en reconocer que un atajo mudo es una trampa", "escribiré requisitos y tiempos en la misma curva"],
        ["cada atajo declara qué pide antes de prometer nada", "Golurk sostiene la lámina mientras los novatos dibujan", "la ruta larga seguirá señalizada como alternativa digna"])],
    ["¿Qué línea abrirá el mapa?", ["Línea novata por defecto", "Línea experta por defecto"]],
    ["el mapa abre en la lectura lenta y permite cambiar de capa", "los veteranos reciben su propia lámina sin tachar la otra"],
    ["POISONBARB", "Señala con picor el atajo que estorbó a quien llegó por primera vez."]),
  R(1776, "La Caja que Guardaba un Latido",
    "Una caja de relojería guarda una melodía que solo suena cuando alguien decide escucharla y los turistas la graban sin permiso.",
    "Que la caja solo suene con escucha voluntaria y conserve siempre un botón de silencio.",
    ["Escucha voluntaria", ["La caja nunca arranca sola.", "El volumen tiene techo y el silencio botón propio.", "Las grabaciones requieren permiso firmado."], "La reserva de engranajes funciona en silencio y la salida no toca la caja."], [
      N("Ori Relicario", "trchar009", "relojero de reserva", "CHIMECHO", "Chimecho", "mantener la caja viva sin imponer su canción", "programó la melodía para sonar a la hora en punto",
        ["La caja arrancaba sola y la gente huía del taller", "me apresuré: quise que la caja fuera oída y la hice inevitable", "la melodía quedará detrás de un gesto, no de un reloj"],
        ["la caja suena solo cuando alguien coloca la mano", "Chimecho imita el pulso sin levantar el volumen", "el botón de silencio quedará siempre a la vista"]),
      N("Nao Latido", "NPC 04", "visitante recurrente", "MISDREAVUS", "Misdreavus", "escuchar la melodía sin convertirla en espectáculo", "grabó la canción y la regaló como tono de llamada",
        ["La canción sonaba en veinte bolsillos al mismo tiempo", "tardé en reconocer que había vendido una intimidad prestada", "borraré las copias y pediré escuchar de nuevo"],
        ["las copias se apagaron y la caja recuperó su sitio", "Misdreavus se queda quieta cuando el volumen baja", "vendré sin grabadora y con las manos libres"])],
    ["¿Cómo se abrirá la caja?", ["Solo con gesto de escucha", "Con función de visita programada"]],
    ["el taller impone escucha voluntaria y guarda un registro de permisos", "la reserva publica su regla de silencio en la entrada"],
    ["SPELLTAG", "Recuerda una voz sin obligar a nadie a volver a oírla."]),
  R(1783, "La Casa que Repetía la Canción",
    "La caja musical de una casa repite la melodía de su antigua dueña y los vecinos quieren grabarla para venderla como tono de llamada.",
    "Que la caja conserve su melodía sin convertirla en producto y pueda descansar en silencio.",
    ["Permiso de grabación", ["Pedir permiso antes de grabar.", "Limitar los bucles diarios de la caja.", "Respetar las temporadas de silencio acordadas."], "La ventana de la casa y el camino de regreso quedan fuera del negocio."], [
      N("Cleo Caja", "trchar008", "guardiana de la melodía", "KRICKETUNE", "Kricketune", "conservar la canción sin vender la voz de su amiga", "ensayó la melodía en bucles hasta romper el muelle",
        ["La casa repite y repite hasta que la madera se queja", "me apresuré: forcé el bucle para que nadie se perdiera una nota", "pondré turnos de escucha y dejaré el muelle descansar"],
        ["la caja canta en horarios y guarda silencio las tardes", "Kricketune acompaña la melodía sin competir con ella", "los permisos se firman con nombre y fecha"]),
      N("Rin Melodía", "NPC 04", "compositora del pueblo", "JIGGLYPUFF", "Jigglypuff", "aprender la melodía sin copiarla para el mercado", "compuso un arreglo y lo registró a su nombre",
        ["Mi arreglo de la canción ya figura en tres tiendas", "tardé en reconocer que había puesto mi firma sobre una herencia", "devolveré los registros y citaré la fuente"],
        ["las tiendas retiraron el registro y la casa quedó tranquila", "Jigglypuff tararea la melodía solo cuando se lo piden", "cada arreglo nuevo citará a la casa y a su guardiana"])],
    ["¿Qué hará el pueblo con la canción?", ["Archivo comunitario citando la fuente", "Producto musical con regalías"]],
    ["el archivo del pueblo custodia la melodía con su historia", "las regalías se fijan por escrito y nadie hereda la voz"],
    ["TWISTEDSPOON", "Gira una melodía prestada hacia quien decidió escucharla y no hacia quien quiso venderla."]),
  R(1790, "La Última Campana del Silencio",
    "Una campana de la meseta solo suena cuando la zona elige callar y los veteranos de duelo exigen horarios que nadie publicó.",
    "Fijar un horario de silencio por escrito y dejar la campana atada al acuerdo, no al ánimo.",
    ["Horario de silencio", ["Publicar el horario con días y motivos.", "Permitir pedir campana apagada por escrito.", "Notificar a los veteranos antes de cada cambio."], "El camino de la meseta y el retorno permanecen transitables aunque la campana calle."], [
      N("Vera Silencio", "trchar009", "guardiana de la campana", "ZANGOOSE", "Zangoose", "que el silencio de la meseta tenga calendario", "decidió los toques según su propio cansancio",
        ["La campana suena cuando yo puedo más, no cuando toca", "me apresuré: convertí mi agenda en el calendario del pueblo", "colgaré el horario en la puerta y lo firmarán los vecinos"],
        ["el horario cuelga firmado y la campana obedece al papel", "Zangoose vela el reloj sin moverse del pie de la torre", "cada cambio se avisará con tres días de antelación"]),
      N("Hugo Badajo", "NPC 04", "veterano de duelos", "SEVIPER", "Seviper", "recibir el aviso del silencio antes que la campana", "organizó duelos nocturnos cuando el pueblo pedía calma",
        ["Mis duelos terminaban justo cuando la gente cerraba ventanas", "tardé en reconocer que el horario importaba más que la costumbre", "mis duelos tendrán permiso y hora cerrada"],
        ["los duelos se anuncian y terminan antes del toque", "Seviper se retira con el primer aviso, sin discusión", "el calendario del veterano quedará junto al de la campana"])],
    ["¿Quién firmará el horario de silencio?", ["Asamblea de la meseta", "Guardiana con revisión trimestral"]],
    ["la asamblea firma el calendario y lo reparte en las casas", "la guardiana publica actas de cada revisión"],
    ["HARDSTONE", "Ancla la campana a un horario escrito en vez de al ánimo de quien toca."]),
  R(1801, "El Retrato que Pedía No Rehacerse",
    "El retrato de un héroe caído pide no reconstruirse en leyenda y el comité de memoria quiere repintarlo para el aniversario.",
    "Restaurar sin reescribir: mantener las pinceladas originales y añadir contexto en lugar de épica.",
    ["Restauración con límites", ["Conservar el trazo original.", "Añadir cartela de contexto, no nueva épica.", "La familia ejerce veto sobre cualquier cambio."], "La sala del retrato conserva una copia fotográfica de control."], [
      N("Iris Retrato", "trchar008", "restauradora de memoria", "TREVENANT", "Trevenant", "cuidar el retrato sin convertir al retratado en estatua", "repintó la sonrisa para que la cara luciera heroica",
        ["El comité me pidió un héroe más luminoso que el original", "me precipité: repinté una sonrisa que el retrato no tenía", "mediré cada capa y devolveré el trazo primero"],
        ["el retrato recuperó su gesto y la cartela explica el resto", "Trevenant señala las capas nuevas bajo la luz rasante", "la familia revisará la restauración antes de colgarla"]),
      N("Osco Placa", "NPC 04", "presidente del comité", "DUSKULL", "Duskull", "honrar sin fabricar un héroe cómodo", "encargó un discurso que borraba las dudas del retratado",
        ["Mi discurso describía a un héroe que nadie conoció", "tardé en reconocer que limpié su memoria para el público", "leeré sus propias cartas y dejaré las dudas en pie"],
        ["el aniversario cita cartas reales y silencios reales", "Duskull apaga el foco cuando el discurso se alarga", "el próximo discurso lo redacta la familia con el archivo"])],
    ["¿Cómo se verá el retrato en el aniversario?", ["Restauración mínima con cartela", "Repintado luminoso de gala"]],
    ["la sala inaugura la cartela y prohíbe repintar el lienzo", "el comité aprueba un reglamento de restauración con límites"],
    ["MIRACLESEED", "Hace crecer la memoria real, no la versión decorativa que se sembró sobre ella."]),
  R(1808, "La Avenida que Contaba los Ausentes",
    "Las placas de una avenida recuerdan a entrenadores desaparecidos y el ayuntamiento quiere cambiar el nombre por celebridades vivas.",
    "Conservar las placas con su fecha y mover cualquier retiro al archivo, nunca a la basura.",
    ["Placa con fecha", ["Las placas siguen un orden cronológico.", "Cada alta requiere prueba o familiar.", "Los retires pasan al archivo con acta."], "La calle de servicio y el regreso al centro permanecen sin placas para no interferir."], [
      N("Vito Placa", "trchar009", "encargado de placas", "MEOWSTIC", "Meowstic", "mantener el calendario de los ausentes legible", "aceptó placas de encargo sin comprobar su historia",
        ["Tres placas nuevas cuentan historias que nadie puede confirmar", "me apresuré: acepté encargos bonitos y olvidé las fechas", "pediré prueba y devolveré cada placa sin fecha"],
        ["las placas vuelven ordenadas y las dudosas esperan en el archivo", "Meowstic vigila el expediente de cada nombre", "las nuevas altas citarán quién las solicitó"]),
      N("Ada Ausente", "NPC 04", "familiar de un desaparecido", "PYROAR", "Pyroar", "que la placa de su hermano no cambie de calle por un concurso", "cedió ante la oferta de una placa más grande a cambio de olvidar la vieja",
        ["El ayuntamiento ofrecía brillo a cambio de retirar la placa pequeña", "tardé en reconocer que vendía un nombre por un foco", "la placa se queda donde está, con su fecha"],
        ["la avenida conserva su calendario y el nombre de su hermano", "Pyroar descansa junto a la placa sin escolta", "los familiares firmarán juntos las próximas altas"])],
    ["¿Qué vivirá en la avenida?", ["Placas cronológicas de ausentes", "Paseo de celebridades vivas"]],
    ["la avenida recupera su calendario y abre un libro de visitas", "el ayuntamiento publica el acta de retirada como documento de archivo"],
    ["REAPERCLOTH", "Cubre un recuerdo sin sofocarlo: retira el foco, no el nombre."]),
  R(1815, "El Jardín de los Nombres Cortados",
    "Las flores plantadas por cada entrenador ausente se podan en figuras decorativas y las familias quieren que crezcan con su propia forma.",
    "Dejar crecer las plantas sin podarlas en siluetas ajenas y registrar quién eligió cada especie.",
    ["Crecimiento registrado", ["Medir sin podar en figuras.", "Registrar la especie elegida por cada familia.", "Permitir que una planta se marchite con dignidad."], "El sendero del jardín y la salida permanecen abiertos en toda estación."], [
      N("Hera Jardín", "trchar008", "jardinera del recuerdo", "FLOETTE", "Floette", "cuidar un jardín que no finge formas ajenas", "recortó las flores en siluetas de medallas",
        ["El jardín parecía una vitrina de premios y no un recuerdo", "me apresuré: podé formas bonitas y borré el crecimiento real", "registraré especie, fecha y manos que plantaron"],
        ["las plantas crecen a su manera y el cuaderno guarda la historia", "Floette riega sin tijeras y cambia de maceta con permiso", "las familias elegirán especie y momento de poda"]),
      N("Milo Corteza", "NPC 04", "familiar jardinero", "MIGHTYENA", "Mightyena", "que la planta de su padre parezca suya y no un trofeo", "pidió una poda en forma de medalla para impresionar a los jueces",
        ["La medalla de hojas gustó más que la planta de mi padre", "tardé en reconocer que cambié su memoria por un concurso", "volveré a la especie que él llevaba en la mochila"],
        ["la planta recupera su forma y el jardín deja de competir", "Mightyena protege el cuaderno de la lluvia", "el jardín celebrará siembras, no concursos"])],
    ["¿Cómo se exhibirá el jardín?", ["Crecimiento libre con cuaderno", "Concurso anual de figuras"]],
    ["el jardín abre el cuaderno de siembras y retira las tijeras del concurso", "el pueblo acuerda cuidar las plantas sin clasificarlas"],
    ["KEEBERRY", "Aporta firmeza a un jardín que aprendió a no fingir formas que nadie plantó."]),
  R(1826, "La Ofrenda que Ganaba por Nosotros",
    "Una ofrenda del día cuida concede victorias que nadie quiere aceptar y el marcador de la guardería acumula triunfos sin dueño.",
    "Marcar con asterisco toda victoria ayudada y permitir renunciar a ella sin castigo.",
    ["Marcador honesto", ["Marcar con asterisco la ayuda desconocida.", "Permitir renunciar a una victoria registrada.", "No iniciar otro partido sin resolver el anterior."], "La sala de cuidados y la curación nunca dependen del marcador."], [
      N("Clara Marcador", "trchar009", "encargada de la guardería", "BLISSEY", "Blissey", "un marcador que nadie tenga que avergonzarse de leer", "celebró triunfos que aparecían sin explicación",
        ["Los triunfos subían y los entrenadores bajaban la mirada", "me apresuré: conté victorias que nadie había ganado", "pondré asteriscos y abriré una columna de renuncias"],
        ["el marcador distingue victoria propia y victoria asistida", "Blissey guarda las renuncias junto a las curaciones", "ningún partido nuevo empieza con un asterisco abierto"]),
      N("Basto Ofrenda", "NPC 04", "cuidador de la ofrenda", "SPIRITOMB", "Spiritomb", "que la ofrenda descanse sin comprar victorias", "dejó la ofrenda encendida toda la noche por costumbre",
        ["La ofrenda arde desde hace noches sin que nadie la apague", "tardé en reconocer que la costumbre costaba victorias ajenas", "la ofrenda tendrá horario y su apagado será solemne"],
        ["la ofrenda se enciende con permiso y se apaga con gratitud", "Spiritomb se aquieta cuando el marcador se corrige", "las renuncias se leen en voz alta, sin nombres si se pide"])],
    ["¿Qué hará la guardería con las victorias ayudadas?", ["Renunciar públicamente a ellas", "Contarlas como récord de la casa"]],
    ["la guardería vacía la columna de récords y abre un libro de renuncias", "la ofrenda se mantiene solo en fechas acordadas"],
    ["ROWAPBERRY", "Devuelve sin ruido un regalo que nadie quiso aceptar."]),
  R(1833, "El Cartucho que Ofrecía Victoria Fácil",
    "Un cartucho negro regala victorias fáciles a cambio de nada y el pueblo debate si sellarlo o convertirlo en atracción.",
    "Que todo reto del cartucho permita perder y registre sus victorias como asistidas.",
    ["Prueba con derrota posible", ["Todo reto admite derrota y retirada.", "Las victorias del cartucho se registran como asistidas.", "El sellado requiere votación pública."], "El centro Pokémon y la salida del pueblo quedan fuera del reto."], [
      N("Tuno Cartucho", "trchar008", "coleccionista de juegos", "SCRAFTY", "Scrafty", "conservar el cartucho como historia, no como máquina de trofeos", "organizó un torneo con victorias garantizadas",
        ["El torneo repartió coronas y nadie perdió ni un partido", "me precipité: prometí victorias para llenar la sala", "cada reto del cartucho tendrá retirada libre y marcador con asterisco"],
        ["el cartucho juega sin prometer triunfos y la sala sigue llena", "Scrafty guarda el cartucho cuando el público se agota", "el registro de asistidas se lee antes de cada partida"]),
      N("Eli Victoria", "NPC 04", "alcaldesa del barrio", "KROOKODILE", "Krookodile", "decidir el futuro del cartucho sin prohibir la memoria", "ordenó ocultar el cartucho para no asustar a las familias",
        ["El cartucho desapareció del estante y el rumor creció", "tardé en reconocer que esconderlo parecía miedo", "convocaré votación y explicaré los riesgos reales"],
        ["la votación quedó citada y el cartucho vuelve al estante", "Krookodile vigila la urna sin intervenir", "sea cual sea el resultado, el pueblo conocerá su historia"])],
    ["¿Qué hará el pueblo con el cartucho?", ["Sellarlo tras votación pública", "Conservarlo como atracción regulada"]],
    ["el pueblo fija la votación y sus condiciones por escrito", "el centro Pokémon ofrece marcadores honestos para el torneo"],
    ["EJECTPACK", "Abandona con dignidad una partida que nunca quiso jugarse de verdad."]),
  R(1840, "La Curación que Cobraba una Victoria",
    "Un programa de curación de la costa cobra victorias futuras como deuda y los entrenadores combaten enfermos para saldarla.",
    "Que ninguna curación dependa de una victoria y que la deuda deje de ser pelea.",
    ["Deuda sin pelea", ["La curación nunca exige combates.", "Las donaciones son voluntarias y públicas.", "El libro de cuentas se muestra a quien lo pide."], "La enfermería de emergencia cura antes de preguntar nada."], [
      N("Lina Deuda", "trchar009", "coordinadora del programa", "WIGGLYTUFF", "Wigglytuff", "curar sin atar la recuperación a un resultado", "firmó contratos de victorias futuras para financiar la enfermería",
        ["Los contratos de curación acumulan victorias sin dueño feliz", "me apresuré: financié la enfermería con triunfos ajenos", "separaré donación, curación y cualquier gratitud"],
        ["la enfermería cura y el libro de donaciones queda abierto", "Wigglytuff cobra sonriendo cero victorias", "los contratos viejos se archivarán como lección"]),
      N("Roque Historial", "NPC 04", "entrenador endeudado", "LUVDISC", "Luvdisc", "combatir sano sin pelear por una deuda", "ocultó una lesión para cumplir su cuota de victorias",
        ["Mi equipo jugaba enfermo para no deber más partidas", "tardé en reconocer que la deuda me quitó el criterio", "renunciaré a la cuota y pediré curación sin promesas"],
        ["la renuncia quedó firmada y mi equipo volvió al agua", "Luvdisc nada sin reloj ni cuota detrás", "contaré mi caso a quien firme el próximo contrato"])],
    ["¿Cómo se financiará la enfermería?", ["Donaciones voluntarias públicas", "Contratos de victorias futuras"]],
    ["la enfermería abre su libro de donaciones y quita los contratos", "el pueblo acuerda que ninguna curación se cobra en victorias"],
    ["SITRUSBERRY", "Restaura poco a poco, sin pedir a nadie una victoria a cambio."]),
  R(1851, "La Excavación que Ensamblaba un Monstruo",
    "Una excavación mezcló huesos de especies distintas para montar un monstruo de museo y los visitantes creen que la criatura existió.",
    "Etiquetar procedencia de cada fragmento y exhibir los montajes como réplicas, nunca como hallazgos.",
    ["Cartela de procedencia", ["Etiquetar origen antes de montar.", "Exhibir mezclas como réplicas declaradas.", "Ningún entierro escenificado se presenta como real."], "La sala de familias y la salida no participan de la exhibición."], [
      N("Yelmo Osario", "trchar008", "director de excavación", "MAROWAK", "Marowak", "reconstruir ambientes sin fabricar criaturas", "unió cuernos de tres sitios y presentó la pieza como especie nueva",
        ["El cartel del museo presenta una especie que nunca existió", "me precipité: ensamblé tres sitios en un solo esqueleto", "desmontaré la pieza y etiquetaré cada fragmento"],
        ["las vitrinas distinguen fósil, réplica y conjetura", "Marowak toca cada etiqueta antes de que se cierre la vitrina", "el montaje volverá a exhibirse solo como advertencia"]),
      N("Pía Estrato", "NPC 04", "geóloga de campo", "YAMASK", "Yamask", "explicar la tierra sin escenificar entierros", "autorizó una recreación de entierro para atraer público",
        ["La recreación del entierro llenó el calendario de visitas", "tardé en reconocer que había puesto duelo ajeno en escena", "la recreación se retirará y la tierra explicará sola"],
        ["la sala vuelve a la estratigrafía y el público aprende igual", "Yamask acompaña las visitas sin escenificar nada", "las familias podrán preguntar sin guiñarle el ojo al cartel"])],
    ["¿Cómo se mostrará la excavación?", ["Piezas con cartela de procedencia", "Montajes espectaculares de época"]],
    ["el museo aprueba el reglamento de cartelas y retira el entierro escenificado", "la excavación publica su diario con los errores incluidos"],
    ["DUBIOUSDISC", "Guarda la duda sobre un hallazgo fabricado hasta que su procedencia quede clara."]),
  R(1858, "El Retrato del Esqueleto Inexistente",
    "Un museo exhibe retratos de un esqueleto que nunca se encontró y las guías infantiles convierten la conjetura en monstruo de cuento.",
    "Separar ilustración e hallazgo real y devolver los cuentos al horario de historias, no a la sala de fósiles.",
    ["Retrato con fuente", ["Ilustrar solo hallazgos reales en la sala de fósiles.", "Marcar la ficción con el sello de hora de cuentos.", "Publicar guías infantiles separadas del material científico."], "El patio infantil y la salida quedan fuera del recorrido de terror."], [
      N("Lupa Cartela", "trchar009", "ilustradora científica", "PUMPKABOO", "Pumpkaboo", "dibujar lo encontrado sin convertir la duda en bestia", "rellenó vacíos del esqueleto con rasgos de criaturas inventadas",
        ["La sala muestra mandíbulas que ningún hallazgo respalda", "me apresuré: dibujé conjeturas con luz de monstruo", "devolveré la mandíbula al cuaderno y marcaré la duda"],
        ["la ilustración enseña huesos reales y preguntas abiertas", "Pumpkaboo ilumina los huecos sin rellenarlos", "la conjetura vivirá en papel aparte, con su sello"]),
      N("Ren Pincel", "NPC 04", "guía de familias", "HOUNDOOM", "Houndoom", "contar historias sin asustar a quien viene a aprender", "leyó la leyenda del esqueleto con efectos de sonido",
        ["Los cuentos con truenos terminaban en llanto y en visitas cortas", "tardé en reconocer que el susto no explicaba nada", "separaré hora de cuentos y hora de fósiles"],
        ["las familias eligen el recorrido y nadie sale asustado por error", "Houndoom se queda en silencio durante la hora de cuentos", "las guías infantiles tendrán su propio mapa"])],
    ["¿Dónde vivirán los retratos del esqueleto?", ["Sala de fósiles solo con fuentes", "Exhibición mixta de hallazgo y leyenda"]],
    ["el museo separa las salas y sella la ficción con su sello", "las guías infantiles se reimprimen con el mapa nuevo"],
    ["MICLEBERRY", "Aporta exactitud a una descripción que se había atrevido a imaginar demasiado."]),
  R(1865, "La Piedra que Simulaba un Entierro",
    "Una instalación de cristal recrea un rito funerario para turistas y las familias del pueblo piden que deje de ser espectáculo.",
    "Que los ritos vuelvan a ser privados y el cristal se venda como decoración, no como reliquia.",
    ["Ritual sin público", ["Los ritos se realizan sin cámara ni entrada.", "El cristal se vende como decoración declarada.", "Toda ceremonia requiere permiso de la familia."], "La plaza y el regreso permanecen abiertos durante cualquier ceremonia."], [
      N("Crista Ritual", "trchar008", "artista de instalaciones", "WHIMSICOTT", "Whimsicott", "crear belleza sin alquilar el duelo de nadie", "vendió entradas para una ceremonia que no era suya",
        ["La ceremonia de cristal tenía butacas numeradas", "me precipité: convertí un rito en función de tarde", "la instalación volverá al arte y el rito a su familia"],
        ["la obra brilla sin público sentado y las ceremonias son privadas", "Whimsicott apaga los cristales cuando llega la familia", "las entradas se sustituyen por visitas de día"]),
      N("Maura Lápida", "NPC 04", "portavoz de las familias", "PURUGLY", "Purugly", "proteger la intimidad sin prohibir el arte", "organizó un boicot que ahuyentó a todo el pueblo",
        ["Mi boicot vació la plaza y endureció a los artistas", "tardé en reconocer que cerrar la puerta no abrió diálogo", "pediré permiso, horario y una condición por escrito"],
        ["familias y artista firmaron el acuerdo de ceremonias", "Purugly se sienta en la puerta sin impedir el paso", "el arte del cristal tendrá su temporada sin rito"])],
    ["¿Qué se venderá en la tienda de la instalación?", ["Cristal decorativo declarado", "Réplicas de reliquia del rito"]],
    ["la tienda retira las reliquias y expone el cristal como decoración", "las familias guardan un ejemplar del acuerdo firmado"],
    ["ENIGMABERRY", "Absorbe la curiosidad que lastima cuando se exhibe como producto."]),
  R(1876, "El Reporte que Cruzaba la Nieve",
    "Un equipo aislado sigue enviando reportes desde la nieve y los rescatistas discuten quién debe partir primero.",
    "Ordenar el rescate por necesidad real y no por fama, repitiendo posición y suministros en cada reporte.",
    ["Cadena de reporte", ["Cada reporte repite posición y suministros.", "El relevo confirma recepción con acuse.", "El orden de rescate se fija por necesidad, no por nombre."], "La cueva mantiene un refugio cálido sin depender de la cola de rescate."], [
      N("Neve Reporte", "trchar009", "radiooperadora de montaña", "ABOMASNOW", "Abomasnow", "mantener la cadena de reportes viva sin gritar", "transmitió sin pedir acuse y dio la señal por recibida",
        ["Los reportes salen y nadie confirma si llegan", "me apresuré: di por enviado cada parte sin esperar acuse", "pediré confirmación y repetiré posición y suministros"],
        ["cada transmisión cierra con acuse y número de parte", "Abomasnow marca la ruta del relevo sobre la nieve", "el cuaderno de suministros viajará con el primer rescate"]),
      N("Tor Rescate", "NPC 04", "jefe de relevo", "AVALUGG", "Avalugg", "rescatar por orden de necesidad aunque la prensa pida nombres", "adelantó a un equipo famoso dejando atrás un caso urgente",
        ["El equipo famoso llegó primero y el urgente esperó dos días", "tardé en reconocer que la fama pesó más que el parte médico", "el orden saldrá de los partes, no de las cámaras"],
        ["la cola de rescate obedece a la necesidad declarada", "Avalugg abre la pista sin preguntar quién es quién", "la prensa recibirá los partes con retraso deliberado"])],
    ["¿Cómo se ordenará la cola de rescate?", ["Por necesidad médica declarada", "Por antigüedad del reporte"]],
    ["el relevo publica su criterio de orden en la entrada", "la cueva abre su refugio cálido a todo orden de la cola"],
    ["NEVERMELTICE", "Conserva un reporte helado hasta que alguien por fin lo encuentre."]),
  R(1883, "El Equipo que No Pedía Rescate",
    "El equipo aislado rechaza el rescate por orgullo y los guías insisten con cámaras encendidas.",
    "Ofrecer ayuda sin presión: suministros primero, puertas de salida documentadas, cámaras apagadas.",
    ["Permiso de ayuda", ["Ofrecer sin presionar.", "Enviar suministros antes que entrevistas.", "Documentar rutas de salida sin exigir declaración."], "La ruta de retirada del equipo permanece marcada y expedita."], [
      N("Nida Ayuda", "trchar008", "guía de relevo", "PILOSWINE", "Piloswine", "ayudar sin arrancar una declaración", "llegó con el micrófono puesto y la ayuda en la mochila cerrada",
        ["Mi primera oferta sonó a noticia y la puerta se cerró", "me precipité: enseñé la cámara antes que los suministros", "dejaré el equipo a la puerta y preguntaré desde lejos"],
        ["los suministros entraron y las cámaras siguen guardadas", "Piloswine carga sin exigir nombre para el parte", "el equipo decidirá cuándo se habla y cuándo no"]),
      N("Risco Orgullo", "NPC 04", "capitán del equipo aislado", "URSARING", "Ursaring", "mantener a su equipo unido sin convertirlo en fortaleza", "rechazó ayuda tres veces para no parecer débil",
        ["Mi equipo comía raciones cortas mientras yo firmaba orgullo", "tardé en reconocer que confundí coherencia con testarudez", "aceptaré suministros y reservaré la retirada para cuando toque"],
        ["el equipo acepta suministros y conserva su ruta de salida", "Ursaring camina junto al relevo sin escolta obligatoria", "cuando hablemos, será con las manos vacías y sin micrófonos"])],
    ["¿Cómo ofrecerá el relevo su ayuda?", ["Suministros primero y sin cámaras", "Operación con cobertura mediática"]],
    ["el relevo adopta el protocolo de suministros primero", "el equipo aislado recibe un mapa de retirada actualizado"],
    ["SALACBERRY", "Da impulso a una ayuda que se ofreció sin esperar a la bandera correcta."]),
  R(1890, "La Pintura que Esperaba a los Ausentes",
    "Un mural inacabado espera el regreso de un equipo y la galería quiere terminarlo con sustitutos para la inauguración.",
    "Que el mural conserve su parte sin terminar y toda homenaje sustituto se muestre como obra aparte.",
    ["Obra abierta", ["Lo inacabado se inaugura sin completar.", "Los homenajes sustitutos se exponen como obras propias.", "Los artistas ausentes conservan el pincel de su sección."], "La salida de la galería y la cafetería quedan fuera del recorrido del mural."], [
      N("Sora Pincel", "trchar009", "coordinadora de la galería", "SPRITZEE", "Spritzee", "inaugurar sin cerrar una historia ajena", "encargó a otros pintores terminar la sección del equipo ausente",
        ["Los sustitutos pintaron una sección que no les pertenecía", "me precipité: quise una inauguración completa y toqué lo ajeno", "colgaré los homenajes al lado, con nombre propio"],
        ["el mural luce su hueco y los homenajes cuelgan firmados", "Spritzee vuela por el borde sin rozar la pintura", "la sección del equipo guarda sus pinceles hasta su regreso"]),
      N("Tilo Ausente", "NPC 04", "familiar del equipo", "DEDENNE", "Dedenne", "que el mural espere sin convertirse en rehén", "presionó para cerrar el mural antes de tiempo por hastío",
        ["Yo mismo quise pintar encima y acabar de una vez", "tardé en reconocer que el cansancio me hacía traicionar la espera", "el mural espera y nosotros esperamos con él"],
        ["la inauguración aceptó el hueco y el público entendió", "Dedenne se posa en el marco cada tarde de visita", "cuando vuelvan, elegirán ellos el pincel"])],
    ["¿Qué verá el público en la inauguración?", ["Mural inacabado con sus huecos", "Versión completada por sustitutos"]],
    ["la galería inaugura el mural tal cual y abre el libro de visitas", "los homenajes se exponen en la sala contigua con sus firmas"],
    ["SILVERPOWDER", "Añade brillo a lo terminado sin rellenar lo que todavía espera."]),
  R(1901, "El Dato que Intentaba Clasificar al Jugador",
    "Datos corruptos de la cueva intentan clasificar al jugador en categorías fijas y las etiquetas se pegan a los entrenadores.",
    "Convertir toda etiqueta en consejo reversible y poner en cuarentena las filas corruptas sin borrarlas.",
    ["Etiqueta reversible", ["Las categorías son consejos, nunca sentencias.", "El jugador puede cambiar su etiqueta cuando quiera.", "Las filas corruptas se aíslan sin eliminarse."], "El faro de la trinchera mantiene su señal y el retorno intactos ante cualquier error de datos."], [
      N("Bit Etiqueta", "trchar008", "tecnófarera de datos", "PORYGONZ", "Porygon-Z", "clasificar sin encasillar a nadie", "convirtió una etiqueta provisional en registro permanente",
        ["La cueva clasifica y el registro no se borra nunca", "me apresuré: guardé etiquetas provisionales como si fueran diagnóstico", "pondré fecha de caducidad y botón de cambio"],
        ["las etiquetas caducan y el jugador corrige su fila", "Porygon-Z copia la fila nueva sin arrastrar la corrupta", "la cuarentena conserva los datos originales bajo llave"]),
      N("Zeta Cuarentena", "NPC 04", "conservadora de archivos", "ELECTRODE", "Electrode", "preservar los datos rotos hasta entenderlos", "ordenó purgar la carpeta corrupta con un clic",
        ["La carpeta corrupta se borró dos veces esta temporada", "tardé en reconocer que purgar no es reparar", "aíslo, copio y espero a que alguien entienda"],
        ["la cuarentena guarda copias fechadas de cada fila rota", "Electrode rueda lento para no tirar los cajones", "las purgas exigirán acta y dos lectores"])],
    ["¿Qué hará la cueva con las filas corruptas?", ["Cuarentena con copias fechadas", "Purga inmediata del archivo"]],
    ["la cueva abre la sala de cuarentena y publica su reglamento", "los entrenadores reciben sus etiquetas con botón de cambio"],
    ["METALCOAT", "Recubre un dato frágil sin ocultar del todo sus bordes dañados."]),
  R(1908, "La Luz que Purgaba Archivos Rotos",
    "Un haz de luz de la isla elimina por completo los archivos corruptos y los conservadores reclaman copias antes de reparar.",
    "Que la luz aísle en vez de borrar y que toda reparación empiece por una copia de respaldo.",
    ["Cámara de cuarentena", ["La luz aísla; nunca borra sin revisión.", "Toda reparación parte de una copia.", "Las reparaciones se anuncian con su fecha."], "La senda del bosque y el retorno siguen iluminados aunque el archivo esté en cuarentena."], [
      N("Fax Purga", "trchar009", "farera de archivos", "JOLTEON", "Jolteon", "dirigir la luz sin destruir la historia", "ordenó encender el haz a máxima potencia sobre la carpeta completa",
        ["La carpeta entera se apagó con la luz al máximo", "me precipité: quise limpiar rápido y borré contexto", "bajaré el haz y separaré brillo de destrucción"],
        ["la luz solo aísla y la carpeta vuelve con su contexto", "Jolteon marca el umbral con una descarga corta", "cada reparación se anuncia antes y después"]),
      N("Mora Archivo", "NPC 04", "archivera de respaldos", "GALVANTULA", "Galvantula", "tejer respaldos que nadie tenga que recordar pedir", "confió en la luz y dejó de hacer copias semanales",
        ["Mis respaldos se adelgazaron mientras la luz brillaba", "tardé en reconocer que la confianza no es un plan", "tejeré copias nuevas aunque la luz prometa limpieza"],
        ["la red de respaldos sostiene cada carpeta con dos copias", "Galvantula revisa los hilos cuando cambia el viento", "el calendario de copias cuelga junto al del haz"])],
    ["¿Cómo actuará el haz de luz?", ["Aislar y notificar antes de reparar", "Borrar todo archivo marcado como roto"]],
    ["el bosque fija el protocolo de aislamiento y sus avisos", "los respaldos semanales vuelven a ser obligatorios"],
    ["PRISMSCALE", "Devuelve color a un archivo que la luz había vuelto plano del todo."]),
  R(1915, "La Torre de Datos con Dos Versiones",
    "Una torre guarda dos versiones de la misma ruta y los fallos intercambian sus etiquetas hasta confundir a los viajeros.",
    "Conservar ambas versiones con fecha y registrar cada intercambio de etiqueta.",
    ["Doble versión con fecha", ["Ambas versiones se conservan.", "Las etiquetas se sellan con resumen fijo.", "Todo intercambio queda registrado con hora."], "La torre mantiene su señal de retorno visible desde cualquiera de las dos versiones."], [
      N("Nix Versión", "trchar008", "administradora de la torre", "MORPEKO", "Morpeko", "sostener dos historias sin convertirlas en trampa", "dejó las etiquetas colgadas de un gancho común",
        ["Las etiquetas cuelgan juntas y el viajero elige a ciegas", "me apresuré: ahorré anclajes y mezclé los destinos", "fijaré cada etiqueta a su versión y sellaré el resumen"],
        ["las etiquetas quedan ancladas y el registro anota los cruces", "Morpeko no cambia de gancho sin firmar el registro", "las dos versiones tendrán su propia entrada"]),
      N("Raya Cambio", "NPC 04", "técnico de intercambios", "BOLTUND", "Boltund", "reparar etiquetas sin esconder los errores", "recolocó etiquetas de noche y no anotó nada",
        ["Mi recolocación nocturna explicó el caos de la mañana", "tardé en reconocer que el silencio multiplicaba el daño", "cada cambio llevará hora, firma y motivo"],
        ["el registro delata mis manos y por fin ayuda", "Boltund trae el sello antes de que se mueva nada", "los viajeros leerán el registro junto al mapa"])],
    ["¿Qué hará la torre con sus dos versiones?", ["Dos entradas fechadas y firmadas", "Una versión principal y la otra oculta"]],
    ["la torre abre doble entrada y publica el registro de cambios", "los viajeros reciben el mapa con sus dos lecturas"],
    ["ELECTIRIZER", "Da impulso a la revisión cada vez que las etiquetas vuelven a intercambiarse."]),
  R(1926, "El Acertijo que Fingía Profundidad",
    "Un acertijo imposible de la provincia escondía sus respuestas para parecer profundo y el club de acertijos quiere reglas justas.",
    "Que todo acertijo salga con su pista de resolución y su hoja de respuestas a la vista del organizador.",
    ["Acertijo con pista", ["Todo acertijo declara su pista de resolución.", "Ningún acertijo se publica sin hoja de respuestas.", "La dificultad se anuncia antes de participar."], "El camino de la provincia y el regreso permanecen fuera del acertijo."], [
      N("Rima Acertijo", "trchar009", "maestra de acertijos", "NATU", "Natu", "diseñar enigmas difíciles pero honestos", "ocultó las pistas para que el acertijo pareciera imposible",
        ["El acertijo era famoso por irresoluble y era solo escondido", "me precipité: quise admiración y saqué las pistas del juego", "diseñaré dificultad con camino de salida"],
        ["el acertijo conserva su misterio y enseña su pista", "Natu señala el primer paso sin decir la respuesta", "cada enigma nuevo saldrá con hoja de respuestas firmada"]),
      N("Vero Pista", "NPC 04", "jugadora del club", "MUNNA", "Munna", "aprender sin sentirse burlada por un truco", "se sintió tonta cuando descubrió las respuestas escondidas",
        ["Creí no servir para los enigmas hasta ver el truco", "tardé en reconocer que la burla era diseño, no dificultad", "pediré pistas sin avergonzarme y avisaré a otros"],
        ["el club publica las pistas y las dudas dejan de ser secreto", "Munna acompaña a quien se atasca sin resolver por él", "las hojas de respuestas se archivan a la vista"])],
    ["¿Cómo se publicarán los acertijos?", ["Con pista y hoja de respuestas", "Como pruebas cerradas sin revelar nada"]],
    ["el club redacta su reglamento de enigmas justos", "la provincia recibe el primer acertijo con pista visible"],
    ["STARFBERRY", "Premia a quien desmonta un acertijo sin necesidad de público."]),
  R(1933, "La Prueba que Ocultaba sus Reglas",
    "Una prueba de acceso esconde sus reglas para parecer élite y los candidatos suspenden por sorpresas de última hora.",
    "Publicar las reglas antes de entrar, con ejemplo resuelto y política de repitición.",
    ["Reglas primero", ["Las reglas se publican antes de la inscripción.", "Cada prueba incluye un ejemplo resuelto.", "La política de repitición se explica en la puerta."], "La zona de espera y la salida del complejo quedan fuera del examen."], [
      N("Nao Reglas", "trchar008", "directora de exámenes", "SLOWKING", "Slowking", "elegir estudiantes sin fabricar fracasos evitables", "cambió el baremo al segundo día de pruebas",
        ["El baremo cambió dos veces durante la misma convocatoria", "me precipité: ajusté las reglas en caliente y rompí la igualdad", "congelaré el baremo antes de abrir la inscripción"],
        ["las reglas están firmadas y la convocatoria avanza sin cambios", "Slowking lee el reglamento en voz alta el primer día", "el ejemplo resuelto se reparte con la inscripción"]),
      N("Llano Muestra", "NPC 04", "candidato repetidor", "KADABRA", "Kadabra", "acceder a una prueba cuyas reglas conoce de antemano", "intentó colarse en el examen para copiar las reglas ocultas",
        ["Esperaba la lista de reglas como quien espera un fallo ajeno", "tardé en reconocer que el secreto me volvió tramposo", "estudiaré del ejemplo resuelto y repetiré con calma"],
        ["la convocatoria publicó su reglamento y mi repetición es legal", "Kadabra aparta los apuntes que nadie pidió copiar", "cada candidato podrá leer las reglas en la puerta"])],
    ["¿Qué verá el candidato antes de inscribirse?", ["Reglamento completo con ejemplo", "Solo las fechas y el temario"]],
    ["el complejo publica el reglamento y congela el baremo", "la zona de espera enseña el ejemplo resuelto a todo el mundo"],
    ["APICOTBERRY", "Eleva la resistencia de quien enfrenta reglas que llegaron tarde."]),
];

const specs07 = [
  R(1940, "El Eco que Contestaba Antes de la Pregunta",
    "Un oráculo del pueblo responde antes de que nadie pregunte y las respuestas parecen sabiduría cuando son solo truco.",
    "Que las respuestas se emitan después de preguntar y que el oráculo pueda decir que no lo sabe.",
    ["Pregunta primero", ["Toda respuesta sigue a una pregunta registrada.", "El oráculo puede responder no sé.", "El silencio se acepta como resultado."], "El sendero del pueblo y el regreso permanecen abiertos aunque el oráculo calle."], [
      N("Sía Oráculo", "trchar009", "guardiana del oráculo", "TSAREENA", "Tsareena", "devolver al oráculo su papel de interlocutor", "programó las respuestas en guion fijo de feria",
        ["Las respuestas salen recitadas, en el mismo orden de siempre", "me apresuré: escribí un guion y lo llamé sabiduría", "esperaré la pregunta y permitiré que el oráculo dude"],
        ["el oráculo escucha primero y calla cuando no sabe", "Tsareena anota cada pregunta sin sugerir respuestas", "las respuestas grabadas se archivan como teatro"]),
      N("Kibo Respuesta", "NPC 04", "aldeano creyente", "LURANTIS", "Lurantis", "volver a preguntar sin sentirse tonto", "acató las respuestas del guion como órdenes del destino",
        ["Yo ordenaba la cosecha cuando el oráculo ya había hablado", "tardé en reconocer que obedecía un guion de feria", "preguntaré en voz alta y aceptaré el no sé"],
        ["el pueblo pregunta de nuevo y las cosechas se deciden entre todos", "Lurantis abre las hojas cuando la pregunta llega completa", "el oráculo vuelve a ser una conversación"])],
    ["¿Cómo funcionará el oráculo?", ["Conversación con no sé permitido", "Consultas rápidas de guion"]],
    ["el pueblo cambia el oráculo por una conversación y archiva el guion", "las decisiones de cosecha vuelven a la asamblea"],
    ["CUSTAPBERRY", "Actúa solo cuando la pregunta ya está dicha del todo."]),
  R(1951, "El Recuerdo que Enseñaba Venganza",
    "Un recuerdo implantado convenció a una dependienta de que fue traicionada y su rencor ajeno pesa sobre todo el centro comercial.",
    "Etiquetar los sentimientos implantados y abrir el registro de origen sin exigir perdón a nadie.",
    ["Memoria con fuente", ["Los sentimientos implantados se etiquetan como tales.", "El registro de origen queda abierto a la interesada.", "Nadie debe perdonar para cerrar el expediente."], "Las salidas del centro comercial y la enfermería permanecen neutrales."], [
      N("Amira Recuerdo", "trchar008", "dependienta del centro", "WOBBUFFET", "Wobbuffet", "reconocer qué parte de su rencor es suya", "dejó notas de acusación en los escaparates de sus compañeras",
        ["Las notas de acusación aparecieron en tres escaparates", "me precipité: sentí la traición y la escribí como verdad", "leeré el registro de origen antes de escribir otra nota"],
        ["las notas se retiraron y el expediente se abrió sin exigir perdón", "Wobbuffet devuelve las cartas sin comentarlas", "mi rencor tendrá nombre, fecha y terapeuta"]),
      N("Simón Olvido", "NPC 04", "técnico de memoria", "SNORLAX", "Snorlax", "diseñar borrados que no dejen rencores prestados", "instaló recuerdos de relleno sin registrar su origen",
        ["Mis instalaciones de recuerdos salieron del taller sin etiqueta", "tardé en reconocer que un relleno puede volverse herida", "etiquetaré cada instalación y guardaré su receta"],
        ["las instalaciones nuevas salen con etiqueta y receta", "Snorlax vigila el registro sin leer los sentimientos", "los borrados pedirán consentimiento por escrito"])],
    ["¿Cómo se tratará el recuerdo implantado?", ["Etiquetado abierto y sin exigir perdón", "Borrado inmediato del recuerdo"]],
    ["el centro comercial aprueba la etiqueta de origen y abre el registro", "la sala de memoria publica su reglamento de consentimiento"],
    ["JABOCABERRY", "Deja que un rencor prestado se disuelva sin herir a quien lo cargó."]),
  R(1958, "La Deuda que Heredó un Hijo",
    "Una deuda de venganza pasó de padres a hijos y el joven rehabilitado de la reserva carga con un rencor que nunca firmó.",
    "Que ninguna deuda de odio se herede y que la rehabilitación del joven se proteja por escrito.",
    ["Deuda personalísima", ["Las deudas de rencor no se heredan.", "Las disculpas se registran, no se escenifican.", "La cuenta del joven queda sellada hasta su mayoría."], "La salida de la reserva y la atención del centro Pokémon son siempre incondicionales."], [
      N("Cris Herencia", "trchar009", "mediadora de la reserva", "FURFROU", "Furfrou", "cortar la cadena de rencor sin romper las familias", "presentó la deuda del padre como asunto del hijo",
        ["La mesa de mediación citó al hijo por la deuda del padre", "me precipité: escribí una herencia donde solo había una historia", "cerraré la cuenta del padre y sellaré la del joven"],
        ["las dos cuentas viven separadas y la familia respira", "Furfrou camina entre las mesas sin elegir ninguna", "el expediente del joven se abrirá cuando él decida"]),
      N("Nilo Rehabilitado", "NPC 04", "joven en rehabilitación", "MIGHTYENA", "Mightyena", "empezar su propia historia sin el apellido del rencor", "cargó con la deuda para parecer leal a su familia",
        ["Yo firmaba los pliegos de una guerra que no empecé", "tardé en reconocer que la lealtad me pedía ser rehén", "devolveré los pliegos y firmaré solo mis decisiones"],
        ["los pliegos vuelven a sus autores y mi expediente se sella", "Mightyena me acompaña sin portar ninguna bandera", "cuando hable con mi familia, será sobre el presente"])],
    ["¿Qué hará la reserva con la deuda de rencor?", ["Declararla personalísima e intransferible", "Renegociarla como asunto familiar"]],
    ["la reserva sella el registro de herencias de rencor", "el centro Pokémon acompaña al joven en su expediente propio"],
    ["GANLONBERRY", "Refuerza la defensa de quien rechazó heredar un rencor que no le pertenecía."]),
  R(1965, "La Carta que Volvió Culpable al Mensajero",
    "Una carta falsa culpó al mensajero de un mensaje que nunca escribió y su memoria ahora carga con la letra ajena.",
    "Huellas de tinta por carta, cuarentena de falsificaciones y ninguna culpa sin prueba de trazo.",
    ["Rastro de tinta", ["Cada carta conserva su rastro de tinta.", "Las falsificaciones se aíslan sin destruirse.", "Sin trazo no hay culpa."], "La oficina de reparto mantiene su servicio y el regreso a la ruta sin interrupciones."], [
      N("Basco Mensajero", "trchar008", "cartero de la ruta", "CROBAT", "Crobat", "entregar cartas sin convertirse en sospechoso", "aceptó la culpa para cerrar rápido el asunto",
        ["La firma del pliego no es la mía y aun así la reconocí", "me precipité: firmé una culpa que mi tinta nunca escribió", "compararé trazos y devolveré el pliego al expediente"],
        ["el trazo ajeno quedó aislado y mi nombre se limpió", "Crobat vuela la ruta sin cargar pliegos ajenos", "cada entrega nueva se sella con tinta de la oficina"]),
      N("Ángela Tinta", "NPC 04", "grafóloga de la oficina", "MASQUERAIN", "Masquerain", "analizar trazos sin fabricar culpables", "escribió un informe que imitaba la letra del cartero",
        ["Mi informe parecía más una condena que un análisis", "tardé en reconocer que imité su letra para ser convincente", "separaré observación, conjetura y veredicto"],
        ["el informe se reescribió en tres capas legibles", "Masquerain vuela sobre el papel sin gotear", "las falsificaciones esperan en cuarentena sin dueño"])],
    ["¿Cómo se resolverán las acusaciones postales?", ["Con rastro de tinta y cuarentena", "Con la confesión del cartero"]],
    ["la oficina abre su laboratorio de trazos y publica el reglamento", "la ruta recibe sellos nuevos de tinta verificable"],
    ["BRIGHTPOWDER", "Difumina una acusación hasta que exista una prueba con trazo propio."]),
  R(1976, "El Guardado que Era una Persona",
    "Un archivo de recuerdos se ofrece como partida guardable y la custodia de las personas archivadas no tiene dueño claro.",
    "Custodia con doble llave, copias con caducidad y derecho a cerrar el archivo propio.",
    ["Custodia con llave doble", ["Cada archivo necesita su llave y una llave de custodia.", "Las copias caducan por fecha.", "La persona puede cerrar su archivo cuando quiera."], "La salida del distrito y la asistencia del centro Pokémon no dependen del archivo."], [
      N("Alma Guardada", "trchar009", "archivera del distrito", "COFAGRIGUS", "Cofagrigus", "custodiar personas sin poseerlas", "presentó el archivo de una persona como partida exportable",
        ["El catálogo ofrece mi archivo como si fuera un perfil", "me precipité: convertí la custodia en posesión", "devolveré las llaves y redactaré el consentimiento"],
        ["las dobles llaves se firmaron y las copias tienen fecha", "Cofagrigus cierra el cajón sin mirar el contenido", "cada persona podrá cerrar su archivo sin dar motivos"]),
      N("Rubén Llave", "NPC 04", "familiar custodio", "SPIRITOMB", "Spiritomb", "guardar recuerdos ajenos sin apropiarse de ellos", "hizo copias de seguridad sin avisar a la persona archivada",
        ["Mis copias de seguridad viajaban en mi propia mochila", "tardé en reconocer que una copia sin avisar también es una toma", "pediré permiso y destruiré las copias viejas"],
        ["las copias viejas se devolvieron y las nuevas caducan", "Spiritomb desaparece cuando se firman los permisos", "el registro de llaves quedará a la vista del distrito"])],
    ["¿Quién tendrá la segunda llave del archivo?", ["Un custodio rotatorio del distrito", "La propia familia de la persona"]],
    ["el distrito elige su custodio rotatorio y publica el acta", "el archivo abre su registro de consentimientos y caducidades"],
    ["DEEPSEASCALE", "Protege la intimidad de quien prefirió no abrirse del todo."]),
  R(1983, "El Cofre de Recuerdos en Escena",
    "Un concurso escénico presta recuerdos ajenos como utilería y los jurados premian habilidades que los participantes no desarrollaron.",
    "Préstamos con devolución, originales sellados y un jurado que juzgue técnica propia.",
    ["Préstamo con devolución", ["Todo préstamo de recuerdo se devuelve al terminar.", "Los originales permanecen sellados durante la actuación.", "El jurado puntúa técnica, no recuerdos prestados."], "La sala de descanso y la salida quedan fuera del concurso."], [
      N("Fina Escena", "trchar008", "directora del concurso", "CLEFAIRY", "Clefable", "que el escenario premie a quien actúa, no a quien alquila", "autorizó utilería de recuerdos sin contrato de devolución",
        ["Las utilerías de recuerdo llenaban el escenario sin contrato", "me precipité: quise un espectáculo brillante y presté vidas ajenas", "haré contrato de préstamo y sellaré los originales"],
        ["los contratos de préstamo cierran con devolución firmada", "Clefable devuelve cada recuerdo antes del aplauso", "el jurado recibirá una parrilla de técnica propia"]),
      N("Lino Préstamo", "NPC 04", "participante", "AUDINO", "Audino", "actuar con lo suyo aunque brille menos", "alquiló los recuerdos de su abuela para la final",
        ["La final de mi abuela brillaba más que mi propia voz", "tardé en reconocer que alquilé mi historia", "actuaré con mi técnica y devolveré el recuerdo antes del jurado"],
        ["mi actuación salió sin utilería ajena y el público aplaudió igual", "Audino sostiene el contrato de devolución", "el concurso publicará su reglamento de préstamos"])],
    ["¿Qué premiará el jurado?", ["Técnica propia del participante", "Impacto escénico, venga de donde venga"]],
    ["el concurso publica la parrilla de técnica y retira los préstamos sin contrato", "los originales vuelven a sus dueños con acta de devolución"],
    ["OVALSTONE", "Devuelve redondo y sin grietas cada recuerdo que volvió a su dueño."]),
  R(1990, "El Archivo que Guardaba el Fin de la Historia",
    "Un archivo de la ruta colecciona finales de historias y corre el riesgo de coronar uno solo como canon.",
    "Catálogo sin jerarquía: los finales se archivan sin clasificar y los autores pueden seguir escribiendo.",
    ["Final sin canon", ["Los finales se catalogan sin ranking.", "Los autores pueden añadir sin borrar.", "El lector elige su propio punto de entrada."], "La sala de lectura y el regreso permanecen abiertos a toda hora."], [
      N("Nadia Final", "trchar009", "archivera de finales", "PERSIAN", "Persian", "guardar finales sin coronar a ninguno", "clasificó los finales por calidad y escondió los modestos",
        ["El catálogo ordena los finales como si fueran podios", "me precipité: apliqué una escala donde solo cabía memoria", "quitaré los podios y dejaré las fechas y las firmas"],
        ["los finales cuelgan en orden de llegada, sin medallas", "Persian se sienta sobre el cajón de los modestos", "el catálogo anunciará que ningún final está completo"]),
      N("Gabo Apertura", "NPC 04", "lector empedernido", "XATU", "Xatu", "leer sin exigir un final oficial", "presionó al archivo para que publicara un final único",
        ["Yo pedí a gritos un final oficial y cerrado", "tardé en reconocer que mi impaciencia empujaba al podio", "elegiré mi entrada y dejaré escribir a los demás"],
        ["el archivo recuperó sus entradas múltiples y yo mi curiosidad", "Xatu señala puertas de lectura sin abrir ninguna", "los autores recibieron la invitación a continuar"])],
    ["¿Qué publicará el archivo?", ["Catálogo de finales sin ranking", "Edición oficial de un final único"]],
    ["el archivo retira los podios y publica la invitación a continuar", "los lectores reciben un mapa de entradas posibles"],
    ["PETAYABERRY", "Impulsa a quien se atreve a escribir otro final sin borrar el anterior."]),
  R(2001, "La Mesa de los Cuarenta Testigos",
    "Cuarenta historias compiten por decidir qué final merece Atlas y la asamblea del centro teme que una sola ocupe el atril.",
    "Turno coral: cada historia habla una vez, el acta queda abierta y ninguna decisión es para siempre.",
    ["Turno coral", ["Cada historia habla una sola vez por ronda.", "El acta queda abierta a correcciones.", "Toda decisión admite revisión la próxima temporada."], "La enfermería del centro y la salida nunca dependen de los turnos."], [
      N("Cira Mesa", "trchar008", "coordinadora de la asamblea", "MAGNEZONE", "Magnezone", "reunir cuarenta voces sin que ninguna pese de más", "dejó que la historia más sonada acaparara la mesa",
        ["La ronda se cerraba cuando la voz famosa terminaba", "me precipité: confundí aplauso con derecho a turno", "mediré los turnos y dejaré el acta corregible"],
        ["las cuarenta voces tuvieron su minuto y el acta quedó abierta", "Magnezone sostiene el cronómetro sin apagar ninguna voz", "la próxima temporada reabrirá las decisiones"]),
      N("Ugo Testigo", "NPC 04", "cronista invitado", "CHATOT", "Chatot", "transcribir sin decidir qué historia importa", "resumía las intervenciones dejando fuera las dudas",
        ["Mis actas eran limpias y mentían por omisión", "tardé en reconocer que un resumen también elige bando", "transcribiré dudas, silencios y correcciones"],
        ["el acta conserva las cuatro capas de cada intervención", "Chatot repite lo dicho sin mejorar el tono", "cualquiera podrá firmar una corrección al acta"])],
    ["¿Cómo decidirá la asamblea?", ["Rondas de turno con acta revisable", "Votación rápida al cierre de cada ronda"]],
    ["la asamblea aprueba el turno coral y abre el libro de correcciones", "el centro Pokémon publica el calendario de rondas"],
    ["MARANGABERRY", "Eleva la voz de cada historia sin que ninguna ocupe el atril para siempre."]),
  R(2008, "El Escenario que Reunía a los Ausentes",
    "Un escenario evoca ecos de campeones ausentes y el público trata a las apariciones como marionetas de su propio recuerdo.",
    "Invitación con nombre: cada eco se anuncia con su nombre verdadero, descansa entre apariciones y sale cuando quiere.",
    ["Invitación con nombre", ["Cada eco se anuncia con su nombre verdadero.", "Ninguna aparición se repite sin descanso declarado.", "Todo eco puede retirarse sin pedir permiso."], "Las salidas del escenario permanecen iluminadas y libres durante la función."], [
      N("Ámbar Escena", "trchar009", "maestra de ceremonias", "DRAGONITE", "Dragonite", "honrar a los ausentes sin usarlos de trofeo", "programó tres funciones seguidas con el mismo eco",
        ["El eco del campeón apareció tres veces sin descanso", "me precipité: llené cartel y vacié la cortesía", "anunciaré nombres, respetaré descansos y abriré la retirada"],
        ["las funciones se anuncian con nombre y pausa", "Dragonite anuncia cada retirada con la voz baja", "el público aprendió a aplaudir sin pedir repetición"]),
      N("Nardo Eco", "NPC 04", "evocador del escenario", "UNOWN", "Unown", "evocar sin fabricar voluntades ajenas", "escribió guiones que ponían palabras en boca de los ausentes",
        ["Mis guiones hablaban por quienes ya no pueden corregirme", "tardé en reconocer que evocar no es ventriloquía", "devolveré el silencio y citaré solo lo documentado"],
        ["las evocaciones citan fuentes y se detienen donde empieza la duda", "Unown deletrea lo que sí está escrito", "el escenario guarda sus guiones como homenaje, no como verdad"])],
    ["¿Qué verá el público en la función?", ["Ecos anunciados con nombre y pausa", "Función continua de evocaciones"]],
    ["el escenario publica su reglamento de invitaciones y descansos", "las salidas se iluminan antes de cada función"],
    ["DRAGONFANG", "Preserva el filo de una voz ausente sin convertirla en arma de espectáculo."]),
  R(2015, "La Torre que Reunía los Cuarenta Archivos",
    "En el umbral final, los cuarenta archivos de Atlas compiten por definir un solo cierre y los archiveros temen perder versiones.",
    "Cerrar la temporada sin cerrar el archivo: conservar las cuarenta versiones y decidir solo el siguiente capítulo.",
    ["Cierre con reservas", ["Las cuarenta versiones se conservan íntegras.", "La decisión se anuncia como capítulo, no como final.", "Todo archivo conserva su llave propia."], "La torre mantiene su baliza de retorno y el acceso libre a los archivos en todo momento."], [
      N("Cima Archivo", "trchar008", "archivera del umbral", "MAMOSWINE", "Mamoswine", "sostener mil historias sin elegir una favorita", "propuso fundir los cuarenta archivos en uno solo",
        ["El borrador de cierre fundía los archivos y perdía las manos", "me precipité: quise un cierre elegante y apliqué una fusión", "conservaré las llaves y propondré un capítulo"],
        ["las cuarenta llaves siguen en su sitio y el capítulo se anuncia", "Mamoswine sostiene la entrada sin entrar a elegir", "cada temporada podrá escribir el capítulo siguiente"]),
      N("Ilya Coro", "NPC 04", "coordinadora de voces", "PRIMARINA", "Primarina", "dirigir el coro sin imponer una letra", "ensayó un solo tema para todas las historias",
        ["Mi coro ensayaba una letra para cuarenta bocas distintas", "tardé en reconocer que la armonía exigía borrar diferencias", "ensayaré con las cuarenta voces y respetaré sus tonos"],
        ["el coro sonó desigual y por fin verdadero", "Primarina marca el compás sin tapar ninguna voz", "el capítulo se cantará con todas las partituras a la vista"])],
    ["¿Qué decidirá la torre?", ["Un capítulo siguiente con archivos intactos", "Un cierre único que funda los archivos"]],
    ["la torre publica el capítulo y devuelve las cuarenta llaves", "el umbral abre su calendario de temporadas"],
    ["PROTECTOR", "Custodia las cuarenta versiones mientras el coro decide su próximo capítulo."]),
];

const all = [...specs06, ...specs07];
if (specs06.length !== 25) throw new Error(`Se esperaban 25 rutas en macro06 y hay ${specs06.length}.`);
if (specs07.length !== 10) throw new Error(`Se esperaban 10 rutas en macro07 y hay ${specs07.length}.`);

const banned = /soy un entrenador|qué gran combate|este pokémon es muy fuerte|según la pokédex|debes derrotarme/i;
for (const spec of all) for (const npc of spec.npcs) {
  if (!npc.partnerName) throw new Error(`${spec.mapId}: falta nombre de presentación de ${npc.name}`);
  const lines = [...npc.dialogue.before, ...npc.dialogue.after];
  if (lines.some((line) => banned.test(line))) throw new Error(`${spec.mapId}: frase genérica en ${npc.name}`);
  if (lines.length !== 6) throw new Error(`${spec.mapId}: ${npc.name} necesita 3+3 líneas`);
}

function compileSpec(spec, globalIndex) {
  const flag = 833 + globalIndex;
  const variable = 229 + globalIndex;
  const [mechanicName, rules, failureSafe] = spec.mechanic;
  const [question, options] = spec.decision;
  const [item, meaning] = spec.reward;
  const [immediate, later] = [spec.consequence, spec.npcs.map((npc) => npc.dialogue.after[2])];
  return {
    tier: 2,
    routeBatch: 18 + Math.floor(globalIndex / 5),
    mapId: spec.mapId,
    flag,
    variable,
    title: spec.title,
    promise: sentence(spec.promise),
    objective: sentence(spec.objective),
    mechanic: { name: mechanicName, rules: rules.map(sentence), failureSafe: sentence(failureSafe) },
    npcs: spec.npcs.map((npc) => ({
      name: npc.name,
      sprite: npc.sprite,
      role: npc.role,
      partnerPokemon: npc.partnerPokemon,
      motivation: npc.motivation,
      conflict: npc.conflict,
      dialogue: npc.dialogue,
    })),
    decision: {
      question: sentence(question),
      options,
      immediate: immediate.map(sentence),
      later: later.map(sentence),
    },
    reward: { item, meaning: sentence(meaning) },
    progression: { switchId: flag, decisionVariable: variable, freeReturnMapId: 1001 },
    safety: { bagAlwaysAvailable: true, noForcedBattle: true, existingChallengePreserved: true, baseChallengeExpected: false, freeReturn: true, rewardOnce: true },
  };
}

for (const [macroCycle, offset, specs] of [[6, 0, specs06], [7, 25, specs07]]) {
  const blueprints = specs.map((spec, index) => compileSpec(spec, offset + index));
  const output = { version: 1, macroCycle, tier2Batches: macroCycle === 6 ? 5 : 2, blueprints };
  const target = path.join(ROOT, "content", `atlas_tier2_blueprints_macro${String(macroCycle).padStart(2, "0")}.json`);
  fs.writeFileSync(target, `${JSON.stringify(output, null, 2)}\n`);
  console.log(`Tier 2 macrociclo ${String(macroCycle).padStart(2, "0")}: ${blueprints.length} rutas en ${output.tier2Batches} lotes.`);
}
