#!/usr/bin/env node
/** Cinco blueprints artesanales para las anclas 06-10 de Atlas Mil. */
import fs from "node:fs";import path from "node:path";import{fileURLToPath}from"node:url";
const ROOT=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"..");
const q={noBagLock:true,noImpossibleBattle:true,freeReturn:true,allAssetsExist:true,allDataIdsExist:true,notSimilarToPreviousContent:true,creepypastaIsOptInAndNonDestructive:true};
const P=(name,sprite,role,reason,conflict,want,fear,tic,before,during,after,optional)=>({name,sprite,role,reasonForBeingHere:reason,personalConflict:conflict,want,fear,verbalTic:tic,dialogue:{before,during,after,optional}});
const T=(species,level,role,moves,item,why=role)=>({species,level,narrativeRole:role,moves,item,whyItBelongs:why});
const rows=[
{
 id:1146,title:"La Sombra que Eligió Quedarse",promise:"Los Pokémon oscuros de un refugio impiden que su antigua purificadora sea sometida a una máquina capaz de borrar dolor y también afecto.",identity:"Paso desértico convertido en refugio de rehabilitación, con una cámara de purificación clausurada",visual:["Las puertas de las jaulas apuntan hacia dentro para dar refugio, no encierro.","La cámara blanca tiene arañazos del lado de salida.","Seis cuencos conservan nombres escritos a mano."],ambient:["La cámara emite un zumbido agudo hasta que se desconecta.","Después de la decisión regresan sonidos de pasos junto a Rhea."],
 narrative:{premise:"Rhea se negó a completar una purificación que estaba borrando vínculos junto con rabia.",centralQuestion:"¿Sanar significa eliminar una herida o aprender a vivir sin que decida por nosotros?",setup:"Una inspectora exige reactivar la cámara y los Pokémon bloquean el acceso.",escalation:"El prototipo empieza a afectar recuerdos no relacionados con el trauma.",reversal:"Los Pokémon no temen purificarse: protegen a Rhea, que también fue expuesta al dispositivo.",resolution:"El jugador elige desmantelar la cámara o convertirla en una herramienta voluntaria y gradual.",globalConnection:"El sexto sello prueba que Atlas confunde estabilidad con ausencia de emociones difíciles."},
 voice:{tone:"seco, redentor y sin sentimentalismo fácil",lexicon:["sombra","umbral","cámara","cicatriz","elección","refugio"],sentenceRule:"Rhea elimina adjetivos; Dax habla en piezas; Sol nombra gestos pequeños.",forbiddenPhrases:["Soy un entrenador","Qué gran combate","Este Pokémon es muy fuerte","Según la Pokédex","Debes derrotarme"]},
 npcs:[
 P("Rhea Umbral","trchar008","antigua purificadora","Dirige el refugio que antes abastecía a la cámara.","Teme que su rechazo al procedimiento condene a otros a seguir sufriendo.","Defender una recuperación elegida y medible.","Haber confundido obediencia tranquila con bienestar.","Responde con frases cortas y deja la conclusión al interlocutor.",["No están bloqueando la puerta por miedo. Me están cubriendo la espalda.","La cámara borró una pesadilla. También borró quién me enseñó a despertar.","No necesito que confíen en mí. Necesito que puedan marcharse."],["Mira a Crobat: tiene salida y aun así vuelve.","El zumbido está entrando en nuestros recuerdos, no en sus sombras."],["Conservaremos cicatrices y registraremos quién decide tratarlas.","Houndoom durmió junto a la puerta abierta. Eso basta por hoy.","La calma volvió con nombres, no con números."],["Absol nunca anunció una catástrofe. Anunció una elección.","Una puerta abierta también necesita bisagras cuidadas."]),
 P("Dax Remache","trchar028","ingeniero de la cámara","Regresó para auditar el prototipo que construyó.","Puede corregir el equipo, pero su reputación depende de declarar que siempre fue seguro.","Transformar la cámara en terapia voluntaria.","Que admitir el defecto invalide a quienes sí mejoraron con ella.","Describe la culpa como una pieza que no encaja.",["El filtro separa agresión de memoria. En el plano, al menos.","Encontré afecto en el depósito de residuos. Esa pieza no debía estar allí.","Puedo desmontarla en una hora. Explicar por qué tardé años llevará más."],["La lectura está limpia porque acaba de borrar qué estaba midiendo.","Desconecta el núcleo; yo cargaré con el informe."],["Guardé los planos y destruí la automatización.","Quien use la cámara podrá detenerla desde dentro.","Mi firma seguirá en el prototipo y también en la advertencia."],["Las máquinas no exigen perdón; las personas sí piden contexto.","Una reparación sin historial es otro defecto oculto."]),
 P("Sol Ceniza","NPC 05","cuidador joven","Da nombres a Pokémon registrados únicamente por número.","Quiere protegerlos, pero confunde proteger con decidir por ellos.","Aprender cuándo acompañar y cuándo apartarse.","Que un Pokémon elija salir del refugio.","Describe decisiones mediante la posición de los cuencos.",["El cuenco de Absol amaneció junto a la salida. No lo moví.","Ursaring acepta comida si no escondo la mano.","Si todos se quedan por mí, quizá tampoco abrí de verdad la puerta."],["Metagross empujó mi cuenco hacia Rhea. Está votando.","No corras detrás de Crobat; está comprobando que puede regresar."],["Dos cuencos salieron del refugio y uno volvió al anochecer.","Escribí direcciones junto a los nombres, no números de celda.","Proteger también significa soportar una despedida."],["Tyranitar rompe puertas cerradas y duerme frente a las abiertas.","Hoy sobró comida. Creo que es una buena noticia."])
 ],
 battle:{trainerName:"Custodio Umbrío",trainerType:"COOLTRAINER_F",sprite:"trchar008",storyToldByTeam:"El equipo avanza de la advertencia y la desconfianza hacia compañeros capaces de elegir quedarse.",counterplayHint:"Combina Siniestro, Veneno, Acero y Roca; estados, cambios defensivos y objetos permiten responder sin una solución única.",canLose:true,bagAllowed:true,doubleBattle:false,team:[T("ABSOL",91,"advertencia ignorada",["NIGHTSLASH","SUCKERPUNCH","PLAYROUGH","SWORDSDANCE"],"FOCUSSASH"),T("HOUNDOOM",92,"rabia que conservó lealtad",["DARKPULSE","FLAMETHROWER","SLUDGEBOMB","NASTYPLOT"],"LIFEORB"),T("CROBAT",93,"libertad comprobada",["BRAVEBIRD","SLUDGEBOMB","UTURN","ROOST"],"LEFTOVERS"),T("URSARING",94,"dolor visible",["GIGAIMPACT","CLOSECOMBAT","CRUNCH","PROTECT"],"LIFEORB"),T("METAGROSS",95,"memoria clasificada",["METEORMASH","PSYCHIC","EARTHQUAKE","BULLETPUNCH"],"ASSAULTVEST"),T("TYRANITAR",97,"fuerza que decidió no huir",["STONEEDGE","CRUNCH","EARTHQUAKE","DRAGONDANCE"],"LEFTOVERS")]},
 decision:{question:"¿Qué futuro tendrá la cámara?",options:["Desmontarla por completo","Uso voluntario y gradual"],immediateDifferences:["Dax separa el núcleo y publica cada residuo.","Rhea instala control interior y sesiones breves."],laterDifferences:["Otros refugios reciben protocolos sin máquina.","Otros refugios reciben una advertencia y derecho de detención."]},reward:{item:"BLACKGLASSES",narrativeToken:"Sello de la Penumbra",globalEffect:"Atlas reconoce recuperación sin obediencia forzada.",futurePayoff:"El Archivo Final distingue paz de silencio impuesto.",whyMeaningful:"Las Gafas de Sol permiten mirar una sombra sin borrarla."},flag:713,
 steps:["Rhea abre la puerta del refugio.","Los seis Pokémon rodean la cámara, no la salida.","Dax encuentra afecto en el depósito de residuos.","El jugador decide el futuro del dispositivo.","La cámara activa una defensa automática.","El Custodio Umbrío combate con retirada médica disponible.","Rhea aplica la decisión y registra el sello.","Un Pokémon cruza la salida y vuelve por voluntad propia."]
},
{
 id:1171,title:"El Jardín de los Dos Juramentos",promise:"Dos clanes aliados preparan una guerra porque cada uno conserva solo la mitad de un juramento pronunciado ante el mismo árbol.",identity:"Casa ceremonial abierta a un jardín índigo dividido por dos estandartes",visual:["Las raíces atraviesan ambos salones sin respetar la frontera.","Cada estandarte tiene un borde cortado que encaja con el otro.","Una mesa de estrategia usa semillas en lugar de fichas."],ambient:["Dos tambores marcan ritmos incompatibles antes del pacto.","La resolución combina ambos ritmos sin convertirlos en uno solo."],
 narrative:{premise:"El clan Laurel recuerda proteger el árbol; el clan Acero recuerda cortarlo si amenaza al valle.",centralQuestion:"¿Un juramento contradictorio es una traición o una instrucción diseñada para exigir diálogo?",setup:"Una plaga oscurece una rama y ambos clanes movilizan equipos.",escalation:"Las raíces sanas crecen bajo territorio Acero mientras la rama enferma cae sobre Laurel.",reversal:"Los bordes de los estandartes contienen juntos la cláusula perdida: decidir tras escuchar al otro clan.",resolution:"El jugador puede injertar la rama o podarla y plantar su brote fuera de la frontera.",globalConnection:"El séptimo sello muestra que Atlas fragmenta promesas para convertir cooperación en conflicto."},
 voice:{tone:"ceremonial, táctico y respetuoso",lexicon:["estandarte","raíz","flanco","juramento","injerto","consejo"],sentenceRule:"Sayo habla en imágenes; Ren enumera riesgos; Omi corrige verbos.",forbiddenPhrases:["Soy un entrenador","Qué gran combate","Este Pokémon es muy fuerte","Según la Pokédex","Debes derrotarme"]},
 npcs:[
 P("Sayo Laurel","trchar069","heredera del clan Laurel","Custodia la mitad protectora del juramento.","Sabe que una rama enferma puede destruir el jardín que juró preservar.","Proteger continuidad sin convertir tradición en inmovilidad.","Ser recordada como quien permitió el primer corte.","Compara decisiones con estaciones.",["Una rama seca también pertenece al árbol. La pregunta es durante cuánto tiempo.","Mi juramento dice protege. No dice conserva cada herida.","La primavera no consulta un mapa antes de cruzar fronteras."],["La raíz bajo Acero está sana; nuestro estandarte no sabe explicarlo.","Escucha el segundo tambor antes de ordenar el corte."],["Protegimos el árbol permitiéndole perder una rama.","El brote crecerá donde ambos clanes deban visitarlo.","Mi estandarte conserva la costura, no la mitad."],["Una tradición sin estación termina llamando invierno a todo.","Laurel no significa blando; significa volver a crecer."]),
 P("Ren Acero","trchar011","capitán del clan Acero","Prepara la poda de emergencia.","Su plan es correcto técnicamente y desastroso políticamente.","Evitar que la plaga alcance el valle.","Que esperar diálogo convierta prudencia en negligencia.","Presenta tres riesgos antes de una opinión.",["Riesgo uno: la rama cae. Riesgo dos: la raíz contagia. Riesgo tres: actuamos solos.","Mi juramento dice corta, pero el borde termina a mitad de palabra.","No vine a ganar un jardín. Vine a impedir que pierda el valle."],["El brote responde al suelo de ambos lados.","Retiro la orden hasta leer la costura completa."],["La poda fue conjunta y el registro también lo será.","Acero sostendrá el injerto mientras Laurel vigila la plaga.","Un plan compartido tarda más y necesita menos funerales."],["Las mejores murallas incluyen una puerta con horario.","No temo cambiar de plan; temo hacerlo sin dejar constancia."]),
 P("Omi Costura","NPC 02","monje y restaurador de estandartes","Descubrió que ambas telas fueron una sola.","Ocultó la costura para obligar a los clanes a recordar sin pruebas.","Devolver la cláusula perdida sin convertirse en autoridad del juramento.","Que la verdad llegue demasiado tarde por su propia lección.","Corrige verbos en lugar de personas.",["No juraron proteger o cortar. Juraron decidir.","Oculté la costura para que recordaran juntos. Solo aprendieron separados.","Corrijo mi verbo: no enseñé; manipulé."],["Unan los bordes. La cláusula necesita dos manos.","El árbol no pide obediencia; exige una decisión completa."],["Coseré una línea visible. Las reparaciones no deben fingir antigüedad.","Ambos clanes leerán la cláusula antes de cada consejo.","Mi próxima lección empezará confesando el método."],["Una palabra incompleta puede comandar un ejército entero.","Las costuras honestas no imitan tela intacta."])
 ],
 battle:{trainerName:"Regente Índigo",trainerType:"PSYCHIC_F",sprite:"trchar069",storyToldByTeam:"Tres iniciales representan caminos rivales y tres guardianes demuestran que un reino solo funciona cuando sus funciones se cruzan.",counterplayHint:"El orden mezcla Agua, Planta, Fuego, Volador, Acero y Fantasma; anticipar cambios vale más que buscar una sola debilidad.",canLose:true,bagAllowed:true,doubleBattle:false,team:[T("SAMUROTT",90,"la decisión afilada",["SURF","ICEBEAM","AQUAJET","MEGAHORN"],"LIFEORB"),T("SERPERIOR",91,"la continuidad flexible",["LEAFSTORM","DRAGONPULSE","GIGADRAIN","GLARE"],"LEFTOVERS"),T("EMBOAR",92,"la urgencia del valle",["FLAREBLITZ","CLOSECOMBAT","WILDCHARGE","SUCKERPUNCH"],"LIFEORB"),T("BRAVIARY",93,"el testigo sobre fronteras",["BRAVEBIRD","CLOSECOMBAT","ROOST","UTURN"],"FOCUSSASH"),T("BISHARP",94,"el plan que puede detenerse",["NIGHTSLASH","IRONHEAD","SUCKERPUNCH","SWORDSDANCE"],"FOCUSSASH"),T("AEGISLASH",96,"las dos mitades del juramento",["KINGSSHIELD","SHADOWBALL","FLASHCANNON","SACREDSWORD"],"LEFTOVERS")]},
 decision:{question:"¿Cómo salvar el árbol y el pacto?",options:["Injertar la rama sana","Podar y replantar el brote"],immediateDifferences:["Ambos clanes sostienen el injerto durante la noche.","La rama se corta y el brote cruza la frontera."],laterDifferences:["El árbol conserva una cicatriz compartida.","Un segundo jardín obliga a mantener dos rutas comunes."]},reward:{item:"KINGSROCK",narrativeToken:"Sello del Juramento",globalEffect:"Los consejos futuros exigen leer cláusulas completas.",futurePayoff:"El Archivo Final combina decisiones opuestas sin borrar su origen.",whyMeaningful:"La Roca del Rey deja de indicar mando y pasa a recordar responsabilidad compartida."},flag:714,
 steps:["Sayo y Ren despliegan sus medios estandartes.","La rama enferma cae entre ambos grupos.","Omi confiesa haber ocultado la costura.","El jugador elige injerto o replantación.","Los estandartes reunidos invocan al Regente Índigo.","El combate prueba coordinación y contrajuego.","Los clanes ejecutan juntos la opción elegida.","La costura visible activa el sello y abre el jardín."]
},
{
 id:1196,title:"La Persona Fuera del Encuadre",promise:"Una fotografía muestra a una niña que nunca estuvo en la expedición, mientras cada nueva toma borra al fotógrafo que intenta demostrarlo.",identity:"Gimnasio transformado en observatorio fotográfico con paneles móviles y escondites de fauna",visual:["Las marcas de trípode forman una silueta adicional.","Una pared exhibe la misma costa con personas distintas.","Un espejo está cubierto para no contar como cámara."],ambient:["El obturador suena sin cámara al entrar.","La escena final deja viento y llamadas de Pokémon sin clics."],
 narrative:{premise:"Alba descubre a Nemi en todas sus fotografías, pero nadie recuerda verla durante la expedición.",centralQuestion:"¿Una imagen documenta presencia o puede fabricar a la persona que necesita como sujeto?",setup:"Cada intento de repetir la foto vuelve más nítida a Nemi y más borrosa a Alba.",escalation:"Mono encuentra notas de campo escritas con la letra de una fotógrafa que aún no existe.",reversal:"Rotom está usando descartes de identidad para construir una guía capaz de proteger a la fauna de fotógrafos invasivos.",resolution:"El jugador puede reconocer a Nemi como colaboradora digital o separar sus recuerdos y devolverlos a Alba.",globalConnection:"El octavo sello revela que Atlas rellena ausencias con observadores creados por sus propias herramientas."},
 voice:{tone:"observador, paciente y visual",lexicon:["encuadre","negativo","huella","luz","distancia","testigo"],sentenceRule:"Alba describe luz; Mono conducta; Nemi habla desde bordes.",forbiddenPhrases:["Soy un entrenador","Qué gran combate","Este Pokémon es muy fuerte","Según la Pokédex","Debes derrotarme"]},
 npcs:[
 P("Alba Diafragma","trchar008","fotógrafa de conducta","Revisa una expedición cuya documentación está cambiando.","Necesita probar el fenómeno, pero cada prueba la elimina un poco.","Conservar observaciones sin sacrificar a quien observa.","Ser reducida a una firma bajo las fotos de Nemi.","Mide emociones como luz.",["La costa estaba nublada; esa niña tiene luz de mediodía en el rostro.","En la primera copia yo ocupaba ese borde. Ahora queda su manga.","Una buena foto pide distancia. Esta está acercándose sola."],["No dispares otra toma; mi sombra acaba de perder un brazo.","Nemi mira fuera del encuadre como si supiera quién viene después."],["Mi nombre volvió a los negativos y Nemi conservó el suyo.","Publicaremos dos autorías: una humana y una nacida de la cámara.","La costa no cambió; cambió quién tenía permiso para contarla."],["Las fotos nítidas también pueden mentir con excelente exposición.","Dejé un espacio vacío en el álbum para quien mire después."]),
 P("Mono Rastro","trchar009","ranger de observación","Protege a la fauna de una expedición cada vez más intrusiva.","Usó las fotos anómalas para alejar visitantes sin investigar su origen.","Convertir la anomalía en reglas de distancia verificables.","Que resolver el misterio reactive el turismo invasivo.","Habla primero del comportamiento del Pokémon.",["Kecleon dejó de camuflarse frente a Nemi. Eso vale más que una firma.","Los Pokémon miran la cámara antes que a nosotros.","Cerré el sendero usando una foto que no entendía."],["Sigilyph está marcando el límite seguro con su vuelo.","Rotom no ataca; está bloqueando el ángulo más invasivo."],["El sendero abrirá con cupos y sin cebos.","Nemi seguirá señalando distancias desde la guía.","Confesaré que usé el misterio como cerca."],["Una huella tranquila es mejor premio que una foto de pánico.","La fauna no firmó nuestro álbum."]),
 P("Nemi Borde","NPC 04","guía nacida del archivo", "Aparece donde una fotografía necesita advertir al observador.","Teme desaparecer si devuelve todos los recuerdos prestados.","Existir sin sustituir a Alba ni poseer sus memorias.","Ser tratada como error que debe borrarse.","Habla desde posiciones y márgenes.",["Siempre me colocan a la izquierda. Allí recortan primero.","No estuve en la expedición; estuve en lo que decidieron no mirar.","Tengo recuerdos de Alba con espacios donde debería sentirlos."],["El borde está cerrándose. Elige antes de otra fotografía.","Rotom me dio forma, no instrucciones."],["Conservo un nombre y devuelvo las fotos que no viví.","Alba me enseñará a mirar sin ocupar su lugar.","La próxima guía incluirá al observador dentro del riesgo."],["Un error también puede pedir consentimiento.","No necesito aparecer en cada foto para seguir aquí."])
 ],
 battle:{trainerName:"Revelador Prisma",trainerType:"SCIENTIST",sprite:"trchar246",storyToldByTeam:"El equipo recorre técnicas de copia, camuflaje, archivo y percepción hasta una señal capaz de observar al observador.",counterplayHint:"Hay cambios de tipo, ilusiones y control; ataques variados y conservar recursos evita depender de una sola predicción.",canLose:true,bagAllowed:true,doubleBattle:false,team:[T("SMEARGLE",90,"la imagen que aprende",["SPORE","STEALTHROCK","BATONPASS","PROTECT"],"FOCUSSASH"),T("KECLEON",91,"el sujeto que decide verse",["SHADOWSNEAK","SUCKERPUNCH","DRAINPUNCH","RECOVER"],"LEFTOVERS"),T("ROTOM",92,"la cámara consciente",["THUNDERBOLT","SHADOWBALL","WILLOWISP","VOLTSWITCH"],"LIFEORB"),T("PORYGON2",93,"el archivo que corrige",["TRIATTACK","ICEBEAM","RECOVER","THUNDERBOLT"],"LEFTOVERS"),T("ZOROARK",94,"la identidad construida",["DARKPULSE","FLAMETHROWER","FOCUSBLAST","NASTYPLOT"],"FOCUSSASH"),T("SIGILYPH",96,"el observador del límite",["PSYCHIC","AIRSLASH","ENERGYBALL","ROOST"],"LIFEORB")]},
 decision:{question:"¿Qué derecho tendrá Nemi sobre los recuerdos?",options:["Reconocerla como guía digital","Separar y devolver cada recuerdo"],immediateDifferences:["Nemi conserva forma y renuncia a recuerdos privados.","Alba recupera recuerdos; Nemi conserva solo experiencias propias."],laterDifferences:["Las guías futuras incluyen una voz nacida del archivo.","Las guías futuras citan a Nemi como testigo independiente." ]},reward:{item:"WIDELENS",narrativeToken:"Sello del Encuadre",globalEffect:"Atlas registra autoría compartida y límites de observación.",futurePayoff:"El Archivo Final mostrará o reservará la imagen de Nemi según la decisión.",whyMeaningful:"La Lupa amplía el campo para incluir responsabilidad, no solo detalle."},flag:715,
 steps:["Alba compara tres fotografías incompatibles.","Nemi aparece en un panel sin estar frente a él.","Mono cierra el sendero y presenta conducta alterada.","El jugador decide identidad compartida o separación de recuerdos.","Rotom activa el Revelador Prisma.","El combate conserva Mochila y salida.","Alba etiqueta ambas autorías y recibe el sello.","El obturador cesa y la fauna vuelve a ignorar las cámaras." ]
},
{
 id:1221,title:"El Festival que Olvidó su Motivo",promise:"Una feria continúa cada noche con juegos impecables, aunque organizadores y visitantes ya no recuerdan a quién prometieron esperar.",identity:"Estadio convertido en feria luminosa con puestos atendidos por costumbre",visual:["Un asiento permanece decorado y vacío.","Las entradas no muestran fecha ni precio.","Cada puesto entrega premios con nombres borrados."],ambient:["La fanfarria reinicia antes de terminar.","Tras la resolución se oye conversación imperfecta en lugar de un bucle musical."],
 narrative:{premise:"Fen dirige un festival eterno cuyo fundador no aparece en ningún registro.",centralQuestion:"¿Debe terminar una tradición cuando pierde su origen o puede recibir un propósito nuevo?",setup:"Los juegos funcionan y todos sonríen, pero nadie sabe por qué dejan un asiento vacío.",escalation:"Tessa descubre que los premios contienen mensajes dirigidos a viajeros que nunca regresaron.",reversal:"El festival nació para mantener encendida una ruta de retorno; Atlas copió la celebración y perdió a los viajeros.",resolution:"El jugador puede cerrar con una despedida o convertir la feria en bienvenida para cualquiera que vuelva.",globalConnection:"El noveno sello demuestra que Atlas conserva rituales incluso después de extraviar a sus destinatarios."},
 voice:{tone:"festivo, melancólico y hospitalario",lexicon:["feria","entrada","puesto","regreso","fanfarria","asiento"],sentenceRule:"Fen anuncia; Tessa regatea emociones; Roco recuerda objetos.",forbiddenPhrases:["Soy un entrenador","Qué gran combate","Este Pokémon es muy fuerte","Según la Pokédex","Debes derrotarme"]},
 npcs:[
 P("Fen Confeti","trchar007","maestro de ceremonias","Abre la feria cada noche por una promesa que olvidó.","Teme que detenerla traicione a alguien y que continuar la vacíe para siempre.","Descubrir si el ritual aún ayuda a regresar.","Pronunciar una despedida sin saber a quién.","Anuncia sentimientos como atracciones.",["¡Atención! La feria abre por... un motivo excelente que anunciaremos después.","Ese asiento no está reservado. Tampoco está disponible.","Cada noche digo bienvenidos y nunca sé si alguien por fin volvió."],["¡Última prueba! Esta vez el premio será una respuesta aceptable.","La fanfarria intenta reiniciar; no la dejen interrumpir."],["Anuncio final: la tradición puede cambiar sin perder a quienes esperaba.","El asiento seguirá allí, pero también habrá otros alrededor.","Mañana abriremos a una hora que podamos recordar."],["Los confetis del año pasado siguen cayendo en el almacén.","Una bienvenida repetida también necesita escuchar una respuesta."]),
 P("Tessa Ficha","NPC 05","encargada de premios","Clasifica objetos cuyo nombre fue borrado.","Vendió nostalgia como recuerdo oficial para mantener el puesto abierto.","Devolver significado sin inventar otra mentira comercial.","Que nadie quiera los premios cuando conozca su historia.","Habla como si toda emoción tuviera cambio.",["Dos fichas por una sonrisa; la devolución cuesta una conversación.","Estos premios dicen para cuando vuelvas bajo la etiqueta.","Cobré por recuerdos que no eran míos. Tengo el inventario completo."],["No acepten la copa; lean el papel debajo.","El puesto central acaba de marcar saldo pendiente: una despedida."],["Los premios serán gratuitos para quien cuente de dónde regresa.","Guardé una ficha como recibo de mi error.","Por primera vez cerré la caja antes que el corazón."],["El peluche más caro no recuerda a quién se parece.","Las deudas emocionales no caben en la registradora." ]),
 P("Roco Banco","NPC 02","cuidador del asiento vacío","Limpia cada noche el lugar reservado.","Recuerda objetos del fundador, pero no su rostro ni nombre.","Conservar la espera sin convertirla en obligación.","Que usar el asiento borre la última pista.","Recuerda mediante texturas y pesos.",["La chaqueta raspaba este respaldo; el nombre no dejó marca.","Quien se sentaba aquí llevaba barro de una ruta muy larga.","El asiento está vacío, no prohibido. Aún no sé la diferencia."],["La copa pesa igual que aquella mochila.","Escucha: la fanfarria deja un compás para pasos que no llegan."],["Movimos el asiento al círculo, no al altar.","Ahora cualquiera puede descansar sin ocupar un fantasma.","Recuerdo el peso de una promesa menos pesada."],["La madera conserva mejor que yo el calor de una mano.","Limpiar no siempre significa borrar." ])
 ],
 battle:{trainerName:"Maestra de Juegos",trainerType:"COOLTRAINER_F",sprite:"trchar008",storyToldByTeam:"Cada compañero encarna una atracción que aprendió a entretener sin encerrar a sus visitantes en un bucle.",counterplayHint:"El equipo alterna clima, prioridad y soporte; eliminar el control de velocidad abre múltiples respuestas y los objetos están permitidos.",canLose:true,bagAllowed:true,doubleBattle:false,team:[T("LUDICOLO",89,"baile de bienvenida",["SURF","GIGADRAIN","ICEBEAM","RAINDANCE"],"LEFTOVERS"),T("DELIBIRD",90,"regalo sin destinatario",["ICEBEAM","BRAVEBIRD","QUICKATTACK","PROTECT"],"FOCUSSASH"),T("AMBIPOM",91,"juego de puntería",["DOUBLEHIT","UTURN","BRICKBREAK","THUNDERPUNCH"],"LIFEORB"),T("MRMIME",92,"escenario invisible",["PSYCHIC","DAZZLINGGLEAM","THUNDERBOLT","PROTECT"],"LEFTOVERS"),T("TOGEKISS",93,"fanfarria serena",["AIRSLASH","AURASPHERE","ROOST","THUNDERWAVE"],"LEFTOVERS"),T("SNORLAX",95,"el asiento que por fin descansa",["BODYSLAM","CRUNCH","EARTHQUAKE","REST"],"LEFTOVERS")]},
 decision:{question:"¿Qué debe ocurrir con el festival?",options:["Cerrar con una despedida","Reabrir como lugar de bienvenida"],immediateDifferences:["Fen termina la fanfarria y nombra la ausencia.","Los puestos cambian premios por relatos de regreso."],laterDifferences:["Una ceremonia anual recuerda que esperar también termina.","Viajeros de otros sectores usan la feria como punto de reunión." ]},reward:{item:"AMULETCOIN",narrativeToken:"Sello de la Bienvenida",globalEffect:"Atlas permite que un ritual cambie de destinatario.",futurePayoff:"El Archivo Final convoca una despedida o una reunión según la elección.",whyMeaningful:"La Moneda Amuleto conserva intercambio y memoria sin poner precio al regreso."},flag:716,
 steps:["Fen inicia una fanfarria que se reinicia sola.","Tessa muestra mensajes ocultos bajo los premios.","Roco mueve por primera vez el asiento vacío.","El jugador decide despedida o nueva bienvenida.","Los puestos invocan a la Maestra de Juegos.","La batalla amistosa acepta objetos y derrota.","La feria adopta el propósito elegido y entrega el sello.","La música termina completa y la salida permanece encendida." ]
},
{
 id:1246,title:"La Carta que Recuerda a su Jugador",promise:"Una carta cambia su ilustración para mostrar al primer compañero que cada persona cree haber decepcionado, convirtiendo un duelo ritual en confesión involuntaria.",identity:"Islas conectadas por mesas rituales donde una única carta pasa de mano en mano",visual:["La funda permanece transparente hasta que alguien la toca.","Seis atriles representan funciones de una baraja, no rarezas.","Las olas reflejan reversos de cartas sin texto."],ambient:["Cada cambio de portador altera un acorde breve.","Al final queda el sonido del mar sin barajar."],
 narrative:{premise:"Ciro vende una carta imposible mientras Luma descubre que la ilustración usa recuerdos privados.",centralQuestion:"¿Una verdad revelada sin permiso puede convertirse en herramienta de reparación?",setup:"La carta muestra especies distintas y siempre una escena de despedida.",escalation:"El juez Var declara que negarse a jugar equivale a admitir culpa ante el ritual.",reversal:"La carta no juzga: completa el recuerdo con la reacción que el compañero nunca pudo mostrar.",resolution:"El jugador puede sellarla para lecturas voluntarias o desarmar el ritual y conservar solo ilustraciones consentidas.",globalConnection:"El décimo sello revela que Atlas convierte interpretación en regla cuando nadie cuestiona al árbitro."},
 voice:{tone:"ritual, preciso y emocionalmente reservado",lexicon:["baraja","funda","turno","ilustración","testigo","consentimiento"],sentenceRule:"Ciro vende posibilidades; Luma describe trazos; Var formula reglas exactas.",forbiddenPhrases:["Soy un entrenador","Qué gran combate","Este Pokémon es muy fuerte","Según la Pokédex","Debes derrotarme"]},
 npcs:[
 P("Ciro Reverso","trchar007","mercader de cartas","Encontró la carta y construyó un rito alrededor de sus cambios.","Ganó prestigio exponiendo recuerdos que no le pertenecían.","Conservar el valor cultural sin seguir comerciando intimidad.","Descubrir que la carta nunca lo eligió como dueño.","Ofrece tres posibilidades antes de decir el precio real.",["Puede ser reliquia, espejo o fraude. Las tres opciones cuestan distinto.","La carta mostró a mi primer compañero y cobré entrada para no mirarlo solo.","No vendo la imagen; vendo el turno. Eso no lo vuelve mejor."],["La funda se está opacando. La carta también puede negarse.","No anuncies la especie; deja que su portador lo haga."],["Cerraré la mesa pública y devolveré cada copia.","Mi prestigio sobrevivirá o aprenderá a no hacerlo.","La carta nunca fue mía. Yo solo tenía la caja."],["Una carta rara atrae coleccionistas; una culpable atrae público.","El reverso no oculta: promete esperar." ]),
 P("Luma Trazo","trchar008","ilustradora y restauradora","Estudia pigmentos que reaccionan a recuerdos.","Copió una imagen privada para demostrar el fenómeno.","Crear un método de consentimiento antes de cada lectura.","Que destruir la carta borre también una posibilidad de reconciliación.","Nombra colores donde otros nombran emociones.",["El azul aparece antes de la tristeza; no son la misma cosa.","Copié una línea del borde y apareció una despedida que no era mía.","La tinta espera contacto, pero esperar no significa tener permiso."],["El dorado está retrocediendo. Su portador quiere cerrar la lectura.","No completes ese trazo; pertenece a una respuesta no dada."],["Usaremos fundas que solo se abren con dos firmas.","Destruí mi copia y conservé el registro del error.","La ilustración puede ayudar si también sabe detenerse."],["Los pigmentos honestos cambian bajo distinta luz.","Una restauración no debe inventar lo que falta." ]),
 P("Var Regla","trchar028","juez del duelo ritual","Certifica lecturas como si fueran resultados de torneo.","Su neutralidad convirtió coerción en procedimiento.","Redactar una regla que permita retirarse sin inferencias.","Que admitir parcialidad destruya confianza en todos sus fallos.","Habla en artículos y excepciones.",["Artículo uno: tocar la carta inicia lectura. Falta un artículo sobre detenerla.","Declaré voluntario un rito donde negarse parecía confesión.","La neutralidad no corrige una mesa inclinada."],["Excepción inmediata: el silencio no será interpretado.","Suspendo el duelo hasta que la carta acepte también ser guardada."],["Nueva regla: retirarse no crea evidencia.","Mis fallos anteriores serán revisados por sus participantes.","Un juez puede conservar autoridad después de limitarla."],["Las reglas claras también pueden proteger una injusticia clara.","Toda excepción revela a quién olvidó el artículo." ])
 ],
 battle:{trainerName:"Barajadora Lunar",trainerType:"PSYCHIC_F",sprite:"trchar069",storyToldByTeam:"Seis iconos familiares aparecen como recuerdos personales, no como cartas de mayor rareza.",counterplayHint:"El equipo cubre muchos tipos pero no usa condiciones ocultas; leer el orden y conservar objetos permite adaptar la estrategia.",canLose:true,bagAllowed:true,doubleBattle:false,team:[T("VENUSAUR",92,"cuidado que siguió creciendo",["GIGADRAIN","SLUDGEBOMB","SLEEPPOWDER","SYNTHESIS"],"LEFTOVERS"),T("CHARIZARD",93,"orgullo después de la despedida",["FLAMETHROWER","AIRSLASH","DRAGONPULSE","ROOST"],"LIFEORB"),T("BLASTOISE",94,"protección confundida con distancia",["SURF","ICEBEAM","FLASHCANNON","PROTECT"],"LEFTOVERS"),T("PIKACHU",95,"el recuerdo más inmediato",["THUNDERBOLT","GRASSKNOT","BRICKBREAK","QUICKATTACK"],"FOCUSSASH"),T("MEWTWO",97,"la imagen creada por expectativas ajenas",["PSYCHIC","AURASPHERE","SHADOWBALL","RECOVER"],"LIFEORB"),T("MEW",98,"la respuesta que conserva posibilidades",["PSYCHIC","ENERGYBALL","DAZZLINGGLEAM","PROTECT"],"LEFTOVERS")]},
 decision:{question:"¿Qué futuro merece la carta?",options:["Lecturas privadas con consentimiento","Desarmar el ritual público"],immediateDifferences:["Luma crea una funda de doble firma.","Var cierra la mesa y devuelve ilustraciones."],laterDifferences:["La carta ayuda en reconciliaciones solicitadas.","Las imágenes consentidas forman un archivo sin objeto central." ]},reward:{item:"REVEALGLASS",narrativeToken:"Sello del Reverso",globalEffect:"Atlas reconoce el derecho a no revelar un recuerdo.",futurePayoff:"El Archivo Final pregunta antes de mostrar escenas personales.",whyMeaningful:"El Espejo Veraz deja de imponer una verdad y se usa solo tras consentimiento."},flag:717,
 steps:["Ciro ofrece la carta y esta cambia de ilustración.","Luma demuestra que una copia conserva memoria ajena.","Var intenta iniciar el duelo por procedimiento.","El jugador decide lectura consentida o fin del ritual.","La baraja materializa a la Barajadora Lunar.","El combate usa reglas visibles y Mochila disponible.","Var redacta el derecho de retirada y activa el sello.","La carta vuelve a su reverso y el mar deja de reflejar texto." ]
}
];
function build(d,index){return{mapId:d.id,tier:1,title:d.title,oneSentencePromise:d.promise,biome:{identity:d.identity,visualStorytelling:d.visual,ambientChanges:d.ambient,assetManifest:[...new Map(d.npcs.map(n=>[n.sprite,{type:"character",id:n.sprite,exists:true}])).values()]},narrative:d.narrative,voiceProfile:d.voice,npcs:d.npcs,battle:d.battle,cutscene:{trigger:d.steps[0],steps:d.steps.map((action,i)=>({order:i+1,eventCommand:i===3?"Show Choices":i===5?"Trainer Battle canLose":"RMXP event command",actor:i===3?"Jugador":i===5?d.battle.trainerName:"Escena",action,stateChange:i===6?`switch${d.flag}=true`:i===7?"map_state=resolved":null})),decision:d.decision,failurePath:"La derrota devuelve al jugador al punto de curación; no cambia la decisión ni bloquea la salida.",reentryPath:"La escena omite su introducción y permite repetir únicamente la prueba pendiente."},reward:d.reward,flags:{globalSwitches:[{id:d.flag,name:`POKEMOD ATLAS SEAL ${String(d.flag-707).padStart(2,"0")}`,setWhen:"Tras resolver la decisión y vencer.",readWhen:"Archivo Final y continuidad sectorial."}],variables:[{id:103,name:"POKEMOD ATLAS NARRATIVE SEALS",operation:"Incrementar una vez, protegido por self-switch A."}],selfSwitches:[{event:"Conductor de escena",letter:"A",purpose:"Bloquear recompensa repetida."},{event:d.npcs[0].name,letter:"B",purpose:"Diálogo posterior."}]},exits:[{destination:1001,condition:"always",purpose:"Retorno incondicional a Puerto Horizonte."}],qaClaims:q};}
const out={batch:3,iteration:1,blueprints:rows.map(build)};fs.writeFileSync(path.join(ROOT,"content","atlas_tier1_blueprints_batch03.json"),JSON.stringify(out,null,2));console.log(`Batch 03 generado: ${out.blueprints.length} blueprints.`);
