#!/usr/bin/env node
/** Diez lotes Tier 2 curados: macrociclos 04 y 05, 25 rutas cada uno. */
import fs from "node:fs";
import path from "node:path";
import { ROOT } from "./lib/fire_ash_registry.mjs";

let npcIndex = 0;
const sentence = (text) => /[.!?…]$/.test(text) ? text : `${text}.`;
const admissions = [
  (error) => `Me precipité: ${error}`,
  (error) => `Tardé en reconocer que ${error}`,
  (error) => `Mi primer registro ocultaba que ${error}`,
  (error) => `Convertí una suposición en regla: ${error}`,
  (error) => `La rutina parecía útil, pero ${error}`,
  (error) => `No comprobé a tiempo que ${error}`,
  (error) => `Confundí rapidez con certeza y ${error}`,
  (error) => `El plano no mostraba que ${error}`,
  (error) => `Mi criterio dejó fuera un dato: ${error}`,
  (error) => `Ahora puedo decirlo sin rodeos: ${error}`,
];
const partnerChecks = [
  (pokemon, name) => `${pokemon} comprobó el cambio junto a ${name}`,
  (pokemon, name) => `${name} repitió la prueba mientras ${pokemon} vigilaba el borde`,
  (pokemon, name) => `${pokemon} ya reconoce la señal acordada con ${name}`,
  (pokemon, name) => `Con ${pokemon}, ${name} recorrió la solución desde el otro extremo`,
  (pokemon, name) => `${name} dejó que ${pokemon} confirmara el resultado sin apurarlo`,
  (pokemon, name) => `${pokemon} encontró estable la nueva ruta de ${name}`,
  (pokemon, name) => `${name} y ${pokemon} verificaron que el cambio puede revertirse`,
  (pokemon, name) => `${pokemon} respondió al nuevo criterio que propuso ${name}`,
  (pokemon, name) => `${name} anotó la reacción de ${pokemon} antes de cerrar el registro`,
  (pokemon, name) => `${pokemon} cruzó la zona corregida sin repetir el problema de ${name}`,
];
function N(name, sprite, role, partnerPokemon, want, error, clue, plan, result, future) {
  const index = npcIndex++;
  return {
    name, sprite, role, partnerPokemon,
    motivation: sentence(`Quiere ${want}`),
    conflict: sentence(`Su error anterior fue que ${error}`),
    dialogue: {
      before: [sentence(clue), sentence(admissions[index % admissions.length](error)), sentence(plan)],
      after: [sentence(result), sentence(partnerChecks[index % partnerChecks.length](partnerPokemon, name)), sentence(future)],
    },
    _plan: sentence(plan), _future: sentence(future),
  };
}
const R = (mapId, title, promise, objective, mechanic, npcs, decision, reward) => ({ mapId, title, promise, objective, mechanic, npcs, decision, reward });

const specs = [
  R(1315,"El Alfabeto que Cambiaba de Polo","Las inscripciones de una casa magnética reordenan sus símbolos cuando Metang pasa cerca y el archivo publica traducciones distintas cada mañana.","Comparar orientación, distancia y secuencia para fijar una lectura que conserve las variantes.",
    ["Lectura polar",["Fotografiar antes de acercar metal.","Anotar el norte de cada lectura.","Guardar variantes sin elegir una como original."],"La puerta y una copia en papel permanecen disponibles."],[
      N("Iria Vector","trchar008","epigrafista magnética","METANG","publicar traducciones que indiquen sus condiciones","leyó cada reordenamiento como una corrección definitiva","Metang gira y la tercera fila responde antes que la primera","separaré texto, orientación y hora en tres columnas","las cuatro lecturas quedaron vinculadas sin borrarse","el archivo exigirá contexto antes de llamar error a una variante"),
      N("Nuno Glifo","NPC 04","conservador de símbolos","UNOWN","proteger signos móviles sin encerrarlos bajo vidrio","pegó las piezas sueltas y detuvo una secuencia que aún comunicaba","Unown forma una pausa donde mi adhesivo dejó una línea continua","usaré marcos removibles y marcas fuera de la piedra","la secuencia vuelve a moverse dentro de límites documentados","los visitantes verán cambio y traducción como capas distintas")],
    ["¿Cómo se mostrará la inscripción?",["Lecturas paralelas con brújula","Secuencia móvil con historial"]],["BINDINGBAND","Mantiene unidas varias lecturas sin inmovilizar la inscripción."]),
  R(1326,"La Casa de los Huesos Repuestos","Una familia reconstruye fósiles con piezas de especies distintas para completar siluetas perfectas y termina ocultando qué fragmentos son auténticos.","Clasificar fragmentos, réplicas y uniones hipotéticas antes de abrir la colección vecinal.",
    ["Mesa de procedencia",["Marcar material antes de ensamblar.","Distinguir ajuste físico e hipótesis.","Permitir desmontar cada unión."],"Ninguna pieza sale de su caja hasta quedar registrada."],[
      N("Olia Estrato","trchar009","preparadora fósil","OMANYTE","mostrar hallazgos incompletos sin restarles valor","rellenó ausencias con fragmentos reales de otra especie","La espiral coincide en color, pero la matriz mineral viene de otra costa","desmontaré cada unión y fotografiaré el contacto","la vitrina distingue fósil, réplica y propuesta de montaje","ninguna ausencia volverá a presentarse como vergüenza"),
      N("Ciro Raíz","NPC 04","paleobotánico doméstico","CRADILY","reconstruir el ambiente sin convertir una planta en decoración genérica","puso hojas modernas junto al fósil y las llamó evidencia","Cradily reconoce la forma, no confirma que creciera en esta sala","etiquetaré analogía y muestra histórica por separado","el diorama explica qué dato sostiene cada planta","la casa conservará preguntas abiertas junto a sus piezas")],
    ["¿Qué ocupará el centro de la colección?",["Fósil incompleto con procedencia","Montaje reversible de hipótesis"]],["GRIPCLAW","Sujeta una reconstrucción para estudiarla sin fingir que la unión es permanente."]),
  R(1333,"El Faro de las Eras Mezcladas","Las lentes de un faro fósil proyectan criaturas de épocas diferentes sobre el mismo horizonte y los navegantes toman la imagen como un mapa histórico exacto.","Calibrar tres lentes y rotular qué proyección es dato, recreación o interferencia.",
    ["Calibración estratigráfica",["Probar una lente por vez.","Comparar la proyección con su muestra.","Apagar toda capa sin procedencia."],"La luz de navegación usa un circuito independiente."],[
      N("Luz Ammon","trchar008","óptica del faro","LANTURN","mantener orientación marina separada de la exhibición fósil","conectó recreación y baliza al mismo obturador","Lanturn mantiene el rumbo aunque la silueta jurásica se desplace","aislaré la baliza y asignaré un color a cada capa museográfica","la luz de navegación ya no hereda sombras del museo","el faro anunciará cuándo una escena es recreada"),
      N("Vera Escarcha","NPC 04","climatóloga fósil","AURORUS","explicar climas antiguos sin proyectarlos sobre el tiempo presente","usó la neblina actual para completar zonas vacías de la reconstrucción","Aurorus enfría la lente y aparece una costa que el fósil nunca registró","mediré temperatura antes de interpretar una forma","las proyecciones muestran el margen de incertidumbre térmica","cada nueva lente tendrá una prueba sin efectos ambientales")],
    ["¿Cómo funcionará la exhibición nocturna?",["Capas fechadas y conmutables","Recreación guiada fuera de la baliza"]],["BIGROOT","Ancla cada imagen a su procedencia en vez de dejarla flotar como certeza."]),
  R(1340,"La Isla que Restauraba Pisadas","En una isla de roca roja, voluntarios profundizan huellas fósiles para que sean visibles y cambian sin querer la forma que pretendían preservar.","Comparar moldes antiguos, erosión y retoques para decidir qué huellas dejar sin intervenir.",
    ["Rastreo de relieve",["Medir profundidad sin limpiar primero.","Comparar moldes y roca actual.","Señalar retoques con material reversible."],"La pasarela evita pisar la superficie durante toda la revisión."],[
      N("Taro Molde","trchar009","técnico de huellas","TYRANTRUM","hacer legible el rastro sin fabricar dedos nuevos","repasó bordes débiles hasta volverlos demasiado simétricos","Tyrantrum apoya tres garras y mi molde restaurado muestra cuatro","retiraré el relleno moderno bajo luz rasante","los bordes originales y añadidos se distinguen al primer vistazo","las visitas aprenderán a leer una huella tenue"),
      N("Ala Risco","NPC 04","guardiana costera","ARCHEOPS","proteger la roca del oleaje sin cubrirla de forma permanente","selló toda la plataforma y atrapó sal bajo la resina","Archeops evita la zona donde la sal cristaliza bajo el brillo","abriré canales de drenaje y usaré cubiertas estacionales","la roca respira y la pasarela conserva distancia","cada tormenta activará inspección antes que otra capa de sellador")],
    ["¿Qué huellas se exhibirán?",["Relieves originales con moldes al lado","Retoques visibles y reversibles"]],["MENTALHERB","Ayuda a abandonar una reconstrucción convincente cuando la evidencia la contradice."]),
  R(1351,"El Mercado que Vendía Rocío","Un pueblo del Mar de Nubes embotella el rocío matinal como si perteneciera al primer puesto que lo recoge y deja jardines sin humedad.","Medir captación, suelo y retorno para repartir agua sin convertir la niebla en propiedad.",
    ["Balance de rocío",["Medir antes de embotellar.","Reservar humedad para raíces y bebederos.","Publicar cuánto vuelve al ciclo local."],"La fuente pública permanece abierta y gratuita."],[
      N("Nela Bruma","trchar008","recolectora de rocío","SWABLU","mantener su oficio sin secar los tejados vivos","premió velocidad y recogió agua antes de que llegara a los canalones comunitarios","Swablu sacude gotas sobre una maceta que mi cubeta dejó seca","limitaré cada techo y esperaré a que el jardín reciba primero","las botellas muestran origen, volumen y agua reservada","el mercado dejará una mañana semanal sin recolección"),
      N("Timo Gota","NPC 04","cuidador de cisternas","DRIZZILE","almacenar excedente sin ocultar pérdidas por evaporación","anotó entrada bruta y llamó reserva a un depósito medio vacío","Drizzile marca una fuga que mi libro contabiliza como venta","mediré entrada, salida y nivel al cierre","la cisterna publica pérdidas y capacidad real","los jardines recibirán excedente antes de cerrar cuentas")],
    ["¿Cómo circulará el rocío?",["Cuota después del jardín","Cisterna común con excedentes"]],["WHITEHERB","Devuelve claridad a un balance que había quedado cubierto por etiquetas comerciales."]),
  R(1358,"El Puente que Pesaba las Nubes","Una ciudad suspendida cierra sus puentes cuando las nubes parecen densas, aunque el riesgo real depende del viento lateral y del hielo sobre las cuerdas.","Cruzar sensores de viento, hielo y visibilidad para evitar cierres arbitrarios.",
    ["Lectura de puente",["Medir cuerda y viento por separado.","Comprobar hielo con una sonda.","Anunciar cierre y alternativa antes de bloquear."],"Un corredor bajo permanece conectado al retorno."],[
      N("Brena Cable","trchar009","inspectora de puentes","SKARMORY","cerrar solo cuando la estructura lo necesita","usó el color de la nube como atajo para decidir riesgo","Skarmory vuela bajo una nube oscura y evita una cuerda transparente de hielo","instalaré sondas en los tensores y publicaré sus lecturas","los cierres citan viento, hielo o daño concreto","cada reapertura exige una inspección desde ambos extremos"),
      N("Garo Planeo","NPC 04","mensajero aéreo","GLISCOR","mantener una alternativa para quienes no pueden esperar al deshielo","ofrecía vuelos sin considerar carga ni miedo a la altura","Gliscor planea con una carta; una caja cambia toda la maniobra","separaré mensajería, acompañamiento y carga pesada","la ruta aérea indica límites y acepta rechazos sin presión","el puente inferior seguirá siendo una opción equivalente")],
    ["¿Qué activará un cierre futuro?",["Umbrales de sensores públicos","Inspección doble con ruta alternativa"]],["POWERHERB","Reserva energía para responder al peligro real, no a la apariencia de una nube."]),
  R(1365,"La Final que Pronosticaba Campeones","Un torneo en las nubes ajusta el marcador según el clima previsto y otorga ventaja a equipos que aún no han entrado al campo.","Separar pronóstico, condiciones reales y puntuación antes de la siguiente ronda.",
    ["Mesa de marcador",["Congelar puntos antes del pronóstico.","Medir el campo al inicio real.","Aplicar cambios iguales y anunciados."],"La salida y el área de descanso quedan fuera del sistema de puntuación."],[
      N("Sena Cúmulo","trchar008","jueza meteorológica","TOGETIC","usar el clima para seguridad sin convertirlo en favoritismo","restó puntos preventivos a quienes parecían menos adaptados","Togetic aterriza con viento fuerte; mi tabla ya había declarado desventaja","moveré el pronóstico al informe de seguridad","el marcador empieza en cero cuando ambos equipos confirman","ninguna predicción volverá a contar como jugada"),
      N("Ruy Tribuna","NPC 04","coordinador de campo","STARAPTOR","adaptar horarios sin premiar reputaciones previas","adelantó a equipos populares para evitar lluvia y alteró descansos","Staraptor ve una franja seca que no pertenece a ningún favorito","sortearé cambios de horario y conservaré pausas completas","las reprogramaciones muestran motivo y nuevo descanso","el público recibirá información sin influir en el orden")],
    ["¿Cómo tratará el torneo el pronóstico?",["Solo como alerta de seguridad","Como causa pública de reprogramación"]],["PUREINCENSE","Limpia el marcador de ventajas añadidas antes de que empiece el encuentro."]),
  R(1376,"El Bosque que Seguía una Aguja de Hierro","Los senderos de un bosque metálico obedecen una brújula atraída por raíces ferruginosas y forman círculos alrededor de los claros.","Trazar una ruta usando sol, hitos y magnetismo local sin arrancar las raíces.",
    ["Triangulación forestal",["Comparar brújula y sombra.","Marcar zonas de desviación.","Confirmar cada hito desde el regreso."],"Las cintas hacia Puerto Horizonte permanecen independientes."],[
      N("Ferro Senda","trchar009","botánico metalúrgico","FERROTHORN","conservar raíces que almacenan hierro y desvían instrumentos","propuso cortar las raíces para corregir la brújula","Ferrothorn orienta sus púas al claro mientras mi aguja mira al tronco","mapearé el campo sin tocar la raíz","las zonas magnéticas figuran como rasgo vivo del bosque","los guías usarán dos referencias antes de girar"),
      N("Sila Copa","NPC 04","guardiana de dosel","SHIFTRY","abrir hitos solares sin talar corredores de sombra","podó copas completas para obtener una línea recta de luz","Shiftry encuentra el sol entre hojas que mi plano llamaba obstáculo","usaré pequeñas ventanas estacionales","los hitos solares aparecen sin romper el dosel continuo","cada poda incluirá fecha de cierre y recuperación")],
    ["¿Qué guiará la ruta principal?",["Hitos solares y mapa magnético","Señales dobles en cada desvío"]],["LUCKINCENSE","Celebra encontrar el camino mediante observación, no por confiar en una aguja afortunada."]),
  R(1383,"La Casa que Afinaba sus Clavos","Una vivienda del Bosque de Hierro vibra con cada tormenta porque sus reparaciones mezclaron metales incompatibles y la familia culpa a los Pokémon del tejado.","Identificar resonancias de pared, clavo y tubería antes de sustituir piezas.",
    ["Prueba de resonancia",["Golpear una pieza por vez.","Registrar metal y frecuencia.","Aislar antes de reemplazar."],"La habitación de salida no participa en la prueba."],[
      N("Mara Remache","trchar008","reparadora doméstica","MAWILE","estabilizar la casa sin expulsar a quienes anidan arriba","atribuyó toda vibración a Mawile y añadió más acero","Mawile está quieta y el clavo de cobre responde al tubo de hierro","retiraré uniones mixtas y pondré juntas aislantes","la pared dejó de transmitir la tormenta a cada cuarto","las futuras reparaciones incluirán material y fecha"),
      N("Kilo Rueda","NPC 04","técnico de poleas","KLINKLANG","mantener contraventanas móviles sin convertirlas en amplificadores","sincronizó todas las poleas y una vibración movía la casa completa","Klinklang desacopla un engranaje y el ruido cae de inmediato","separaré cada ventana con embragues manuales","las contraventanas pueden cerrarse sin arrastrar a las demás","la familia elegirá qué mecanismo automatizar")],
    ["¿Cómo se reparará la estructura?",["Juntas aislantes por habitación","Mecanismos desacoplados y manuales"]],["FULLINCENSE","Invita a detener la casa por partes antes de llenarla con otra reparación apresurada."]),
  R(1390,"La Ciudad que Excavaba sus Cimientos","Una casa urbana baja cada año porque los vecinos extraen hierro del subsuelo para reparar edificios y nadie registra el volumen retirado.","Comparar grietas, extracción y carga para establecer una reserva estructural común.",
    ["Balance de cimientos",["Medir huecos antes de extraer.","Relacionar carga y profundidad.","Reservar material para estabilización."],"Las salidas no pasan sobre las zonas en estudio."],[
      N("Ada Viga","trchar009","ingeniera de cimientos","AGGRON","mantener edificios seguros con menos extracción local","calculó cada casa por separado y trasladó hundimientos a la vecina","Aggron pisa una placa y la grieta aparece dos fachadas más allá","modelaré la manzana como una sola estructura","las cargas y huecos comparten un mapa público","ninguna obra volverá a exportar su riesgo"),
      N("Doro Túnel","NPC 04","minero municipal","EXCADRILL","cerrar galerías sin perder rutas de mantenimiento","rellenó túneles con escombro sin comprobar drenaje","Excadrill oye agua detrás de un cierre que mi informe llamó sólido","abriré drenajes y usaré relleno trazable","las galerías cerradas conservan inspección y flujo de agua","cada tonelada extraída tendrá destino y compensación")],
    ["¿Qué limitará la extracción?",["Reserva estructural por manzana","Cuota ligada a estabilización"]],["ODDINCENSE","Marca que una grieta extraña puede venir de una decisión tomada lejos de ella."]),
  R(1401,"La Costa que Navegaba por Constelaciones Viejas","Los pescadores de un canal estelar siguen estrellas pintadas sobre boyas, aunque el cielo y las corrientes ya cambiaron desde que se trazó la ruta.","Comparar boya, cielo y corriente para actualizar el canal sin borrar su historia.",
    ["Derrota estelar",["Leer la boya como fecha histórica.","Medir corriente actual.","Probar regreso antes de abrir ruta."],"El muelle de retorno permanece iluminado."],[
      N("Neri Carta","trchar008","cartógrafa náutica","STARYU","actualizar rutas sin presentar el pasado como error","repintó boyas antiguas y perdió la fecha de sus constelaciones","Staryu señala una estrella real donde la boya muestra una que ya no asoma","añadiré capas fechadas en vez de cubrir pintura","la carta distingue cielo histórico y navegación actual","cada revisión conservará la ruta que reemplaza"),
      N("Mato Corriente","NPC 04","piloto de canal","MANTINE","abrir un paso seguro para embarcaciones lentas","probó la ruta solo con viento favorable y carga ligera","Mantine deriva al este cuando mi flecha insiste en norte","haré recorridos con dos mareas y tres cargas","el canal publica límites y ventanas reales","ningún barco tendrá que demostrar velocidad para usarlo")],
    ["¿Cómo se actualizarán las boyas?",["Capas de cielo con fecha","Ruta actual junto a hitos históricos"]],["ROSEINCENSE","Conserva el aroma de una tradición sin confundirla con coordenadas presentes."]),
  R(1408,"El Concurso de la Estrella Adicional","Un escenario añade digitalmente una estrella a los trajes que no reflejan suficiente luz y el público vota por un diseño que nadie confeccionó.","Separar iluminación, edición y trabajo físico antes de repetir la exhibición.",
    ["Prueba de escenario",["Ver el traje con luz neutra.","Declarar cada efecto añadido.","Permitir una presentación sin edición."],"Los camerinos y la salida no dependen del marcador."],[
      N("Mina Órbita","trchar009","diseñadora de escenario","MINIOR","usar efectos como acompañamiento y no como autoría oculta","añadió destellos automáticos sin consultar a quienes cosieron los trajes","Minior brilla fuera del foco y mi programa se adjudica el destello","mostraré una leyenda de efectos antes de cada acto","el público distingue tela, luz y edición","cada participante puede apagar la capa digital"),
      N("Pía Marea","NPC 04","coordinadora de vestuario","PRIMARINA","proteger prendas y reconocer el trabajo de taller","clasificó como fallo toda tela que no respondía al filtro azul","Primarina canta y la seda cambia por sonido, no por defecto","probaré cada material bajo su condición prevista","las fichas describen respuesta real y cuidado","el taller firma lo que hizo y puede rechazar una edición")],
    ["¿Cómo se evaluará la próxima exhibición?",["Versión neutra antes de efectos","Voto separado para traje y puesta en escena"]],["WAVEINCENSE","Reconoce una puesta en escena que acompaña el diseño sin apropiárselo."]),
  R(1415,"El Desierto de las Señales Celestes","Un camino seco mueve sus señales para alinearlas con meteoros y deja de indicar pozos, sombra y distancia a quienes viajan de día.","Restituir información terrestre y conservar la observación celeste como capa opcional.",
    ["Doble cartografía",["Fijar agua y distancia al suelo.","Separar noche y día.","Comprobar cada señal desde ambos sentidos."],"Los postes de regreso nunca se mueven."],[
      N("Cala Espina","trchar008","guía de dunas","CACTURNE","mantener hitos útiles durante el calor diurno","giró postes para las noches de meteoros y olvidó devolverlos","Cacturne encuentra el pozo mientras la flecha apunta al último cometa","anclaré la información vital en placas fijas","agua, sombra y distancia vuelven a leerse de día","las noches celestes usarán discos superpuestos"),
      N("Siro Cenit","NPC 04","observador de cielo","SIGILYPH","compartir trayectorias sin gobernar el camino terrestre","trató cada alineación astronómica como prioridad de navegación","Sigilyph repite un círculo hermoso que no conduce a refugio","proyectaré rutas celestes sobre un mapa separado","las observaciones conservan hora y horizonte","ningún fenómeno temporal moverá una salida permanente")],
    ["¿Dónde aparecerán los meteoros?",["Discos nocturnos sobre postes fijos","Mapa celeste en refugios de observación"]],["ROCKINCENSE","Devuelve peso y estabilidad a la información que debe permanecer en tierra."]),
  R(1426,"La Tetera que Silbaba por Toda la Casa","Una vivienda del Páramo Sonoro conecta sus válvulas a un único silbato y nadie distingue agua lista, presión alta o puerta abierta.","Asignar sonidos y señales visuales distintas a tres avisos domésticos.",
    ["Afinación de avisos",["Escuchar una fuente por vez.","Asociar sonido y acción concreta.","Mantener controles manuales."],"La válvula principal queda accesible y sin automatizar."],[
      N("Tila Vapor","trchar009","afinadora doméstica","TYMPOLE","crear avisos reconocibles sin llenar la casa de ruido","dio el mismo tono a situaciones con respuestas opuestas","Tympole responde al silbato de la tetera y también corre hacia la puerta","cambiaré ritmo, volumen y luz según la acción","cada aviso tiene un significado y un botón de prueba","la casa publicará una guía junto a cada control"),
      N("Pol Oolong","NPC 04","cuidador de vajilla","POLTEAGEIST","proteger objetos frágiles sin tratarlos como causa del ruido","culpó a Polteageist y escondió tazas mientras la válvula seguía vibrando","Polteageist permanece quieto y la tubería canta dentro del muro","aislaré la válvula antes de mover otra pieza","la vajilla volvió a su estante y la presión tiene medidor","ningún objeto será apartado sin comprobar la fuente")],
    ["¿Cómo avisará la casa?",["Sonido, luz y acción vinculados","Controles locales por habitación"]],["CHOICEBAND","Obliga a que cada señal elija un significado claro en vez de intentar decirlo todo."]),
  R(1433,"El Puente que Devolvía el Eco Equivocado","Un puente repite las llamadas desde la orilla opuesta y los equipos de rescate corren hacia voces antiguas almacenadas en sus placas.","Distinguir eco presente, grabación estructural y llamada humana antes de movilizar ayuda.",
    ["Triangulación sonora",["Repetir llamada con código nuevo.","Medir retraso y dirección.","Confirmar por una segunda señal."],"La ruta física de retorno sigue abierta aunque falle el audio."],[
      N("Eco Valva","trchar008","acústica de puentes","EXPLOUD","identificar ecos sin silenciar el entorno","guardó muestras en placas activas y creó respuestas involuntarias","Exploud llama dos veces y el puente devuelve una tercera voz de ayer","retiraré muestras y marcaré el retraso natural","las placas ya no reproducen archivos durante una emergencia","cada prueba sonora cerrará su canal al terminar"),
      N("Nora Ala","NPC 04","rescatista de ribera","NOIVERN","responder rápido sin perseguir señales no confirmadas","usó volumen como prueba de cercanía y cruzó hacia el lado opuesto","Noivern oye un pulso débil detrás de la voz más fuerte","pediré código, luz o movimiento antes de desplegar","las llamadas se verifican con dos canales independientes","el protocolo conserva rapidez y un punto de regreso")],
    ["¿Qué confirmará una llamada?",["Código nuevo más dirección","Audio y señal visual independiente"]],["CHOICESPECS","Enfoca la atención en señales verificadas y no en la voz más espectacular."]),
  R(1440,"La Lluvia que Tocaba Todas las Alarmas","Un páramo boscoso amplifica cada gota sobre placas distintas y activa sirenas de crecida incluso cuando el cauce permanece bajo.","Relacionar sonido, nivel de agua y saturación del suelo antes de emitir alertas.",
    ["Partitura de tormenta",["Separar intensidad sonora y caudal.","Leer suelo y cauce.","Ensayar alertas sin bloquear senderos."],"Los refugios mantienen salida manual y señal silenciosa."],[
      N("Cora Trino","trchar009","operadora de alertas","CHATOT","emitir avisos comprensibles sin convertir lluvia en pánico","copió el volumen de Chatot como umbral único de crecida","Chatot grita bajo una chapa seca y el río apenas cambia","cruzaré sonido con nivel y humedad","las alarmas citan qué sensor superó su umbral","la lluvia podrá sonar fuerte sin cerrar todo el páramo"),
      N("Belo Charco","NPC 04","lector de humedales","SEISMITOAD","proteger pasos bajos sin drenar zonas sanas","consideró cualquier vibración de Seismitoad una señal de desborde","Seismitoad canta por territorio donde mi mapa dibuja emergencia","marcaré cantos, saturación y crecida en canales distintos","los pasos se cierran solo con agua o suelo inestable","el humedal conserva sus sonidos cotidianos")],
    ["¿Qué activará la sirena mayor?",["Dos sensores físicos coincidentes","Nivel crítico confirmado en terreno"]],["CHOICESCARF","Permite reaccionar con rapidez después de elegir la señal correcta."]),
  R(1451,"El Piso de las Cometas Prestadas","Una tienda de altura alquila cometas como equipos de rescate y cobra daños cuando el viento obliga a soltarlas para evitar una caída.","Separar juguete, herramienta y material de emergencia antes de la próxima salida.",
    ["Mesa de vuelo",["Clasificar uso y límite de viento.","Ensayar liberación segura.","Registrar desgaste sin culpar al usuario."],"La escalera y el punto de anclaje permanecen libres."],[
      N("Vela Nudo","trchar008","diseñadora de cometas","EMOLGA","construir equipos que puedan soltarse sin penalización","usó el mismo contrato para juego y rescate","Emolga corta el viento y mi cuerda de exhibición intenta retenerlo","añadiré liberadores y etiquetas por uso","las cometas de rescate abren el nudo bajo carga crítica","soltar por seguridad deja de contarse como daño"),
      N("Juno Semilla","NPC 04","probador de corrientes","JUMPLUFF","publicar condiciones reales de vuelo en cada terraza","certificó modelos con una ráfaga promedio y ocultó picos","Jumpluff asciende de golpe donde la ficha promete brisa estable","mediré ráfaga máxima y turbulencia","cada terraza muestra una ventana de uso revisable","los alquileres incluyen una ruta de descenso")],
    ["¿Cómo se prestará una cometa?",["Contrato según uso real","Prueba de liberación antes del vuelo"]],["LEFTOVERS","Recuerda que un equipo seguro deja margen después de cumplir su tarea."]),
  R(1458,"El Gimnasio que Giraba la Gravedad","Ventiladores de un gimnasio insular cambian la dirección de las plataformas y convierten una exhibición en una prueba inesperada de equilibrio.","Fijar fases, señales y salidas antes de volver a activar el circuito.",
    ["Secuencia de plataformas",["Bloquear una fase por vez.","Anunciar dirección antes del movimiento.","Confirmar que todas las salidas siguen accesibles."],"Una pasarela fija rodea el circuito completo."],[
      N("Orbe Nadir","trchar009","técnica de plataformas","CLAYDOL","mostrar cambios de orientación sin sorprender a participantes","vinculó luces decorativas y motores al mismo temporizador","Claydol gira con la luz; la plataforma arranca medio pulso después","separaré espectáculo, aviso y movimiento","cada giro tiene cuenta atrás y parada manual","las fases pueden ensayarse desde la pasarela"),
      N("Eli Ceniza","NPC 04","supervisor de visitantes","ELGYEM","ofrecer rutas comprensibles para distintas tolerancias al movimiento","presentó el circuito móvil como única entrada digna","Elgyem cruza quieto por un borde que mi folleto ni menciona","señalaré la pasarela como recorrido completo","la entrada fija recibe el mismo reconocimiento","nadie tendrá que aceptar mareo para ver el gimnasio")],
    ["¿Cómo se reabrirá el circuito?",["Fases anunciadas y bloqueables","Ruta móvil y pasarela equivalentes"]],["BLACKSLUDGE","Representa una fuerza difícil de ver que debe contenerse antes de mover el terreno."]),
  R(1465,"El Concurso que Medía el Viento en Aplausos","Un certamen insular interpreta cintas agitadas por el público como control aerodinámico y penaliza presentaciones en rincones tranquilos.","Separar corriente, movimiento deliberado y ruido de tribuna antes de puntuar.",
    ["Lectura de cintas",["Medir viento sin público.","Observar un gesto repetible.","Puntuar intención y control por separado."],"Los participantes pueden elegir una zona sin tribuna."],[
      N("Rima Pluma","trchar008","coreógrafa aérea","ORICORIO","hacer visibles decisiones de movimiento sin premiar el ruido","ensayó solo frente a ventiladores y llamó técnica al empuje externo","Oricorio repite el giro cuando la cinta queda quieta","mostraré la secuencia sin viento antes de añadir ambiente","la ficha distingue gesto, equilibrio y corriente","cada participante declara qué efecto forma parte de su acto"),
      N("Tebo Globo","NPC 04","operador de decorados","DRIFLOON","mantener adornos seguros sin convertirlos en medidores","ató globos a la mesa del jurado y sus tirones parecían puntuación","Drifloon sube por una corriente lateral que nadie registró","moveré los globos fuera de la línea de evaluación","el anemómetro ocupa el lugar de los adornos","la tribuna ya no fabrica evidencia con cada aplauso")],
    ["¿Qué verá primero el jurado?",["Rutina sin viento artificial","Medición separada de corriente y control"]],["LIFEORB","Celebra la energía de una presentación sin ocultar el costo real del esfuerzo."]),
  R(1476,"El Centro que Diagnosticaba Profundidad","Un Centro Pokémon flotante asigna tratamiento según cuánto se hunde cada paciente en una cámara de presión, aunque especies ligeras muestran síntomas graves antes.","Separar profundidad tolerada, síntomas y especie sin retrasar la curación.",
    ["Triage de presión",["Preguntar síntomas antes de probar.","Usar cámaras solo con consentimiento.","Mantener curación fuera del experimento."],"La máquina de curación y la salida funcionan siempre."],[
      N("Coral Pulso","trchar009","enfermera de presión","CORSOLA","detectar malestar temprano sin convertirlo en competencia de profundidad","ordenó la fila por metros tolerados y no por síntomas","Corsola palidece en superficie mientras la tabla la llama estable","priorizaré signos, relato y recuperación","la cámara dejó de decidir quién recibe ayuda primero","cada prueba puede detenerse sin perder turno"),
      N("Ren Burbuja","NPC 04","técnico de cámaras","REUNICLUS","calibrar equipos para cuerpos distintos","usó un volumen estándar y comparó resultados incompatibles","Reuniclus ocupa la cámara de otra forma y el sensor interpreta fuga","ajustaré volumen, tiempo y referencia por especie","las lecturas incluyen configuración completa","ningún número viajará sin sus condiciones")],
    ["¿Qué organizará el triage?",["Síntomas y recuperación","Evaluación clínica antes de cámara"]],["FLAMEORB","Advierte que una señal intensa puede revelar un problema sin medir toda su gravedad."]),
  R(1483,"La Llave del Torneo Sumergido","Un cuadro eliminatorio bajo el mar usa pulsos de sonar como resultados y confunde ecos de Wailmer con confirmaciones del árbitro.","Crear códigos distintos para juego, fauna y emergencia antes de continuar la ronda.",
    ["Código de sonar",["Reservar una frecuencia oficial.","Confirmar resultado por canal secundario.","No desplazar fauna para limpiar señales."],"La esclusa de retorno no depende del sonar."],[
      N("Ona Pulso","trchar008","árbitra submarina","WAILMER","registrar resultados sin callar el océano","eligió una frecuencia común porque parecía más audible","Wailmer canta y mi consola anuncia una victoria inexistente","moveré el código oficial y añadiré firma temporal","cada resultado exige pulso y confirmación visual","los cantos naturales quedarán descritos, no bloqueados"),
      N("Clau Pinza","NPC 04","mantenedor de balizas","CLAWITZER","proteger cables sin disparar señales accidentales","usó chorros de prueba cerca del sensor y creó pulsos idénticos","Clawitzer limpia una baliza y el tablero suma otro punto","aislaré mantenimiento y competición","las balizas entran en modo de servicio visible","ninguna reparación volverá a alterar el cuadro")],
    ["¿Cómo se confirmará un resultado?",["Sonar firmado más luz","Dos operadores en canales separados"]],["TOXICORB","Recuerda que una señal contaminada debe aislarse antes de entrar al marcador."]),
  R(1490,"La Fábrica de los Compañeros Temporales","Una fábrica de combates presta Pokémon con biografías inventadas para que cada equipo parezca coherente y los cuidadores dejan de reconocer sus preferencias reales.","Reemplazar perfiles ficticios por fichas de cuidado, consentimiento y observación.",
    ["Ficha de préstamo",["Registrar preferencias observadas.","Separar estrategia y personalidad.","Permitir rechazar un emparejamiento."],"La devolución y el retiro quedan disponibles sin penalización."],[
      N("Pori Clave","trchar009","analista de alquiler","PORYGON2","ofrecer información útil sin escribir personajes sobre los Pokémon","generó historias automáticas a partir de estadísticas","Porygon2 completa un perfil brillante con datos que solo hablan de velocidad","limitaré la ficha a cuidado, movimientos y señales observadas","los perfiles ficticios desaparecieron del mostrador","cada entrenador recibe datos revisables y no una personalidad impuesta"),
      N("Dita Turno","NPC 04","cuidadora de rotaciones","DITTO","respetar descansos y afinidades durante los préstamos","trató la capacidad de imitar como disponibilidad permanente","Ditto conserva otra forma cuando mi horario ya exige una nueva","añadiré pausas y una opción clara de no participar","las rotaciones siguen recuperación y elección","ningún préstamo se renovará por inercia")],
    ["¿Qué contendrá la ficha de alquiler?",["Cuidados y señales observadas","Estrategia separada de preferencias"]],["IRONBALL","Da peso real a un préstamo que antes se sostenía sobre historias ligeras."]),
  R(1501,"Los Hitos que Corrían Tras el Cometa","Una ruta mueve sus mojones para seguir la sombra de un cometa y cada amanecer cambia la distancia escrita hasta el próximo refugio.","Fijar distancias terrestres y conservar la trayectoria celeste como observación temporal.",
    ["Doble escala",["Medir el camino con hitos fijos.","Anotar hora de la sombra.","No mover refugios ni retornos."],"Las balizas de salida permanecen ancladas."],[
      N("Celia Tramo","trchar008","medidora de rutas","CLEFAIRY","devolver distancias confiables sin perder la fiesta del cometa","usó la sombra como regla y reubicó mojones cada noche","Clefairy baila alrededor de una marca que ayer estaba veinte pasos atrás","clavaré hitos terrestres y proyectaré la sombra sobre ellos","las distancias vuelven a coincidir al amanecer","la trayectoria celeste tendrá fecha y no autoridad vial"),
      N("Cosme Cola","NPC 04","cronista del cometa","COSMOG","guardar observaciones sin convertirlas en destino obligatorio","declaró oficial el punto más fotografiado y desvió a todos los viajeros","Cosmog flota lejos del mirador que mi folleto llama centro","abriré varios puntos de observación equivalentes","las crónicas registran posición y condiciones","nadie tendrá que abandonar la ruta para participar")],
    ["¿Dónde aparecerá la trayectoria?",["Proyección sobre hitos fijos","Miradores múltiples con fecha"]],["MACHOBRACE","Refuerza una ruta estable aunque el cielo parezca tirar de ella."]),
  R(1508,"El Palacio que Elegía por su Cometa","Un escenario de estrategia interpreta la dirección del cometa como la jugada favorita del participante y bloquea otras opciones antes de comenzar.","Restaurar todas las elecciones y presentar el augurio como una pista opcional.",
    ["Tablero de alternativas",["Mostrar todas las opciones primero.","Etiquetar el augurio como hipótesis.","Permitir cambiar sin penalización."],"La opción de salir permanece visible en cada turno."],[
      N("Xara Augur","trchar009","lectora de trayectorias","XATU","compartir patrones sin apropiarse de la decisión","programó el tablero para destacar su interpretación hasta ocultar otras jugadas","Xatu mira el oeste y la consola deshabilita tres botones al este","devolveré igual tamaño y acceso a cada opción","el augurio aparece como nota que puede cerrarse","ninguna lectura volverá a convertirse en comando"),
      N("Abo Paso","NPC 04","árbitro de estrategia","ABSOL","advertir riesgos sin declarar una opción incorrecta de antemano","penalizó a quien ignoraba la alerta aunque su jugada fuera válida","Absol se inquieta ante un riesgo; eso no decide quién debe aceptarlo","separaré advertencia, regla y resultado","las jugadas se evalúan por el reglamento publicado","cada alerta incluye una forma de continuar o retirarse")],
    ["¿Cómo aparecerá el augurio?",["Pista cerrable junto al tablero","Consulta voluntaria antes del turno"]],["BLACKBELT","Representa disciplina para elegir con información sin obedecer una señal externa."]),
  R(1515,"La Pirámide de las Habitaciones Fugaces","Las salas de una pirámide cambian de nombre con cada lluvia de meteoros y los mapas de emergencia dejan de coincidir con las puertas.","Asignar identificadores físicos permanentes y conservar los nombres celestes como alias.",
    ["Índice de cámaras",["Numerar estructura y salida.","Separar alias y ubicación.","Probar evacuación sin luz celeste."],"La escalera principal conserva un nombre fijo."],[
      N("Bala Cámara","trchar008","archivera de ruinas","BALTOY","preservar nombres rituales sin poner en riesgo la orientación","sustituyó números por títulos celestes que cambiaban cada temporada","Baltoy gira frente a la Cámara Roja y el mapa ya la llama Cola Norte","restauraré códigos físicos junto a cada alias","todas las puertas coinciden con el plano de emergencia","los nombres rituales conservan fecha y relato"),
      N("Cofa Sello","NPC 04","guardián de accesos","COFAGRIGUS","mantener cámaras protegidas y rutas de salida inequívocas","cerró puertas por alias y bloqueó una salida que había cambiado de nombre","Cofagrigus reconoce el sello físico que mi lista omitía","controlaré acceso por código estable","los cierres nunca afectan escaleras de evacuación","cada guardia recibe plano estructural y glosario ritual")],
    ["¿Cómo se nombrarán las salas?",["Código fijo más alias celeste","Plano estructural y glosario separado"]],["BLACKGLASSES","Ayuda a distinguir una salida estable incluso cuando la ceremonia oscurece los nombres."]),
  // MACRO04_SPECS
  R(1526,"El Camino que se Plegaba al Llover","Las señales de una ruta de papel se pliegan para protegerse de la lluvia y ocultan justo la información necesaria para volver.","Diseñar pliegues que resguarden el material sin esconder destino, distancia ni retorno.",
    ["Prueba de pliegues",["Mojar una muestra fuera de la ruta.","Mantener visible una cara esencial.","Comprobar lectura desde ambos sentidos."],"Las balizas rígidas de regreso permanecen instaladas."],[
      N("Lina Doblez","trchar009","ingeniera de papel","LEAVANNY","crear señales reparables que sigan siendo legibles bajo lluvia","protegió toda la tinta plegándola hacia dentro","Leavanny cierra la hoja y desaparecen destino y distancia al mismo tiempo","reservaré una solapa exterior para la información vital","el pliegue protege detalles y deja visible el regreso","cada patrón tendrá instrucciones de apertura y secado"),
      N("Taro Trazo","NPC 04","pintor de rutas","SMEARGLE","usar tintas resistentes sin volver permanentes los errores","selló indicaciones temporales y dificultó cualquier corrección","Smeargle prueba una tinta lavable que mi barniz habría atrapado","separaré base durable y capa revisable","las señales admiten cambios sin perder su orientación principal","cada corrección conservará fecha y motivo")],
    ["¿Qué parte nunca se plegará?",["Destino y retorno exteriores","Código fijo con detalles desplegables"]],["SILKSCARF","Une flexibilidad y lectura clara sin endurecer el camino de papel."]),
  R(1533,"El Mapa que Hacía Pájaros con la Tormenta","Una estación dobla pronósticos en aves de papel y su vuelo decide qué senderos cerrar, aunque una ráfaga interior altera la dirección.","Separar predicción, demostración y cierre real antes de lanzar otra figura.",
    ["Vuelo de prueba",["Leer el pronóstico antes del pliegue.","Probar viento interior y exterior.","Cerrar solo con medición de terreno."],"La salida y un sendero de baja exposición siguen abiertos."],[
      N("Masi Ala","trchar008","meteoróloga de papel","MASQUERAIN","usar figuras para explicar incertidumbre sin convertirlas en oráculos","trató la dirección del vuelo como confirmación meteorológica","Masquerain bate las alas y el pájaro cambia un pronóstico ya escrito","mostraré varios vuelos como demostración, no como resultado","cada figura lleva rango y fuente del pronóstico","ningún cierre dependerá de una sola trayectoria de papel"),
      N("Dram Nube","NPC 04","narrador de tormentas","DRAMPA","contar alertas comprensibles sin exagerar el peligro","añadió finales dramáticos que borraban las rutas seguras","Drampa descansa bajo una lluvia que mi relato llamó catástrofe","leeré condiciones y alternativas antes de la historia","las alertas terminan con una acción concreta y una salida","la ficción queda anunciada fuera del parte operativo")],
    ["¿Qué función tendrán las aves?",["Visualizar varios pronósticos","Enseñar viento sin autorizar cierres"]],["SHELLBELL","Devuelve una señal clara después de que el viento dispersa el espectáculo."]),
  R(1540,"El Centro de los Formularios Infinitos","Un Centro Pokémon origami exige una hoja distinta por cada síntoma y las fichas plegadas esconden información cuando pasan de recepción a curación.","Reducir el registro a datos clínicos necesarios y una preferencia de contacto.",
    ["Triage desplegable",["Preguntar antes de duplicar datos.","Mantener visible la prioridad clínica.","Guardar preferencias en una sección separada."],"La curación nunca espera a que termine el formulario."],[
      N("Celia Hoja","trchar009","recepcionista clínica","CHANSEY","recibir información útil sin convertir la atención en papeleo","añadió formularios para cada excepción y retrasó la primera evaluación","Chansey ya tomó temperatura mientras mi tercera hoja sigue vacía","haré una ficha breve y módulos solo cuando sean necesarios","la prioridad clínica se lee sin desplegar datos personales","cada módulo puede retirarse al dejar de ser útil"),
      N("Inda Pliegue","NPC 04","enlace de cuidados","INDEEDEE","entregar preferencias al equipo correcto sin exponerlas en la sala","dobló todas las notas juntas y una indicación privada quedó hacia fuera","Indeedee cubre la solapa que mi diseño presentaba como portada","separaré clínica, contacto y comodidad","cada sección tiene acceso y duración definidos","los pacientes deciden qué preferencia conservar")],
    ["¿Cómo será la nueva ficha?",["Núcleo clínico y módulos opcionales","Prioridad visible con datos protegidos"]],["WISEGLASSES","Favorece una lectura cuidadosa sin exigir más páginas de las necesarias."]),
  R(1551,"El Vestido de las Mil Facetas","Un concurso de cristal multiplica un traje mediante espejos y el jurado puntúa reflejos que ocultan costuras, movilidad y trabajo real.","Evaluar la prenda con luz neutra antes de añadir las facetas escénicas.",
    ["Pasarela de facetas",["Mostrar una vuelta sin espejos.","Declarar cada reflejo añadido.","Comprobar movilidad y seguridad."],"Existe una pasarela lateral sin efectos."],[
      N("Gala Prisma","trchar008","modista de concurso","GLAMEOW","hacer visible la construcción sin renunciar al brillo teatral","colocó espejos donde escondían una unión frágil","Glameow roza la falda y una faceta tapa el hilo que necesita arreglo","presentaré primero la prenda bajo luz uniforme","el jurado ve costura, movimiento y luego escenografía","cada espejo tendrá una función declarada"),
      N("Furo Corte","NPC 04","peluquero escénico","FURFROU","coordinar silueta y movimiento sin obligar una forma única","fijó adornos para que coincidieran con reflejos y limitó el giro","Furfrou gira cómodo sin el aro que mi plano llamaba indispensable","probaré adornos removibles durante el ensayo","la silueta cambia sin bloquear movimiento","cada participante conserva la decisión final sobre su aspecto")],
    ["¿Cómo puntuará el jurado?",["Prenda primero, efectos después","Costura, movilidad y escena separadas"]],["MUSCLEBAND","Reconoce el trabajo estructural que sostiene una apariencia brillante."]),
  R(1558,"La Sala de Curación Transparente","Un Centro de cristal vuelve transparentes sus separadores para vigilar mejor y termina exponiendo conversaciones y tratamientos a toda la sala.","Restaurar privacidad sin impedir señales clínicas y rutas de asistencia.",
    ["Diseño de separadores",["Probar visibilidad desde cama y pasillo.","Mantener llamada de ayuda accesible.","Distinguir supervisión y exposición."],"La salida y la estación clínica permanecen despejadas."],[
      N("Crio Panel","trchar009","técnico de mamparas","CRYOGONAL","regular luz y privacidad según cada espacio","usó transparencia total como sinónimo de seguridad","Cryogonal refleja el pasillo y una conversación llega a tres camas","instalaré franjas opacas y ventanas orientadas","las camas conservan contacto clínico sin quedar en exhibición","cada panel puede ajustarse desde ambos lados"),
      N("Tessa Velo","NPC 04","coordinadora de sala","GOTHITELLE","responder a llamadas sin observar continuamente","organizó rondas mirando a través de cada pared","Gothitelle detecta el timbre aunque la cortina esté cerrada","usaré señales de llamada y visitas anunciadas","las rondas comienzan con aviso y permiso cuando es posible","el equipo registra atención, no escenas privadas")],
    ["¿Cómo combinará la sala cuidado y privacidad?",["Mamparas ajustables con timbre","Rondas anunciadas y ventanas clínicas"]],["AMULETCOIN","Recuerda que algo valioso puede protegerse sin colocarlo a la vista."]),
  R(1565,"La Ruta de Hielo que Guardaba Pasos","Un sendero cristalino conserva huellas antiguas bajo el hielo y los guías las siguen aunque terminen en grietas nuevas.","Distinguir memoria congelada, paso reciente y ruta segura.",
    ["Lectura de huellas",["Fechar por capa y escarcha.","Sondear hielo antes de seguir.","Marcar desvíos sin borrar rastros antiguos."],"Una cuerda continua conecta refugio y retorno."],[
      N("Glacia Rastro","trchar008","guía de hielo","GLACEON","mostrar huellas históricas sin usarlas como instrucciones actuales","tomó nitidez como prueba de que un rastro era reciente","Glaceon deja polvo nuevo sobre una marca nítida atrapada mucho más abajo","señalaré capa, fecha estimada y estado del hielo","las huellas antiguas se observan desde una pasarela","ninguna memoria volverá a decidir un cruce"),
      N("Bero Sonda","NPC 04","inspector de grietas","BEARTIC","abrir rutas solo después de medir espesor y tensión","confió en el peso de Beartic como prueba para todos los viajeros","Beartic cruza una placa que vibra bajo pasos más rápidos","usaré sonda, temperatura y ruta de retorno","los límites publicados incluyen condición y hora","cada cambio de clima activa una revisión real")],
    ["¿Cómo se señalará el sendero?",["Ruta actual sobre pasarela","Huellas históricas y desvío separado"]],["SMOKEBALL","Permite retirarse de una ruta engañosa sin tener que borrar las huellas que conserva."]),
  R(1576,"El Estadio que Sembraba Rivales","Una llanura meteoro asigna oponentes según parecidos calculados y evita encuentros inesperados que podrían revelar estilos distintos.","Abrir el cuadro de emparejamientos y permitir criterios revisables antes de competir.",
    ["Sorteo de constelaciones",["Publicar variables del emparejamiento.","Ofrecer sorteo neutral.","Permitir rechazar una categoría errónea."],"La retirada no altera historial ni recompensa previa."],[
      N("Meta Órbita","trchar009","analista de cuadros","METAGROSS","crear cruces justos sin convertir similitud en destino","usó un modelo opaco que repetía los mismos rivales","Metagross encuentra una coincidencia matemática donde los estilos no se parecen","publicaré criterios y margen de azar","el cuadro muestra por qué y cómo se formó cada cruce","los participantes pueden impugnar una clasificación"),
      N("Fali Fila","NPC 04","capitana de equipos","FALINKS","mantener orden sin fijar identidades competitivas","trató la posición del grupo como rol permanente","Falinks cambia formación y mi registro insiste en una única función","registraré estrategia por encuentro, no como etiqueta personal","los roles pueden cambiar antes de cada ronda","el historial describe decisiones y no una esencia del equipo")],
    ["¿Cómo se formará el siguiente cuadro?",["Criterios públicos con azar","Sorteo neutral y revisión posterior"]],["EVERSTONE","Sirve como recordatorio de que estabilidad elegida no debe convertirse en identidad impuesta."]),
  R(1583,"La Danza del Polvo Meteórico","Un concurso usa polvo brillante caído del cielo y confunde la reacción alérgica de los participantes con falta de preparación escénica.","Separar material, respuesta física y valoración artística antes de reabrir la pista.",
    ["Ensayo sin polvo",["Presentar la rutina limpia primero.","Declarar composición y riesgo.","Ofrecer efectos alternativos."],"La salida y una zona sin partículas permanecen abiertas."],[
      N("Duna Ala","trchar008","coreógrafa nocturna","DUSTOX","conservar el efecto celeste sin exigir exposición","normalizó la tos porque también ocurría durante ensayos intensos","Dustox evita el polvo meteórico aunque vuela dentro de otras nubes","retiraré partículas y reconstruiré el ritmo con luz","la rutina conserva su intención sin material suspendido","cada efecto tendrá una alternativa equivalente"),
      N("Clea Brillo","NPC 04","inspectora de materiales","CLEFABLE","informar composición sin arruinar la sorpresa artística","guardó la fórmula como secreto del concurso","Clefable reconoce un mineral que la ficha llama simplemente magia","publicaré ingredientes antes de la inscripción","los participantes eligen con información y sin perder categoría","la sorpresa quedará en la escena, no en el riesgo")],
    ["¿Cómo volverá el brillo a la pista?",["Luz proyectada sin partículas","Material declarado y participación opcional"]],["EVIOLITE","Valora una forma todavía en desarrollo sin exigirle soportar una condición dañina."]),
  R(1590,"La Casa que Ensayaba Impactos","Una vivienda activa alarmas y cierra persianas cada vez que Beeheeyem predice un meteoro, aunque la mayoría se desintegra lejos.","Graduar observación, preparación y evacuación según evidencia actual.",
    ["Escala de impacto",["Separar detección y trayectoria.","Confirmar distancia antes de cerrar.","Mantener una salida manual."],"Las puertas nunca dependen de la alarma automática."],[
      N("Bea Vector","trchar009","observadora de meteoros","BEHEEYEM","compartir predicciones con nivel de confianza","transmitió cada detección como impacto confirmado","Beeheeyem señala una luz alta y mi casa ya baja todas las persianas","publicaré trayectoria, margen y próxima revisión","las alertas indican qué sabemos y qué falta","una observación lejana ya no vaciará la vivienda"),
      N("Bron Cúpula","NPC 04","constructor de refugios","BRONZONG","preparar protección sin convertirla en encierro cotidiano","bloqueó ventanas durante semanas para un evento improbable","Bronzong resuena dentro de una casa más peligrosa por falta de ventilación","instalaré cierres manuales y pruebas breves","el refugio puede activarse sin inutilizar la casa","cada simulacro termina con reapertura comprobada")],
    ["¿Qué activará el refugio?",["Trayectoria confirmada y umbral","Alerta gradual con decisión manual"]],["ASSAULTVEST","Protege frente a un impacto real sin obligar a vivir permanentemente bajo alarma."]),
  R(1601,"El Pueblo que Iluminaba el Coral","Una ciudad coralina copia el brillo de los arrecifes en sus faroles y confunde a especies nocturnas que siguen señales químicas distintas.","Rediseñar iluminación urbana sin imitar llamadas naturales.",
    ["Mapa de luminiscencia",["Observar una noche sin faroles nuevos.","Separar color y patrón.","Reservar corredores oscuros."],"Las balizas humanas apuntan al suelo y al retorno."],[
      N("Shii Lumen","trchar008","micóloga urbana","SHIINOTIC","preservar señales vivas sin convertirlas en decoración pública","copió pulsos de Shiinoitic para atraer visitantes","Shiinotic apaga su copa cuando el farol repite su llamada","cambiaré luz fija, baja y fuera de los corredores vivos","los hongos recuperan patrones distinguibles","la ciudad explicará por qué una zona permanece oscura"),
      N("Cora Rama","NPC 04","restauradora de arrecife","CURSOLA","evitar que la estética coral oculte fragilidad real","instaló réplicas sobre colonias dañadas y dificultó su inspección","Cursola atraviesa un adorno donde el coral vivo necesita espacio","retiraré réplicas y marcaré restauración sin disfraz","las zonas dañadas son visibles y están protegidas","cada adorno futuro tendrá distancia ecológica")],
    ["¿Cómo brillará el pueblo?",["Faroles humanos sin pulsos naturales","Corredores oscuros y luz fija"]],["WEAKNESSPOLICY","Convierte una vulnerabilidad reconocida en una regla de cuidado y no en un motivo para ocultarla."]),
  R(1608,"La Casa que Filtraba el Mar","Una vivienda costera cristaliza toda el agua para volverla transparente y elimina minerales que un vivero coralino necesita.","Separar agua potable, agua de vivero y descarte antes de ajustar los filtros.",
    ["Circuito de filtración",["Medir uso antes de filtrar.","Registrar minerales retirados.","Evitar mezclar retornos."],"El depósito de emergencia conserva una línea independiente."],[
      N("Vera Caudal","trchar009","técnica de agua","VAPOREON","producir agua segura sin tratar todos los usos como iguales","aplicó el filtro potable al vivero y al jardín","Vaporeon bebe una línea limpia mientras los pólipos pierden sales necesarias","separaré circuitos y objetivos de calidad","cada grifo indica uso y composición","los cambios de filtro tendrán una prueba en pequeño"),
      N("Mare Púa","NPC 04","cuidadora de vivero","MAREANIE","recuperar minerales sin devolver contaminantes","añadió sales a ojo después de cada filtrado","Mareanie evita un tanque cuya etiqueta dice restaurado","mediré lote, dosis y respuesta antes de completar","el vivero recibe composición estable y trazable","ningún ajuste volverá a depender del aspecto del agua")],
    ["¿Cómo se dividirá el circuito?",["Líneas según uso","Filtro modular con retorno medido"]],["BLUNDERPOLICY","Premia reconocer una filtración equivocada y corregirla antes de repetirla."]),
  R(1615,"El Gimnasio de las Mareas Pintadas","Un gimnasio coralino pinta niveles de agua sobre las paredes y mantiene pruebas abiertas aunque la marea real supere las marcas decorativas.","Conectar sensores, señalización y evacuación sin borrar la identidad visual del recinto.",
    ["Lectura de nivel",["Comparar pintura y sensor.","Reservar un umbral operativo.","Ensayar salida antes de subir agua."],"Una pasarela seca conduce siempre al exterior."],[
      N("Quin Nivel","trchar008","líder de mantenimiento","QUAGSIRE","hacer legible el agua real sin depender del mural","trató las marcas artísticas como escala calibrada","Quagsire flota sobre la línea azul que el folleto llama máxima","instalaré reglas físicas junto al mural","el nivel operativo se distingue sin cubrir la pintura","cada prueba empieza con lectura y ruta seca"),
      N("Gala Drena","NPC 04","operadora de compuertas","GASTRODON","bajar agua sin vaciar humedales conectados","abrió todas las compuertas ante una alarma y drenó zonas vecinas","Gastrodon sigue humedad hacia un canal que mi plan daba por aislado","separaré drenaje de emergencia y regulación","las compuertas indican destino y caudal","un cierre local no desplazará el problema a otra costa")],
    ["¿Qué gobernará la prueba acuática?",["Sensores con umbrales públicos","Lectura manual antes de cada ronda"]],["THROATSPRAY","Hace que una alerta se oiga con claridad sin reemplazar la medición del agua."]),
  R(1626,"La Ciudad que Alquilaba Sombras","Durante un eclipse, comercios reservan zonas oscuras a quien paga entrada y bloquean calles usadas para descansar del calor.","Distinguir espectáculo, refugio térmico y tránsito público.",
    ["Mapa de penumbra",["Medir temperatura y paso.","Marcar zonas públicas primero.","Evitar vallas que persigan la sombra."],"El corredor de retorno nunca puede reservarse."],[
      N("Mimi Umbral","trchar009","escenógrafa del eclipse","MIMIKYU","crear experiencias oscuras sin apropiarse de la sombra común","cercó un callejón fresco y lo presentó como decorado exclusivo","Mimikyu descansa detrás de una valla que antes no existía","retiraré cierres de tránsito y llevaré el espectáculo a una plaza","las zonas públicas quedan marcadas antes del evento","ninguna sombra móvil volverá a crear propiedad privada"),
      N("Helio Reloj","NPC 04","medidor solar","HELIOPTILE","publicar horarios del eclipse sin convertirlos en turnos de acceso","vendió franjas horarias como si controlara la trayectoria","Helioptile cambia de sitio y mi boleto promete oscuridad exacta","mostraré intervalos y visibilidad estimada","el calendario informa sin garantizar un fenómeno","el descanso térmico permanece abierto todo el día")],
    ["¿Dónde ocurrirá la celebración?",["Plaza escénica sin cerrar calles","Recorrido público con refugios libres"]],["ADRENALINEORB","Recuerda que la emoción del eclipse no debe expulsar a quien usa la sombra para cuidarse."]),
  R(1633,"La Mina que Cambiaba de Turno con la Luna","Una isla de hierro adelanta turnos durante el eclipse y mezcla cuadrillas que no conocen las mismas rutas de evacuación.","Restaurar relevos, mapas y descansos antes de reabrir galerías.",
    ["Relevo de galería",["Confirmar equipo y mapa.","Completar descanso antes del cambio.","Recorrer la salida con cada cuadrilla."],"La galería de retorno permanece fuera del horario minero."],[
      N("Stela Veta","trchar008","jefa de cuadrilla","STEELIX","adaptar horarios sin saltar la transferencia de seguridad","fusionó dos turnos para aprovechar la penumbra y perdió responsables de zona","Steelix reconoce una voz, pero la lista mezcla tres capataces","cerraré un relevo antes de abrir el siguiente","cada zona tiene responsable, mapa y descanso completos","el eclipse no volverá a acortar una transferencia"),
      N("Dugo Broca","NPC 04","inspector de túneles","DUGTRIO","comprobar rutas con quienes realmente las usarán","firmó mapas desde superficie y omitió un derrumbe reciente","Dugtrio emerge donde mi plano todavía dibuja un corredor libre","recorreré salida y ventilación con cada equipo","los mapas incorporan cierres y fecha de revisión","ninguna firma sustituirá una inspección en terreno")],
    ["¿Cómo se ajustarán los turnos?",["Relevos completos pese al eclipse","Horario estable con pausa de observación"]],["ELECTRICSEED","Guarda energía para un relevo seguro en vez de gastarla siguiendo la oscuridad."]),
  R(1640,"La Ciudad que Apagaba su Calefacción","Una ciudad nevada corta calefacción para observar mejor el eclipse y obliga a hogares vulnerables a elegir entre frío y participación.","Crear zonas de observación sin reducir servicios térmicos esenciales.",
    ["Balance térmico",["Separar luz decorativa y calefacción.","Medir temperatura interior.","Publicar refugios y duración."],"Los centros cálidos y el retorno permanecen activos."],[
      N("Vani Caldera","trchar009","operadora térmica","VANILLUXE","mantener calor esencial mientras baja la contaminación lumínica","conectó calefacción y luces a un corte común","Vanilluxe soporta el frío; la habitación vecina cae bajo el límite seguro","separaré circuitos y prioridades","la calefacción continúa mientras las luces escénicas se apagan","cada corte futuro publicará servicio afectado"),
      N("Dara Ascua","NPC 04","coordinadora de refugios","DARMANITAN","ofrecer observación y abrigo sin jerarquías de acceso","reservó los mejores refugios para paquetes turísticos","Darmanitan calienta una fila que mi lista dejó fuera","abriré centros por capacidad y necesidad térmica","los refugios muestran espacio y ruta accesible","ver el eclipse no exigirá renunciar al cuidado")],
    ["¿Cómo se oscurecerá la ciudad?",["Solo luces no esenciales","Zonas de observación con calor activo"]],["GRASSYSEED","Representa una reserva de cuidado que permanece incluso cuando cambia la luz del cielo."]),
  R(1651,"El Estadio que Jugaba entre Nubes de Vapor","Un estadio cubre errores de escena con vapor y termina ocultando límites, salidas y señales de pausa.","Reducir niebla, marcar bordes y separar efecto artístico de reglamento.",
    ["Ensayo de visibilidad",["Medir desde cada esquina.","Probar señales con vapor máximo.","Mantener una pausa que apague efectos."],"Las salidas usan luz fija y suelo despejado."],[
      N("Cola Brasa","trchar008","técnica de vapor","COALOSSAL","crear atmósfera sin esconder información de seguridad","aumentó densidad cada vez que una marca escénica fallaba","Coalossal desaparece a tres pasos y mi consola llama perfecto al efecto","limitaré densidad y tiempo por zona","las líneas y salidas siguen visibles durante el espectáculo","cada pausa corta vapor antes de cualquier movimiento"),
      N("Cami Válvula","NPC 04","operadora de presión","CAMERUPT","mantener el sistema estable sin compensar fallos con más calor","subió presión para distribuir niebla y forzó válvulas laterales","Camerupt retrocede donde el tubo vibra fuera del rango","reduciré presión y equilibraré conductos","las válvulas publican límite y cierre manual","ninguna escena pedirá superar la capacidad del sistema")],
    ["¿Cómo se usará el vapor?",["Franjas breves fuera de salidas","Efecto apagable con umbral visible"]],["MISTYSEED","Permite entrar en la niebla con una protección nacida de límites claros."]),
  R(1658,"La Liga de los Calentamientos Eternos","Una Liga de vapor mantiene a los equipos calentando mientras espera una señal ceremonial y convierte la preparación en agotamiento.","Fijar tiempos, pausas y confirmación de inicio independientes de la ceremonia.",
    ["Reloj de calentamiento",["Registrar comienzo real.","Limitar cada bloque.","Permitir enfriamiento antes de competir."],"La zona de descanso conserva salida y curación."],[
      N("Centi Ronda","trchar009","preparadora física","CENTISKORCH","calentar lo necesario sin premiar resistencia al agotamiento","reinició el reloj cada vez que la ceremonia se retrasaba","Centiskorch mantiene calor; el equipo humano ya perdió coordinación","cerraré cada bloque aunque no llegue la señal","los calentamientos tienen máximo y recuperación","ningún retraso ceremonial añadirá esfuerzo obligatorio"),
      N("Blaise Fuente","NPC 04","coordinador de hidratación","BLASTOISE","mantener agua y descanso disponibles durante esperas","retiró estaciones al declarar que el combate estaba por comenzar","Blastoise conserva agua mientras mi cartel dice cierre inminente desde hace una hora","mantendré servicio hasta la llamada efectiva","las estaciones cierran solo al entrar al campo","cada retraso reactiva descanso completo")],
    ["¿Qué terminará el calentamiento?",["Tiempo máximo publicado","Confirmación deportiva, no ceremonial"]],["PSYCHICSEED","Protege concentración y descanso frente a una espera que antes no tenía fin."]),
  R(1665,"La Frontera Dibujada con Vapor","Un mapa regional marca fronteras con vapor proyectado y cada corriente cambia qué aldea parece pertenecer a cada lado.","Sustituir límites móviles por acuerdos y rutas verificables sin borrar la instalación artística.",
    ["Cartografía de corrientes",["Mostrar base física antes del vapor.","Registrar acuerdos y pasos.","Separar efecto y administración."],"Todas las rutas de retorno figuran en una capa fija."],[
      N("Kora Nube","trchar008","artista cartográfica","KOFFING","conservar un mapa vivo sin darle autoridad política","presentó corrientes decorativas como límites oficiales","Koffing desplaza una frontera sin que ninguna calle cambie","proyectaré el vapor sobre una base con leyenda explícita","la instalación muestra movimiento sin reasignar hogares","cada función artística comienza con el mapa acordado"),
      N("Pía Posta","NPC 04","enlace de caminos","PIDOVE","mantener pasos abiertos aunque la imagen cambie","movió puestos siguiendo la proyección y cortó rutas cotidianas","Pidove vuelve al mismo tejado que mi puesto declaró extranjero","fijaré servicios por acceso y acuerdo local","los puestos regresan a cruces estables","ninguna corriente volverá a modificar derechos o retorno")],
    ["¿Cómo convivirán mapa y obra?",["Base oficial bajo proyección","Instalación separada de servicios"]],["NORMALGEM","Da valor a la geografía cotidiana que permanece cuando el efecto extraordinario se disipa."]),
  R(1676,"La Casa de las Ventanas Selladas","Un santuario de polen cierra todas sus ventanas para proteger a visitantes alérgicos y concentra fragancias que también causan malestar.","Crear ventilación, zonas de descanso y avisos sin expulsar plantas ni personas.",
    ["Ronda de aire",["Medir polen interior y exterior.","Abrir por sectores.","Mantener una sala de aire filtrado."],"La salida y el refugio filtrado permanecen accesibles."],[
      N("Riba Miel","trchar009","cuidadora de flores","RIBOMBEE","mantener polinización y visitas con exposición informada","selló la casa y concentró polen en una sola sala","Ribombee evita el techo donde mi medidor alcanza el valor más alto","ventilaré por horarios y presión controlada","los niveles se publican por zona y momento","las flores conservan corredores fuera del refugio filtrado"),
      N("Aroma Lino","NPC 04","especialista de fragancias","AROMATISSE","distinguir perfume, polen y ventilación antes de recomendar una estancia","añadió aromas para cubrir aire cargado","Aromatisse reconoce perfume; el sensor sigue marcando partículas","retiraré fragancias durante la medición","los avisos separan olor agradable y calidad de aire","cada visitante puede elegir una ruta sin perfume")],
    ["¿Cómo se ventilará el santuario?",["Sectores con horarios publicados","Corredores florales y refugio filtrado"]],["FIREGEM","Concentra energía en un punto controlado, como la ventilación que debe actuar sin invadir toda la casa."]),
  R(1683,"La Cueva que Confundía Polen con Humo","Sensores de una cueva interpretan esporas iluminadas como incendio y activan corrientes que dispersan aún más partículas.","Distinguir humo, polen y esporas antes de mover aire o evacuar.",
    ["Muestreo de partículas",["Leer composición y temperatura.","Tomar dos muestras distantes.","Ventilar solo hacia una salida segura."],"La ruta de retorno usa señal física y no depende del sensor."],[
      N("Cruz Eco","trchar008","biólogo de cueva","CROBAT","proteger colonias y visitantes con alertas precisas","usó opacidad como única prueba de humo","Crobat cruza una nube fría que mi panel clasifica como fuego","añadiré temperatura y composición a la alarma","las esporas naturales tienen un perfil documentado","una diferencia nueva seguirá activando revisión humana"),
      N("Pera Micelio","NPC 04","micóloga subterránea","PARASECT","evitar corrientes que sequen los lechos de hongos","abrió ventiladores máximos ante cada alerta falsa","Parasect se aferra al suelo cuando el flujo arranca sin calor","regularé dirección y caudal por sector","la ventilación protege la salida sin barrer toda la cueva","cada activación incluye cierre y recuperación")],
    ["¿Qué confirmará un incendio?",["Calor y composición coincidentes","Dos muestras más revisión humana"]],["WATERGEM","Representa una respuesta específica al fuego real, no una reacción automática a cualquier nube."]),
  R(1690,"El Bosque que Numeraba Polinizadores","Un santuario puntúa cada visita floral y termina empujando a Beedrill y Vivillon hacia recorridos artificiales para mejorar estadísticas.","Cambiar el conteo por observación de diversidad, descanso y retorno natural.",
    ["Censo sin carrera",["Observar sin atraer.","Registrar especie y duración.","Dejar zonas sin conteo."],"Los caminos humanos rodean las áreas de descanso."],[
      N("Vivi Mapa","trchar009","observadora de alas","VIVILLON","entender rutas naturales sin convertirlas en circuito","colocó flores cebo en línea para conseguir datos comparables","Vivillon abandona la fila perfecta y vuelve a un claro sin marcador","retiraré cebos y observaré puntos existentes","el mapa muestra variación y zonas no observadas","la ausencia de dato dejará de contarse como fallo"),
      N("Beda Panal","NPC 04","guardiana de colmenas","BEEDRILL","proteger descanso y alimento durante el censo","abrió panales para identificar individuos y alteró sus turnos","Beedrill cambia de guardia cuando mi ficha todavía exige vuelo","contaré desde distancia y por intervalos","los panales quedan fuera del recorrido público","cada censo termina antes de la fase de descanso")],
    ["¿Cómo se observará la polinización?",["Puntos naturales y datos parciales","Intervalos con zonas sin conteo"]],["ELECTRICGEM","Concentra una observación breve sin mantener al bosque bajo estímulo continuo."]),
  R(1701,"La Avenida de los Reflejos Patrocinados","Una ciudad de espejos inserta anuncios en cada reflejo y los peatones dejan de distinguir señales viales de mensajes comerciales.","Reservar superficies, colores y ángulos para orientación pública.",
    ["Auditoría de reflejos",["Mirar desde altura peatonal.","Separar color vial y comercial.","Eliminar destellos hacia cruces."],"La ruta de retorno usa placas mate permanentes."],[
      N("Zora Vidrio","trchar008","diseñadora de fachadas","ZOROARK","crear reflejos artísticos sin suplantar la señalización","usó ilusiones para extender anuncios sobre placas públicas","Zoroark deshace un anuncio y aparece una flecha que llevaba horas oculta","limitaré proyecciones a marcos privados","las señales públicas recuperan contraste y superficie mate","cada efecto se probará desde el cruce real"),
      N("Mimo Paso","NPC 04","coordinador peatonal","MRMIME","hacer legibles límites y cruces para distintos ritmos de marcha","marcó barreras transparentes que solo él sabía representar","Mr. Mime toca un borde que el resto del paso no puede ver","añadiré textura, color y espacio de detención","las barreras visibles terminan antes de cada cruce","ningún gesto privado volverá a sustituir una señal común")],
    ["¿Qué superficies quedarán libres de anuncios?",["Cruces y señales públicas","Corredor mate de orientación"]],["GRASSGEM","Devuelve un color vivo a la orientación sin vender el paisaje reflejado."]),
  R(1708,"La Ruta que Copiaba al Viajero Más Rápido","Espejos de un camino aprenden el ritmo del primer viajero y proyectan instrucciones demasiado veloces para quienes llegan después.","Restablecer señales estáticas y ofrecer ritmos opcionales.",
    ["Prueba de cadencia",["Recorrer lento y rápido.","Mantener instrucciones completas.","Permitir pausar cada secuencia."],"Los mojones físicos indican siempre el regreso."],[
      N("Gira Tempo","trchar009","diseñadora de señales","GIRAFARIG","guiar sin asumir un único ritmo corporal","entrenó el sistema con su propio paso y ocultó frases demasiado pronto","Girafarig se detiene a leer mientras el espejo ya muestra el tercer giro","añadiré control de pausa y texto persistente","cada instrucción espera confirmación o permanece visible","la ruta tendrá modos y no una velocidad correcta"),
      N("Nemi Faro","NPC 04","acompañante de ruta","STANTLER","ofrecer ayuda sin empujar a seguir una proyección","corrió delante para activar espejos y dejó atrás a su grupo","Stantler vuelve por un sendero que mi ayuda había saltado","caminaré al ritmo acordado y activaré solo lo pedido","los acompañamientos empiezan con preferencia y pausa","nadie perderá orientación por aceptar ayuda")],
    ["¿Cómo mostrarán instrucciones los espejos?",["Texto persistente con pausa","Modos de ritmo elegibles"]],["ICEGEM","Conserva una instrucción quieta el tiempo suficiente para ser comprendida."]),
  R(1715,"La Isla que Reflejaba una Leyenda Distinta","Los espejos costeros muestran una criatura diferente a cada visitante y el pueblo intenta elegir una versión oficial para atraer turismo.","Conservar testimonios contradictorios sin convertir uno en propaganda obligatoria.",
    ["Archivo de avistamientos",["Registrar ángulo y condición.","Separar observación e interpretación.","Permitir relato anónimo."],"El muelle y el retorno no atraviesan la exhibición."],[
      N("Mila Escama","trchar008","archivera insular","MILOTIC","guardar belleza y contradicción sin coronar una versión","seleccionó el reflejo más elegante y descartó los demás","Milotic aparece curva en mi espejo y recta en el de la orilla","publicaré condiciones junto a cada relato","el archivo muestra diferencias como información","ningún testimonio perderá lugar por ser menos vendible"),
      N("Inko Giro","NPC 04","guía de mareas","INKAY","explicar inversiones ópticas sin decidir qué vio otra persona","corrigió relatos que no coincidían con su modelo","Inkay invierte la imagen y mi explicación todavía deja un detalle sin resolver","ofreceré hipótesis y una ruta para observar","las visitas conocen ángulo, marea y límites del modelo","la duda permanecerá sin convertirse en engaño")],
    ["¿Cómo se contará la leyenda?",["Testimonios con condiciones","Galería de versiones sin jerarquía"]],["FIGHTINGGEM","Representa la fuerza de sostener versiones distintas sin obligarlas a competir."]),
  R(1726,"La Bahía que Cobraba cada Relámpago","Una ruta costera almacena carga de tormenta y factura a los refugios por la energía que reciben, incluso cuando mantenerlos abiertos es cuestión de seguridad.","Separar red pública de emergencia, almacenamiento y consumo comercial.",
    ["Balance de descarga",["Medir captación y pérdida.","Reservar energía de refugio.","Publicar excedente antes de vender."],"Las puertas, balizas y curación usan una línea prioritaria."],[
      N("Rai Poste","trchar009","técnica de pararrayos","RAICHU","captar tormentas sin convertir la seguridad en producto","conectó toda descarga al medidor comercial","Raichu deriva carga hacia un refugio que mi contrato intenta facturar","separaré red de emergencia y excedente","las balizas reciben energía antes de cualquier venta","cada tormenta publica captación, reserva y pérdida"),
      N("Nectra Cable","NPC 04","guardiana de refugios","MANECTRIC","mantener puertas y comunicación aunque falle el mercado","apagó refugios al superar el presupuesto de una ruta","Manectric enciende una radio que la hoja de costos daba por prescindible","declararé servicios térmicos, puertas y radio como carga prioritaria","los refugios siguen abiertos durante toda alerta","ninguna deuda futura podrá bloquear el retorno")],
    ["¿Cómo se repartirá la carga?",["Reserva pública antes del excedente","Red de refugios independiente"]],["POISONGEM","Advierte que una red útil se vuelve dañina cuando mezcla seguridad y cobro sin límites."]),
  // MACRO05_SPECS
];

if (specs.length !== 50) throw new Error(`Se esperaban 50 rutas y hay ${specs.length}.`);
function compileSpec(spec, globalIndex) {
  const flag = 783 + globalIndex;
  const variable = 179 + globalIndex;
  const [mechanicName, rules, failureSafe] = spec.mechanic;
  const [question, options] = spec.decision;
  const [item, meaning] = spec.reward;
  const npcs = spec.npcs.map(({ _plan, _future, ...npc }) => npc);
  return {
    tier: 2,
    routeBatch: 8 + Math.floor(globalIndex / 5),
    mapId: spec.mapId,
    flag,
    variable,
    title: spec.title,
    promise: spec.promise,
    objective: spec.objective,
    mechanic: { name: mechanicName, rules, failureSafe },
    npcs,
    decision: {
      question,
      options,
      immediate: spec.npcs.map((npc) => npc._plan),
      later: spec.npcs.map((npc) => npc._future),
    },
    reward: { item, meaning },
    progression: { switchId: flag, decisionVariable: variable, freeReturnMapId: 1001 },
    safety: { bagAlwaysAvailable: true, noForcedBattle: true, existingChallengePreserved: true, baseChallengeExpected: globalIndex < 25, freeReturn: true, rewardOnce: true },
  };
}
for (const [offset, macroCycle] of [[0,4],[25,5]]) {
  const blueprints = specs.slice(offset, offset + 25).map((spec, index) => compileSpec(spec, offset + index));
  const output = { version: 1, macroCycle, tier2Batches: 5, blueprints };
  const target = path.join(ROOT, "content", `atlas_tier2_blueprints_macro${String(macroCycle).padStart(2, "0")}.json`);
  fs.writeFileSync(target, `${JSON.stringify(output, null, 2)}\n`);
  console.log(`Tier 2 macrociclo ${String(macroCycle).padStart(2, "0")}: ${blueprints.length} rutas en ${output.tier2Batches} lotes.`);
}
