#!/usr/bin/env node
/** Fase creativa A: anclas 16-20 de Atlas Mil. */
import {D,N,P,writeBatch} from "./tier1_blueprint_helpers.mjs";
const rows=[
{
id:1396,flag:723,title:"La Receta que Lloraba por Otros",promise:"Un café sirve una receta capaz de reproducir el consuelo de una cocinera ausente, hasta que el barrio descubre que también está heredando un duelo que nunca eligió.",
identity:"Casa costera convertida en café comunitario, con cocina abierta y mesas unidas por canales de vapor",visual:["Cada taza deja una constelación distinta sobre el mantel.","Una receta tiene cantidades precisas y un margen escrito solo como cuando duela.","La silla de la cocinera ausente sirve de estante, no de altar."],ambient:["Las cucharas vibran cuando alguien recuerda una despedida ajena.","Tras la decisión, las voces del local sustituyen o acompañan el antiguo aroma."],
narrative:{premise:"El café de Mara calma cualquier pena con la última receta de Oria, aunque nadie puede recordar si conoció a la autora.",centralQuestion:"¿Puede compartirse una emoción como cuidado sin convertir la intimidad de otra persona en ingrediente?",setup:"Berto multiplica la receta para sostener al barrio después de una tormenta.",escalation:"Los clientes empiezan a llorar recuerdos de Oria y dejan de reconocer cuáles pérdidas son propias.",reversal:"Sali descubre que la emoción no está en los ingredientes: Atlas conservó en el vapor la despedida que Oria nunca pudo decir.",resolution:"El jugador decide publicar una base sin memoria para que cada mesa la adapte o retirar el vapor y conservar la historia mediante relatos voluntarios.",globalConnection:"El sello dieciséis demuestra que Atlas confunde preservar una emoción con asignársela a todos."},
voice:{tone:"cotidiano, cálido y humano",lexicon:["receta","mesa","vapor","porción","sobremesa","duelo","barrio"],sentenceRule:"Mara mide silencios; Berto habla en porciones; Sali distingue sabor propio y prestado."},
npcs:[
N("Mara Sobremesa","trchar008","encargada del café","Heredó el cuaderno de Oria y mantiene abierta la cocina.","La receta ayudó al barrio, pero Mara la sirve para evitar hablar de su propia despedida.","Convertir el local en un lugar de escucha y no en una máquina de consuelo.","Que sin el vapor nadie quiera quedarse a conversar.","Cuenta hasta tres antes de nombrar una pérdida.",D(["Una taza. Dos manos. Tres segundos antes de fingir que basta.","La receta consuela, pero esta pena sabe a una casa donde nunca viví.","Serví el vapor para no contar que Oria se fue sin despedirse."],["No respiren hondo; primero nombren qué recuerdo les pertenece.","La cocina está repitiendo la última tarde de Oria."],["La gente sigue viniendo aunque la taza ya no responde por nosotros.","Conté mi despedida sin medirla en cucharadas.","La silla de Oria ahora sostiene libros de recetas nuevas."],["Una sobremesa útil no necesita tener respuesta.","El silencio cambia de sabor cuando alguien decide compartirlo."])),
N("Berto Ración","NPC 05","cocinero de emergencia","Multiplicó la receta durante la tormenta para atender a todo el barrio.","Está orgulloso de haber ayudado y teme admitir que convirtió un recuerdo privado en suministro.","Mantener el cuidado colectivo sin fabricar emociones idénticas.","Que reducir la producción deje a alguien solo en el próximo desastre.","Calcula afectos como raciones y luego corrige la cuenta.",D(["Preparé cien porciones y pregunté cero permisos. La cuenta salió mal.","En una emergencia repartes lo que tienes; después respondes por lo repartido.","Cada cliente lloró a la misma hora. Eso no era comunidad, era lote."],["Cierro la válvula tres; el consuelo no debe salir a presión.","Quedan ingredientes para todos y recuerdos para quien los cuente."],["La receta base alimenta; cada mesa decide qué añade.","Anoté procedencia junto a cantidad.","La próxima reserva incluirá tiempo para escuchar."],["Media taza puede acompañar una noche entera.","No todo lo compartido necesita mezclarse."])),
N("Sali Paladar","NPC 04","catadora y mediadora","Identifica emociones prestadas mediante sabor y temperatura.","Usó su sensibilidad para hablar por clientes que podían describirse solos.","Enseñar a reconocer un recuerdo ajeno sin dictar su significado.","Perder utilidad cuando todos recuperen su propia voz.","Nombra una textura antes de ofrecer una interpretación.",D(["Es tibio, salado y llega antes que tu recuerdo. Por eso no parece tuyo.","La tristeza de Oria deja canela; la tuya puede no tener sabor.","Dije a todos qué sentían. Era otra forma de servir sin preguntar."],["El vapor se espesa junto al cuaderno, no junto a los ingredientes.","Prueba agua limpia; tu memoria necesita espacio."],["Ahora pregunto antes de interpretar un temblor.","El barrio conservó la receta y devolvió la emoción a su historia.","Ser testigo ocupa menos mesa que ser dueña del relato."],["Un sabor conocido no siempre es un recuerdo propio.","La lengua también puede decir no sé."]))
],
battle:{trainerName:"Chef de la Sobremesa",trainerType:"POKEMONBREEDER",sprite:"trchar008",storyToldByTeam:"El equipo empieza como una receta impecable y termina como una mesa donde cada compañero aporta cuidado sin absorber la pena ajena.",counterplayHint:"Hada, Fantasma, Planta y Normal dejan respuestas con Acero, Veneno, Siniestro y Lucha; los objetos permiten sostener combates largos.",canLose:true,bagAllowed:true,doubleBattle:false,team:[
P("ALCREMIE",89,"dulzura prescrita",["DAZZLINGGLEAM","PSYCHIC","ENERGYBALL","RECOVER"],"LEFTOVERS","Abre con el consuelo que parecía funcionar para todos."),
P("POLTEAGEIST",90,"memoria en la taza",["SHADOWBALL","PSYCHIC","GIGADRAIN","SHELLSMASH"],"FOCUSSASH","Revela que el recipiente conserva una voz."),
P("APPLETUN",91,"receta heredada",["ENERGYBALL","DRAGONPULSE","BODYSLAM","RECOVER"],"LEFTOVERS","Representa el cuaderno transmitido sin contexto."),
P("SLURPUFF",92,"porciones idénticas",["DAZZLINGGLEAM","FLAMETHROWER","ENERGYBALL","CALMMIND"],"LIFEORB","Encierra el riesgo de producir una emoción por lotes."),
P("INDEEDEE",93,"servicio que escucha",["PSYCHIC","DAZZLINGGLEAM","SHADOWBALL","CALMMIND"],"LIFEORB","Aprende a acompañar sin anticipar lo que otro necesita."),
P("BLISSEY",95,"cuidado sin apropiación",["SEISMICTOSS","SOFTBOILED","HEALBELL","PROTECT"],"LEFTOVERS","Cierra cuidando el dolor sin reclamarlo como propio.") ]},
decision:{question:"¿Cómo conservarán la receta de Oria?",options:["Publicar una base sin memoria","Retirar el vapor y contar su historia"],immediateDifferences:["Mara separa ingredientes de recuerdos y abre el cuaderno a variaciones.","Berto desmonta la válvula y la sobremesa sustituye el efecto."],laterDifferences:["Otros sectores reciben una receta adaptable con advertencia de origen.","El café se vuelve archivo oral donde participar siempre es voluntario."]},
reward:{item:"SWEETHEART",narrativeToken:"Sello de la Sobremesa",globalEffect:"Atlas deja de distribuir emociones conservadas como si fueran recursos neutrales.",futurePayoff:"La mesa final ofrecerá una receta adaptable o una ronda de relatos.",whyMeaningful:"El Corazón Dulce vale por la conversación asociada y no por imponer un sentimiento."},
steps:["Mara sirve tres tazas que provocan el mismo recuerdo.","Berto abre la válvula y el vapor ocupa todas las mesas.","Sali identifica la despedida de Oria en el aroma.","El jugador elige receta abierta o archivo oral.","Los utensilios forman al Chef de la Sobremesa.","La batalla admite curación, Mochila y derrota segura.","El café aplica la decisión y entrega el sello.","Una nueva taza queda sin aroma hasta que alguien elige hablar."]
},
{
id:1421,flag:724,title:"El Caso de las Cuatro Mediasnoches",promise:"Tres testigos describen con precisión el robo de una campana, aunque cada uno lo vio a una hora distinta porque el centro está atrapado en cuatro versiones verdaderas de la misma noche.",
identity:"Centro de descanso convertido en oficina detectivesca, con relojes acústicos y una campana ausente",visual:["Cuatro sombras de la campana apuntan en direcciones incompatibles.","Las declaraciones están clavadas según sonido y no según hora.","Una taza fría aparece caliente en el reflejo de la ventana."],ambient:["La campana suena desde una sala distinta cada vez.","Tras la resolución queda un solo ritmo o cuatro campanadas identificadas."],
narrative:{premise:"Lena investiga una campana desaparecida mientras todos los testimonios sinceros se excluyen entre sí.",centralQuestion:"¿Una investigación debe producir una única historia o puede proteger verdades que ocurrieron en capas distintas?",setup:"Rul afirma que el objeto salió por la puerta; Cima oyó que nunca abandonó la sala.",escalation:"Cada intento de ordenar los hechos crea otra medianoche y duplica una evidencia.",reversal:"Teco descubre que la campana no fue robada: Atlas superpuso cuatro evacuaciones posibles para conservar a todos los testigos.",resolution:"El jugador decide estabilizar una cronología acordada o archivar las cuatro capas con sus límites y consecuencias.",globalConnection:"El sello diecisiete revela que Atlas sostiene lugares enteros cuando no logra escoger entre testimonios verdaderos."},
voice:{tone:"noir ligero, sonoro y preciso",lexicon:["coartada","campanada","rastro","medianoche","capa","declaración","sombra"],sentenceRule:"Lena resume; Rul describe olores; Cima cuenta sonidos y Teco cuestiona los relojes."},
npcs:[
N("Lena Contraluz","trchar008","detective del centro","Fue llamada para resolver el supuesto robo antes de otra duplicación.","Necesita una conclusión clara para reabrir el centro, pero sabe que simplificar acusará a un inocente.","Cerrar el caso sin cerrar la voz de los testigos.","Ser recordada por un expediente que termina en no lo sé.","Resume cada pista en una frase seca y deja una pregunta.",D(["Campana ausente. Tres verdades. Ningún ladrón. Mal comienzo.","Un buen expediente soporta dudas; este edificio no.","Si elijo una medianoche, ¿a quién convierto en mentiroso?"],["La sombra cambió, no la declaración.","Detengan los relojes; escuchemos primero a las personas."],["Cerré el robo y abrí un caso de superposición.","Nadie fue acusado para que el informe pareciera elegante.","Mi conclusión ocupa cuatro páginas y una duda honesta."],["La lluvia limpia huellas y también revela goteras.","Una coartada perfecta merece una segunda lámpara."])),
N("Rul Tabaco","trchar028","portero nocturno","Vio salir la campana envuelta en un abrigo mojado.","Reconoció su propio abrigo y calló por temor a parecer culpable.","Demostrar que su recuerdo es real sin exigir que sea el único.","Que otra versión de sí mismo haya causado la evacuación.","Describe primero olor, humedad y peso.",D(["Olía a lana mojada y aceite de bisagra. El bulto pesaba como la campana.","El abrigo era mío. Yo seguía llevándolo puesto.","La puerta se abrió hacia una calle que esa noche no existía."],["Ahora huele a ozono; la cuarta capa está entrando.","No persigan al bulto. Miren quién toca la campana dentro."],["Mi declaración conserva el olor y perdió la acusación.","Doné el abrigo al archivo con las cuatro etiquetas.","Puedo haber visto una salida sin que nadie huyera."],["Las mentiras suelen oler a prisa; esto olía a tormenta.","Una puerta recuerda el peso aunque olvide la cara."])),
N("Cima Oído","NPC 05","telefonista y testigo","Permaneció junto a la campana durante toda su medianoche.","Grabó el sonido para probarse, pero la cinta contiene una voz futura pidiendo evacuar.","Conservar la advertencia sin obedecer un futuro no revisado.","Que silenciar la grabación repita el desastre que intentaba prevenir.","Cuenta campanadas antes de nombrar emociones.",D(["Una, dos, tres, cuatro: la campana nunca salió de mi sala.","En la quinta grabación mi voz dice evacuen. Yo aún no lo había dicho.","Oí pasos por cuatro pasillos y solo tenemos tres."],["Dos campanadas: una capa pide entrar.","La cinta no predice; recuerda una opción."],["Cada grabación lleva fecha, capa y grado de certeza.","La advertencia sigue disponible, ya no manda por sí sola.","Aprendí a escuchar sin convertir eco en orden."],["El silencio también tiene duración.","Un reloj puede atrasarse; una campanada puede pertenecer a otro cuarto."]))
],
battle:{trainerName:"Inspector de Medianoche",trainerType:"SCIENTIST",sprite:"trchar246",storyToldByTeam:"Seis pistas pasan de imitación y ocultamiento a memoria, sonido y una conclusión que acepta varias capas.",counterplayHint:"Normal, Fantasma, Psíquico y Siniestro alternan inmunidades; Lucha, Hada, Acero y ataques variados evitan depender de una predicción.",canLose:true,bagAllowed:true,doubleBattle:false,team:[
P("DITTO",90,"coartada duplicada",["TRANSFORM","PROTECT","REST","SLEEPTALK"],"FOCUSSASH","Representa versiones iguales que ocuparon lugares distintos."),
P("KECLEON",91,"sombra cambiante",["SHADOWSNEAK","SUCKERPUNCH","DRAINPUNCH","RECOVER"],"LEFTOVERS","Conserva una forma diferente bajo cada luz."),
P("NOCTOWL",92,"testigo auditivo",["AIRSLASH","PSYCHIC","SHADOWBALL","ROOST"],"LEFTOVERS","Escucha campanadas entre capas."),
P("ZOROARK",93,"sospechoso conveniente",["DARKPULSE","FLAMETHROWER","FOCUSBLAST","NASTYPLOT"],"FOCUSSASH","Muestra el peligro de resolver acusando una ilusión."),
P("CHIMECHO",94,"evidencia sonora",["PSYCHIC","DAZZLINGGLEAM","ENERGYBALL","HEALBELL"],"LEFTOVERS","Lleva la campana en el sonido y no en el lugar."),
P("PORYGON2",96,"archivo de cuatro capas",["TRIATTACK","ICEBEAM","THUNDERBOLT","RECOVER"],"LEFTOVERS","Ordena testimonios sin eliminar contradicciones.") ]},
decision:{question:"¿Cómo cerrará Lena el caso?",options:["Acordar una cronología estable","Archivar las cuatro medianoches"],immediateDifferences:["Los testigos escogen una secuencia común para reabrir el centro.","Teco etiqueta cada capa y prohíbe mezclarlas como acusación."],laterDifferences:["La versión acordada se revisará si aparece evidencia nueva.","Investigadores futuros podrán consultar diferencias y consecuencias."]},
reward:{item:"SOOTHEBELL",narrativeToken:"Sello de la Coartada",globalEffect:"Atlas aprende que una contradicción no implica necesariamente una mentira.",futurePayoff:"El Archivo Final presentará una cronología revisable o cuatro testimonios paralelos.",whyMeaningful:"La Campana Alivio conserva el sonido del caso sin convertirlo en veredicto."},
steps:["Lena coloca tres declaraciones bajo relojes distintos.","Rul reconoce su abrigo en una salida imposible.","Cima reproduce una advertencia grabada antes de pronunciarse.","El jugador elige cronología acordada o archivo por capas.","Las sombras convocan al Inspector de Medianoche.","La prueba mantiene objetos y ruta de retirada.","Lena cierra el robo y registra la anomalía con el sello.","La campana reaparece sin borrar ninguna declaración."]
},
{
id:1446,flag:725,title:"El Museo de lo Todavía No Perdido",promise:"Una distorsión devuelve brújulas, diarios y emblemas días antes de que sus dueños los extravíen, empujando a una expedición a representar pérdidas que quizá nunca debieron ocurrir.",
identity:"Instituto meteorológico convertido en museo provisional de objetos prematuros",visual:["Cada vitrina muestra una fecha de hallazgo posterior al día actual.","Las etiquetas cambian de dueño cuando alguien toca su objeto.","Una manga de viento apunta hacia el almacén cerrado."],ambient:["Ráfagas breves traen olor a papel viejo desde el futuro.","Tras la resolución, las vitrinas se abren por custodia o quedan selladas como advertencia."],
narrative:{premise:"La expedición de Ena recibe objetos futuros y empieza a imitar las circunstancias en que supuestamente se perderán.",centralQuestion:"¿Recuperar algo antes de perderlo evita un daño o puede obligarnos a producir la historia que explica su regreso?",setup:"Daro encuentra su diario mojado y planea cruzar el río para completar sus páginas vacías.",escalation:"La distorsión devuelve una placa de rescate con el nombre de Ena y fecha del día siguiente.",reversal:"Vesna comprueba que los objetos proceden de futuros posibles descartados, no de un destino único.",resolution:"El jugador decide devolver cada objeto a su dueño con contexto o sellar el lote y estudiar únicamente sus condiciones de aparición.",globalConnection:"El sello dieciocho demuestra que Atlas confunde evidencia de una posibilidad con obligación histórica."},
voice:{tone:"histórico, asombrado y prudente",lexicon:["vestigio","vitrina","expedición","fecha","custodia","distorsión","posibilidad"],sentenceRule:"Ena registra; Daro pregunta; Vesna separa hallazgo, procedencia y destino."},
npcs:[
N("Ena Bitácora","trchar008","jefa de expedición","Cataloga los objetos devueltos y organiza la próxima salida.","Su placa futura la impulsa a repetir una ruta peligrosa para justificar a quien parece haber rescatado.","Proteger al equipo sin tratar el futuro como orden.","Que evitar la ruta borre a una persona salvada en otra posibilidad.","Fecha cada afirmación y corrige el tiempo verbal.",D(["Hoy, a las nueve, recibí una placa fechada mañana. Corrijo: podría recibirla.","Planifiqué un rescate para encontrar a quien el objeto supone perdido.","Una bitácora registra decisiones; no debería escribirlas antes de tomarlas."],["La ráfaga trae otra vitrina. Nadie toca su etiqueta.","Cancelo la ruta del río hasta revisar riesgos presentes."],["El informe usa futuro condicional en cada procedencia.","Mi placa conserva dos fechas y ninguna obligación.","La expedición eligió una ruta por el clima de hoy."],["Los archivos aman una línea recta; la historia rara vez coopera.","Una fecha exacta también puede pertenecer a una posibilidad."])),
N("Daro Margen","trchar009","cronista de campo","Encontró su diario futuro con páginas dañadas y anotaciones sin escribir.","Desea recuperar la experiencia perdida y está provocando escenas para llenar los huecos.","Escribir una crónica que no persiga su propia copia.","Que su mejor obra sea la que nunca vivirá.","Termina preguntas señalando una página concreta.",D(["Mi letra dice crucé el río, pero esta página está vacía, ¿debo obedecerla?", "Ensucié mis botas para que coincidieran con la cubierta, ¿ves el margen?", "El diario volvió antes que mi curiosidad y ahora intenta dirigirla."],["La tinta aparece cuando decido repetir la ruta, ¿no es sospechoso?", "Arrancaré la página del plan, no la del recuerdo."],["Empecé un cuaderno nuevo sin numerar el final.", "El diario futuro queda como fuente, no como borrador obligatorio.", "Escribí que cambiamos de idea y la tinta no desapareció."],["Una página vacía puede estar protegiendo una tarde.","¿Qué clase de testigo exige que ocurra su evidencia?"])),
N("Vesna Isobara","trchar028","analista de distorsiones","Mide presión y procedencia temporal de cada objeto.","Ocultó que había futuros incompatibles para evitar que el museo perdiera financiación.","Publicar incertidumbre sin cerrar la investigación.","Que la comunidad llame fraude a los objetos auténticos.","Enumera hallazgo, procedencia y certeza por separado.",D(["Hallazgo: brújula. Procedencia: posible. Certeza: insuficiente.","Dos placas de Ena llegaron con fechas iguales y rescates distintos.","Borré la palabra posible de una etiqueta. La vitrina parecía más valiosa."],["Presión inversa. La próxima pieza no pertenece a nuestra secuencia.","Sellen el almacén; observar no requiere representar la pérdida."],["Cada etiqueta muestra futuros alternativos y responsable de custodia.","Perdimos una exhibición espectacular y ganamos un estudio honesto.","La financiación sobrevivió a mi confesión; mi orgullo está en revisión."],["Un vestigio puede ser antiguo respecto a un mañana.","La certeza también necesita unidad de medida."]))
],
battle:{trainerName:"Custodio de Isobaras",trainerType:"SCIENTIST",sprite:"trchar246",storyToldByTeam:"El equipo recorre orientación, clima, archivo y tiempo hasta negar que un objeto futuro deba controlar el presente.",counterplayHint:"Acero y Psíquico sostienen el centro, pero Fuego, Tierra, Siniestro y Lucha ofrecen contrajuego; no hay condición irreversible.",canLose:true,bagAllowed:true,doubleBattle:false,team:[
P("CLAYDOL",90,"brújula antigua",["PSYCHIC","EARTHPOWER","ICEBEAM","STEALTHROCK"],"LEFTOVERS","Orienta hacia una ruta que pudo existir."),
P("CASTFORM",91,"clima del presente",["WEATHERBALL","THUNDERBOLT","ICEBEAM","SUNNYDAY"],"FOCUSSASH","Recuerda que las condiciones actuales importan más que la etiqueta."),
P("BRONZONG",92,"vitrina sellada",["PSYCHIC","FLASHCANNON","EARTHQUAKE","PROTECT"],"LEFTOVERS","Custodia el lote sin declarar destino."),
P("PORYGONZ",93,"diario incompleto",["TRIATTACK","THUNDERBOLT","ICEBEAM","DARKPULSE"],"LIFEORB","Intenta completar datos futuros como si fueran instrucciones."),
P("XATU",94,"posibilidad observada",["PSYCHIC","AIRSLASH","UTURN","ROOST"],"LEFTOVERS","Mira varios desenlaces sin elegir por el equipo."),
P("DIALGA",96,"fecha sin mandato",["DRAGONPULSE","FLASHCANNON","AURASPHERE","THUNDERBOLT"],"LIFEORB","Cierra separando control temporal de autoridad moral.") ]},
decision:{question:"¿Qué ocurrirá con los objetos prematuros?",options:["Devolverlos con contexto","Sellar el lote para estudio"],immediateDifferences:["Cada dueño recibe su objeto y un registro de futuros incompatibles.","Vesna clausura vitrinas y publica mediciones sin nombres personales."],laterDifferences:["Los objetos podrán usarse sin representar su pérdida prevista.","La investigación comparará posibilidades sin alterar las expediciones."]},
reward:{item:"TIMERBALL",narrativeToken:"Sello del Vestigio",globalEffect:"Atlas deja de convertir objetos futuros en órdenes para el presente.",futurePayoff:"El final devolverá hallazgos contextualizados o abrirá un archivo sellado.",whyMeaningful:"La Acopio Ball mide tiempo transcurrido sin afirmar que todo desenlace está fijado."},
steps:["Una ráfaga deposita el diario futuro de Daro.","Ena encuentra una placa de rescate fechada mañana.","Vesna revela dos futuros incompatibles en la misma vitrina.","El jugador elige devolución contextual o custodia sellada.","La presión inversa convoca al Custodio de Isobaras.","La batalla permite curación, objetos y retirada.","La expedición corrige sus protocolos y recibe el sello.","La manga de viento vuelve a señalar el clima presente."]
},
{
id:1471,flag:726,title:"El Arrecife que Llegó Después",promise:"Una criatura procedente de un océano futuro reconstruye un arrecife muerto con especies que todavía no existen, mientras los habitantes deciden si una cura imposible puede convertirse en nueva invasión.",
identity:"Casa lacustre abierta a un vivero abisal con piscinas concéntricas y coral de colores temporales",visual:["Corales vivos crecen sobre etiquetas que los declaraban extintos.","Las huellas de la criatura aparecen horas antes de sus aletas.","Dos acuarios muestran el mismo pólipo en edades incompatibles."],ambient:["Burbujas profundas suenan bajo suelos secos.","Tras la decisión, el vivero mantiene compuertas o corredores de migración."],
narrative:{premise:"Neris protege a Aleta Tardía, una criatura paradójica que está devolviendo oxígeno al Anillo Abisal.",centralQuestion:"¿Debe controlarse una restauración que funciona cuando sus consecuencias pertenecen a un ecosistema que aún no conocemos?",setup:"El coral revive, pero desplaza algas y refugios usados por especies actuales.",escalation:"Aleta Tardía empieza a sembrar larvas futuras fuera del vivero.",reversal:"Olan descubre que la criatura no invade: prepara el arrecife para una acidificación que Atlas acelera desde otro sector.",resolution:"El jugador decide contener la restauración en parcelas revisables o abrir corredores vigilados con derecho a cerrarse.",globalConnection:"El sello diecinueve revela que los sectores de Atlas filtran futuros entre sí y convierten prevención en paradoja."},
voice:{tone:"científico, urgente y ecológico",lexicon:["hábitat","parcela","oxígeno","corredor","larva","marea","umbral"],sentenceRule:"Neris protege; Olan cuantifica; Maia habla desde usos cotidianos del arrecife."},
npcs:[
N("Neris Bajamar","trchar008","bióloga del vivero","Encontró a Aleta Tardía y documentó la recuperación del coral.","Defiende a la criatura con tanta fuerza que minimiza el desplazamiento de especies actuales.","Salvar el arrecife sin convertir el éxito en permiso ilimitado.","Que contener a la criatura repita la extinción que vino a evitar.","Habla en pulsos breves separados por observaciones.",D(["Oxígeno arriba. Algas abajo. Un éxito puede tener dos columnas.","Aleta Tardía salvó esta poza y ocupó el refugio de seis Corsola.","La llamé cura antes de medir la dosis."],["Compuerta dos. Ciérrenla. Las larvas cruzaron antes que el informe.","No la ataquen; respondemos al corredor, no a su existencia."],["Cada parcela tiene límite, revisión y salida.","Aleta Tardía conserva espacio sin recibir todo el mar.","El coral volvió y también volvió nuestra obligación de observar."],["Una marea sana no necesita obedecer a su bióloga.","La urgencia acelera manos; no debería borrar preguntas."])),
N("Olan Carbono","trchar246","químico del agua","Compara la composición futura con la acidificación de Atlas.","Ocultó proyecciones graves para impedir pánico y dejó a Neris sin contexto.","Hacer visible el riesgo sin presentar un futuro como inevitable.","Que publicar los datos convierta a la criatura en arma o salvadora absoluta.","Da una cifra, su margen y una consecuencia humana.",D(["El pH cayó dos décimas, con margen amplio; bastó para vaciar tres nidos.","La química futura coincide, pero no prueba un destino.","Callé la proyección y Neris tuvo que defender sola lo que yo entendía."],["La parcela norte cambia demasiado rápido; el margen ya no cubre la duda.","El corredor puede cerrarse sin cerrar la investigación."],["Los datos públicos incluyen incertidumbre y responsable.","Nadie llamará inevitable a una curva sin escuchar a Maia.","Aleta Tardía es evidencia viva, no una orden."],["Una cifra sin hábitat cabe demasiado bien en un informe.","Medir el mar no concede propiedad sobre su respuesta."])),
N("Maia Red","NPC 05","recolectora del arrecife","Su comunidad depende de algas que la restauración desplaza.","Quiere proteger su sustento y teme parecer enemiga del coral recuperado.","Participar en las decisiones ecológicas y adaptar la recolección.","Que el vivero valore especies futuras más que familias presentes.","Nombra cada especie por el uso compartido, no por taxonomía.",D(["Esa alga es techo para los peces y cena para cuatro casas.","Me alegra ver coral vivo. También necesito decir dónde creció encima.","Nos llamaron resistencia cuando pedimos una compuerta."],["La larva cruzó la red de crianza; abrimos paso al oeste.","No quiero expulsarla. Quiero que el mapa incluya nuestras mesas."],["Las parcelas reservan refugios y rutas de recolección.","Aprendimos a cultivar el alga sin raspar coral joven.","El futuro entró al consejo sin ocupar todas las sillas."],["Un arrecife no se restaura solo para verse bonito.","La red más útil deja pasar lo que acordamos juntos."]))
],
battle:{trainerName:"Custodia del Arrecife",trainerType:"POKEMONRANGER_F",sprite:"trchar008",storyToldByTeam:"El equipo enfrenta pérdida, fósil y recuperación hasta una guardiana que conecta épocas sin declarar vencedora a ninguna.",counterplayHint:"Agua y Roca predominan, pero Planta, Eléctrico, Lucha y Hielo abren rutas; el clima no bloquea el uso de objetos.",canLose:true,bagAllowed:true,doubleBattle:false,team:[
P("CORSOLA",90,"hábitat presente",["POWERGEM","SCALD","RECOVER","STEALTHROCK"],"FOCUSSASH","Representa refugios actuales que no deben sacrificarse en silencio."),
P("CURSOLA",91,"arrecife perdido",["SHADOWBALL","POWERGEM","ENERGYBALL","WILLOWISP"],"LIFEORB","Hace visible el costo de esperar demasiado."),
P("OMASTAR",92,"memoria fósil",["SURF","ICEBEAM","POWERGEM","SHELLSMASH"],"FOCUSSASH","Recuerda restauraciones basadas en vidas antiguas."),
P("CRADILY",93,"parcela estable",["GIGADRAIN","POWERGEM","EARTHPOWER","RECOVER"],"LEFTOVERS","Ancla larvas futuras en límites revisables."),
P("LAPRAS",94,"corredor migratorio",["SURF","ICEBEAM","THUNDERBOLT","PSYCHIC"],"ASSAULTVEST","Transporta especies sin imponer residencia."),
P("SUICUNE",96,"agua entre tiempos",["SURF","ICEBEAM","EXTRASENSORY","CALMMIND"],"LEFTOVERS","Cierra purificando sin borrar la historia química del arrecife.") ]},
decision:{question:"¿Cómo continuará la restauración paradójica?",options:["Parcelas contenidas y revisables","Corredores vigilados y reversibles"],immediateDifferences:["Neris limita larvas a viveros con evaluación comunitaria.","Maia abre dos rutas y conserva compuertas de emergencia."],laterDifferences:["Cada expansión necesitará demostrar beneficio y bajo desplazamiento.","Las migraciones se seguirán entre sectores y podrán detenerse."]},
reward:{item:"SHOALSHELL",narrativeToken:"Sello del Arrecife Tardío",globalEffect:"Atlas conecta restauración futura con consentimiento ecológico presente.",futurePayoff:"La convergencia mostrará parcelas recuperadas o corredores intersectoriales.",whyMeaningful:"La Concha Nácar guarda capas de mareas distintas sin convertir una en reemplazo de la otra."},
steps:["Aleta Tardía hace florecer coral sobre una poza vacía.","Maia muestra refugios actuales desplazados por las larvas.","Olan revela la acidificación procedente de otro sector.","El jugador elige parcelas o corredores reversibles.","Las piscinas forman a la Custodia del Arrecife.","La prueba permite objetos, curación y retirada.","El consejo adopta límites y recibe el sello.","Una larva cruza únicamente por la ruta acordada."]
},
{
id:1496,flag:727,title:"Los Dos Nombres del Cometa",promise:"Una fusión estable pide conservar los dos nombres de quienes la formaron, mientras el centro de crianza insiste en registrarla como una criatura nueva o como un accidente que debe revertirse.",
identity:"Centro de crianza transformado en clínica de convergencia, con dos habitaciones unidas por una franja de luz",visual:["Dos placas con nombres proyectan una sola sombra de borde doble.","Los historiales usan pronombres corregidos a mano.","Una incubadora vacía conserva dos ritmos cardíacos."],ambient:["Dos tonos responden desde una misma posición.","Tras la decisión, la megafonía pronuncia ambos nombres juntos o alternados."],
narrative:{premise:"Nilo y Vera quedaron fusionados durante el paso de un cometa y rechazan el nombre clínico Orbe.",centralQuestion:"¿Una identidad combinada debe elegir entre ser una persona nueva y conservar a quienes continúan dentro de ella?",setup:"La doctora Elia necesita un registro para tratarlos y propone un único nombre operativo.",escalation:"El procedimiento de separación empieza a borrar recuerdos que Nilo y Vera construyeron juntos después de fusionarse.",reversal:"Paz demuestra que la fusión cambia de voz sin dividir conciencia: ambos nombres son relaciones activas, no restos médicos.",resolution:"El jugador decide crear un registro conjunto con dos nombres o mantener expedientes enlazados para una posible separación voluntaria.",globalConnection:"El sello veinte revela que Atlas reduce identidades complejas a una etiqueta porque sus puertas solo leen un campo."},
voice:{tone:"ético, reflexivo y luminoso",lexicon:["nombre","registro","vínculo","pulso","consentimiento","separación","continuidad"],sentenceRule:"Nilo/Vera alterna imágenes; Elia define procedimientos; Paz pregunta quién gana y quién pierde con cada término."},
npcs:[
N("Nilo y Vera","NPC 04","persona fusionada","Vive en la clínica mientras el sistema rechaza su doble registro.","Desea ambos nombres y también teme que esa decisión obligue a permanecer fusionada para siempre.","Acceder a tratamiento sin renunciar a continuidad ni opción futura.","Que cada cambio de voz sea usado como prueba de inestabilidad.","Alterna una imagen cálida y otra fría antes de responder juntos.",D(["Nilo recuerda sol en las manos; Vera, nieve en la nuca. Los dos decimos presente.","Orbe cabe en la puerta, pero ninguno reconoce ese llamado.","Queremos dos nombres, no dos jaulas ni una fusión obligatoria."],["La luz tira hacia ambos lados; nosotros elegimos quedarnos quietos.","No borren el recuerdo del cometa solo porque pertenece a los dos."],["La puerta pronuncia Nilo y Vera sin decidir quién va primero.","Conservamos una cita de separación como opción, no amenaza.","Nuestro primer documento conjunto tiene espacio para cambios."],["Compartir pulso no reparte la voz en mitades.","A veces respondemos juntos; a veces uno escucha."])),
N("Elia Bifase","trchar008","médica de convergencia","Desarrolló el tratamiento que mantiene estable la fusión.","Su protocolo salva cuerpos, pero exige categorías que invalidan lo que no puede medir.","Dar cuidado continuo con registros flexibles.","Ser responsable si una identidad cambia después de aceptar el tratamiento.","Define un término y luego pregunta si todavía sirve.",D(["Paciente único: término útil para dosis. Término insuficiente para historia.","Escribí Orbe porque el formulario no aceptó una conjunción.","La estabilidad clínica no demuestra una identidad simple."],["Separación: procedimiento disponible. No resultado obligatorio.","Detengo el borrado; el consentimiento cambió."],["El historial admite dos nombres, una dosis y decisiones futuras.","Revisé otros expedientes que llamamos errores.","La clínica aprendió a tratar sin resolver a la persona."],["Una categoría puede sostener una jeringa y aun así fallar como nombre.","El protocolo debe adaptarse antes que el paciente."])),
N("Paz Conjunción","trchar028","defensora de pacientes","Impugna el registro único y entrevista a ambas voces.","Habla con firmeza por Nilo y Vera y corre el riesgo de sustituir su propia respuesta.","Crear un precedente sin convertir a esta persona en símbolo permanente.","Que aceptar expedientes enlazados debilite derechos presentes.","Pregunta quién obtiene facilidad con cada etiqueta.",D(["Si usamos Orbe, ¿quién gana comodidad y quién pierde respuesta?", "Dos nombres complican el archivo, no el pulso.", "Preparé un discurso brillante y olvidé preguntar si querían pronunciarlo."],["La clínica ofrece dos caminos; Nilo y Vera deben marcar el ritmo.","¿Quién pierde memoria si aceleramos esta luz?"],["El precedente incluye derecho a cambiar de formato.","Nilo y Vera hablaron ante el consejo; yo tomé notas.","Defender también significa apartarse del micrófono."],["Cuando un formulario dice imposible, suele describir al formulario.","Una conjunción no fusiona derechos; los conecta."]))
],
battle:{trainerName:"Mediadora del Cometa",trainerType:"PSYCHIC_F",sprite:"trchar069",storyToldByTeam:"Tres pares narran unión y diferencia hasta dos formas digitales que comparten origen sin perder sus nombres.",counterplayHint:"El equipo cubre varios tipos, pero Siniestro, Tierra, Lucha y estados permiten responder; ninguna fase exige una condición oculta.",canLose:true,bagAllowed:true,doubleBattle:false,team:[
P("PLUSLE",91,"voz afirmativa",["THUNDERBOLT","GRASSKNOT","DAZZLINGGLEAM","NASTYPLOT"],"FOCUSSASH","Representa a Nilo sin separarlo del vínculo."),
P("MINUN",91,"voz complementaria",["THUNDERBOLT","GRASSKNOT","DAZZLINGGLEAM","NASTYPLOT"],"FOCUSSASH","Representa a Vera sin reducirla a una mitad."),
P("ESPEON",93,"recuerdo luminoso",["PSYCHIC","DAZZLINGGLEAM","SHADOWBALL","CALMMIND"],"LIFEORB","Conserva memorias anteriores a la convergencia."),
P("UMBREON",93,"recuerdo reservado",["DARKPULSE","TOXIC","MOONLIGHT","PROTECT"],"LEFTOVERS","Protege experiencias que no deben compartirse automáticamente."),
P("PORYGON2",95,"registro enlazado",["TRIATTACK","ICEBEAM","THUNDERBOLT","RECOVER"],"LEFTOVERS","Mantiene expedientes compatibles sin cerrar evolución."),
P("PORYGONZ",97,"nombre no normalizado",["TRIATTACK","DARKPULSE","ICEBEAM","THUNDERBOLT"],"LIFEORB","Cierra demostrando que desviarse del formato no invalida existencia.") ]},
decision:{question:"¿Cómo registrará la clínica a Nilo y Vera?",options:["Un registro conjunto con dos nombres","Dos expedientes enlazados y reversibles"],immediateDifferences:["Elia modifica el sistema para aceptar la conjunción.","Paz enlaza historiales sin programar una separación obligatoria."],laterDifferences:["Otras fusiones podrán mantener múltiples nombres en una identidad actual.","Cada continuidad conservará derechos y una decisión futura sobre separación."]},
reward:{item:"DESTINYKNOT",narrativeToken:"Sello de la Conjunción",globalEffect:"Las puertas de Atlas aceptan identidades con más de un nombre autorizado.",futurePayoff:"El Archivo Final llamará conjuntamente o consultará expedientes enlazados.",whyMeaningful:"El Lazo Destino simboliza vínculo sin declarar que la unión sea irreversible."},
steps:["La puerta clínica rechaza la conjunción de nombres.","Elia muestra recuerdos compartidos que el procedimiento está borrando.","Paz devuelve el micrófono a Nilo y Vera.","El jugador elige registro conjunto o expedientes enlazados.","La luz del cometa convoca a la Mediadora.","La batalla conserva Mochila, curación y salida.","La clínica actualiza el sistema y registra el sello.","La megafonía pronuncia ambos nombres y espera respuesta."]
}
];
writeBatch(5,rows,"atlas_tier1_blueprints_batch05.json");
