#!/usr/bin/env node
/** Fase creativa B: anclas 21-25 de Atlas Mil. */
import {D,N,P,writeBatch} from "./tier1_blueprint_helpers.mjs";
const rows=[
{
id:1521,flag:728,title:"La Central de las Cenizas Vivas",promise:"Una central celebrada por no emitir humo esconde residuos que aprenden rutas de evacuación y piden no ser tratados como contaminación ni como milagro energético.",
identity:"Ruta abierta ocupada por una central plegable, humedales de decantación y cintas de papel indicador",visual:["Las chimeneas limpias apuntan hacia depósitos subterráneos.","Manchas luminosas rodean señales de salida sin cruzarlas.","Las cifras de emisión terminan en la puerta de la planta y omiten el humedal."],ambient:["Un zumbido grave cambia cuando los residuos reciben nombre.","Tras la decisión, las bombas reducen ritmo o alimentan un hábitat vigilado."],
narrative:{premise:"La central de Leda presume de energía limpia mientras sus residuos móviles se concentran bajo el humedal.",centralQuestion:"¿Cómo se repara un daño cuando el residuo ha desarrollado conducta propia y ya no puede reducirse a algo que eliminar?",setup:"Taro encuentra patrones de evacuación en las manchas y exige detener la planta.",escalation:"Las cenizas vivas bloquean una válvula para impedir que nuevos residuos caigan al depósito.",reversal:"Muri demuestra que no atacan: están repitiendo las rutas de trabajadores expuestos para enseñar dónde se ocultó el costo.",resolution:"El jugador decide clausurar la línea y restaurar el humedal o mantener producción mínima mientras se reconoce un hábitat con representación propia.",globalConnection:"El sello veintiuno muestra que Atlas desplaza consecuencias fuera del límite que usa para declarar un sector perfecto."},
voice:{tone:"ecológico, grave y obrero",lexicon:["residuo","turno","válvula","humedal","exposición","línea","reparación"],sentenceRule:"Leda usa balances; Taro habla desde tareas; Muri traduce movimientos sin fingir certeza."},
npcs:[
N("Leda Balance","trchar008","directora de la central","Diseñó el sistema sin humo y firma sus informes ambientales.","Redujo emisiones visibles, pero definió el límite de medición para excluir el depósito.","Asumir reparación sin abandonar a la comunidad que depende de la energía.","Que reconocer a las cenizas convierta años de trabajo en una mentira completa.","Compara entradas y salidas antes de nombrar el costo omitido.",D(["Entra agua, sale energía. Faltaba una columna: quién carga lo restante.","Mi informe termina en la puerta; el daño aprendió a caminar debajo.","Construí una central limpia usando un límite sucio."],["Cierro la válvula principal. El balance puede esperar.","Las manchas protegen la salida que yo omití."],["El nuevo informe incluye humedal, trabajadores y conducta residual.","La energía bajó y la reparación dejó de ser nota al pie.","Mi firma permanece tanto en el logro como en el daño."],["Cero humo no significa cero costo.","Un balance honesto también muestra lo que no puede sumar."])),
N("Taro Guante","trchar009","operario de mantenimiento","Descubrió las cenizas durante un turno de limpieza.","Quiere cerrar todo de inmediato, aunque muchas familias dependen de equipos médicos conectados a la central.","Detener la exposición con una transición segura.","Que una demora pactada parezca complicidad.","Describe cada riesgo mediante una tarea concreta.",D(["Abrí el filtro con guantes dobles; la mancha señaló la ducha de emergencia.","Apagar hoy deja respiradores sin carga. Seguir igual deja otro turno bajo tierra.","No necesito que el residuo sea bonito para escuchar la alarma."],["Bloqueen la cinta tres; nadie baja sin relevo.","La ceniza marcó una fuga con la forma de una mano."],["Cada turno puede detener la línea sin pedir permiso.","Instalamos baterías antes de reducir producción.","Volví al humedal como inspector, no como limpiador invisible."],["Una válvula cerrada a tiempo es una decisión política.","Los guantes protegen piel, no silencian informes."])),
N("Muri Decanta","NPC 04","intérprete del humedal","Estudia la conducta colectiva de las cenizas vivas.","Necesita defenderlas y corre el riesgo de atribuirles una voz que aún no comprende.","Crear representación basada en observación y posibilidad de corregirse.","Que la restauración las destruya o que reconocerlas justifique producir más.","Distingue movimiento observado de significado supuesto.",D(["Observación: rodean la salida. Suposición: recuerdan a quienes no alcanzaron a usarla.","No llamemos nacimiento a cada mancha; eso volvería aceptable fabricar más.","Una conducta merece cautela antes que una historia conveniente."],["Se apartan de la bomba vieja y cubren la nueva.","No traduzco consentimiento; traduzco una negativa consistente."],["El consejo registra patrones y admite incertidumbre.","Nadie producirá cenizas para aumentar la población.","El humedal conserva voz sin quedar convertido en combustible."],["Lo vivo no siempre habla como esperamos.","Una duda bien documentada protege más que una certeza útil."]))
],
battle:{trainerName:"Custodia de Decantación",trainerType:"SCIENTIST",sprite:"trchar246",storyToldByTeam:"El equipo recorre residuo, filtro, energía y conducta emergente hasta una forma que protege el humedal sin alimentar la central.",counterplayHint:"Veneno y Acero ceden ante Tierra, Fuego y Psíquico; cambios defensivos y objetos permiten atravesar su desgaste.",canLose:true,bagAllowed:true,doubleBattle:false,team:[
P("GRIMER",90,"residuo oculto",["SLUDGEBOMB","SHADOWSNEAK","GIGADRAIN","PROTECT"],"FOCUSSASH","Abre con lo que el informe dejó bajo tierra."),
P("WEEZING",91,"filtro incompleto",["SLUDGEBOMB","FLAMETHROWER","THUNDERBOLT","WILLOWISP"],"LEFTOVERS","Representa emisiones desplazadas y no eliminadas."),
P("GARBODOR",92,"depósito acumulado",["GUNKSHOT","DRAINPUNCH","SEEDBOMB","ROCKBLAST"],"LIFEORB","Hace visible el costo agregado de muchos turnos."),
P("MUK",93,"conducta colectiva",["GUNKSHOT","CRUNCH","BRICKBREAK","PROTECT"],"LEFTOVERS","Se organiza para bloquear la válvula que lo produce."),
P("MAGNEZONE",94,"red energética",["THUNDERBOLT","FLASHCANNON","VOLTSWITCH","TRIATTACK"],"ASSAULTVEST","Mantiene servicios críticos durante la transición."),
P("ZYGARDE",96,"equilibrio del humedal",["EARTHQUAKE","DRAGONPULSE","CRUNCH","COIL"],"LEFTOVERS","Cierra defendiendo territorio y límite de producción.") ]},
decision:{question:"¿Cómo reparará la central el daño?",options:["Clausurar la línea y restaurar","Producción mínima con hábitat protegido"],immediateDifferences:["Leda activa baterías de transición y Taro desmantela la línea.","Muri define límites de producción y un consejo independiente del humedal."],laterDifferences:["La zona recuperará agua y empleos de restauración.","La planta quedará bajo revisión continua y sin derecho a fabricar más vida residual."]},
reward:{item:"CELLBATTERY",narrativeToken:"Sello de la Decantación",globalEffect:"Atlas deja de declarar limpio un proceso midiendo solo dentro de sus puertas.",futurePayoff:"La convergencia recibirá energía de transición o un modelo de producción limitada.",whyMeaningful:"La Pila conserva energía para una transición y no como excusa para perpetuar el depósito."},
steps:["Taro abre el filtro y las cenizas dibujan una salida.","Leda muestra el balance que excluye el humedal.","Muri documenta una negativa sin atribuir palabras.","El jugador elige clausura o producción mínima protegida.","Las válvulas convocan a la Custodia de Decantación.","La prueba permite objetos, curación y retirada.","La central aplica la transición y registra el sello.","Las cenizas liberan la válvula cuando cesa el vertido."]
},
{
id:1546,flag:729,title:"La Profecía Escrita Después",promise:"Una facción recluta jóvenes con profecías privadas que siempre aciertan porque sus redactores observan primero la crisis y luego falsifican la fecha del augurio.",
identity:"Sendero devastado convertido en santuario de cristal, imprenta clandestina y sala de testimonios",visual:["Los pergaminos envejecidos conservan tinta fresca bajo el pliegue.","Cada profecía tiene un espacio exacto para insertar un nombre.","Los cristales proyectan consignas solo desde el atril central."],ambient:["Susurros repiten frases con una palabra personal distinta.","Tras la resolución, las prensas se detienen o imprimen métodos y correcciones."],
narrative:{premise:"La Orden del Prisma promete propósito a quienes reciben una profecía escrita aparentemente años antes de conocerlos.",centralQuestion:"¿Cómo se devuelve libertad a alguien cuando la mentira que lo reclutó también le dio comunidad y lenguaje para su dolor?",setup:"Iven encuentra un augurio que describe el accidente de su hermana y acepta una misión de la Orden.",escalation:"Nadia descubre plantillas, entrevistas ocultas y fechas añadidas con polvo de cristal.",reversal:"Sor Elian no predice tragedias: sigue equipos de rescate, recopila vulnerabilidades y publica después un texto retrofechado.",resolution:"El jugador decide convertir la imprenta en archivo público de métodos o desmantelarla y financiar una red independiente de acompañamiento.",globalConnection:"El sello veintidós muestra que Atlas amplifica relatos inevitables porque las personas previsibles estabilizan mejor sus sectores."},
voice:{tone:"persuasivo, inquietante y reparador",lexicon:["consigna","augurio","plantilla","elección","fecha","prisma","acompañamiento"],sentenceRule:"Iven cita y duda; Nadia desmonta recursos retóricos; Elian concede una verdad antes de torcerla."},
npcs:[
N("Iven Renglón","NPC 02","recluta reciente","Busca sentido tras el accidente descrito por su profecía.","Sabe que la Orden lo manipuló, pero allí encontró personas que lo visitaron cuando nadie más lo hizo.","Conservar vínculos sin obedecer la misión fabricada.","Que abandonar el augurio signifique abandonar también a su hermana.","Recita una línea y luego añade lo que el texto omitió.",D(["El cristal dice tu pérdida abrirá una puerta. No dice quién cerró las otras.","La profecía conocía el accidente; Elian había leído el informe de rescate.","Me mintieron sobre el destino y acertaron en que estaba solo."],["La consigna termina aquí. Mi decisión empieza después.","No rompan a quienes siguen dentro; muéstrenles la plantilla."],["Conservo amigos y devuelvo la misión.","Escribí a mi hermana sin convertirla en símbolo.","La nueva red visita antes de ofrecer respuestas."],["Una frase puede sostenerte y aun así llevar firma falsa.","Dudar del augurio no borra lo que sobrevivimos."])),
N("Nadia Margen","trchar008","tipógrafa desertora","Diseñó las plantillas que personalizan cada profecía.","Quiere exponer el fraude, aunque publicar expedientes revelaría secretos de reclutas.","Demostrar el método sin volver a explotar información privada.","Que destruir las pruebas permita a Elian repetir la técnica.","Señala la herramienta persuasiva y su costo.",D(["Aquí va una pérdida concreta; aquí, una misión imposible de refutar.","La tinta es nueva. El polvo solo falsifica la edad.","Guardé pruebas en los mismos expedientes que debo proteger."],["Proyección de autoridad: luz alta, voz baja, nombre al final.","Cubran los datos; basta mostrar la plantilla."],["Publicamos el método con ejemplos consentidos.","Cada recluta puede retirar su expediente.","Mi oficio volvió a imprimir preguntas y fechas reales."],["Una consigna breve deja poco espacio para respirar.","La transparencia no exige exponer a la víctima."])),
N("Elian Prisma","trchar028","redactor de augurios","Fundó la Orden y dirige sus rescates selectivos.","Cree que manipular destino es aceptable porque la comunidad sí ayuda a personas olvidadas.","Mantener la red de apoyo sin conservar control doctrinal.","Que revelar el fraude destruya el único refugio de muchos reclutas.","Admite una necesidad real antes de justificar su dominio.",D(["Es verdad: llegamos cuando nadie fue. Por eso aceptaron la fecha.","No inventé su dolor; inventé que me pertenecía la respuesta.","Una profecía obliga a mirar a quien todos ignoraban."],["El prisma ya no proyecta mi voz; siguen escuchándose entre ellos.","Si me derrotan, protejan primero los dormitorios."],["Entregué fondos y registros a un consejo de antiguos reclutas.","Mis augurios conservarán firma y fecha de redacción.","Ayudar sin ser necesario será mi prueba más difícil."],["Una verdad oportuna puede escoltar una mentira.","El destino fue una marca; la soledad era el producto."]))
],
battle:{trainerName:"Oráculo de Imprenta",trainerType:"PSYCHIC_M",sprite:"trchar028",storyToldByTeam:"El equipo comienza con presagios naturales, pasa por sugestión y termina con conocimiento que revela su propio método.",counterplayHint:"Psíquico y Siniestro permiten respuestas con Bicho, Fantasma, Hada y Acero; no hay bucle de evasión ni condición secreta.",canLose:true,bagAllowed:true,doubleBattle:false,team:[
P("ABSOL",90,"presagio interpretado",["NIGHTSLASH","SUCKERPUNCH","PLAYROUGH","SWORDSDANCE"],"FOCUSSASH","La Orden convierte una advertencia en prueba de autoridad."),
P("XATU",91,"futuro observado",["PSYCHIC","AIRSLASH","UTURN","ROOST"],"LEFTOVERS","Ofrece posibilidades que Elian presenta como inevitables."),
P("MALAMAR",92,"persuasión invertida",["PSYCHOCUT","NIGHTSLASH","SUPERPOWER","HYPNOSIS"],"LIFEORB","Representa la manipulación que parece decisión propia."),
P("GOTHITELLE",93,"plantilla personal",["PSYCHIC","THUNDERBOLT","DARKPULSE","CALMMIND"],"LEFTOVERS","Lee vulnerabilidades y las encierra en una narrativa."),
P("ORANGURU",94,"doctrina aprendida",["PSYCHIC","ENERGYBALL","SHADOWBALL","NASTYPLOT"],"LEFTOVERS","Muestra cómo la comunidad repite una consigna útil."),
P("MEW",96,"posibilidad abierta",["PSYCHIC","ENERGYBALL","DAZZLINGGLEAM","PROTECT"],"LIFEORB","Cierra devolviendo múltiples futuros sin propietario.") ]},
decision:{question:"¿Qué reemplazará a la Orden del Prisma?",options:["Archivo público de métodos","Red de apoyo sin imprenta"],immediateDifferences:["Nadia publica plantillas anonimizadas y derecho de retirada.","Iven transfiere dormitorios y fondos a acompañantes independientes."],laterDifferences:["Otros sectores aprenderán a detectar augurios fabricados.","Las personas recibirán ayuda antes de aceptar cualquier relato de destino."]},
reward:{item:"MENTALHERB",narrativeToken:"Sello de la Consigna Rota",globalEffect:"Atlas deja de premiar decisiones obtenidas mediante inevitabilidad fabricada.",futurePayoff:"El final mostrará herramientas de alfabetización o una red de acompañamiento.",whyMeaningful:"La Hierba Mental representa recuperar criterio sin fingir inmunidad a toda persuasión."},
steps:["Iven recita un augurio fechado antes del accidente.","Nadia revela la plantilla y protege los nombres.","Elian admite haber usado informes de rescate.","El jugador elige archivo público o red independiente.","Los cristales convocan al Oráculo de Imprenta.","La batalla mantiene Mochila, curación y salida.","Los reclutas asumen el lugar y reciben el sello.","El atril proyecta una pregunta en vez de una consigna."]
},
{
id:1571,flag:730,title:"La Ciudad que Pagaba con Recuerdos",promise:"Una reconstrucción vuelve más segura y hermosa la ciudad usando memorias vecinales como planos, pero cada calle terminada deja a sus habitantes sin saber por qué querían regresar.",
identity:"Salón de concursos convertido en asamblea urbana, rodeado por fachadas reconstruidas y solares recordados a medias",visual:["Casas nuevas conservan detalles que sus dueños ya no reconocen.","Los planos incluyen olores, apodos y rutas escolares como materiales.","Una pared vieja permanece en pie porque nadie recuerda haberla donado."],ambient:["Martillos repiten ritmos de canciones olvidadas.","Tras la decisión, la obra conserva imperfecciones o instala estaciones de memoria consentida."],
narrative:{premise:"El arquitecto Jano transforma recuerdos en planos capaces de reconstruir exactamente el barrio perdido.",centralQuestion:"¿Qué significa recuperar un lugar si el proceso consume las razones personales para habitarlo?",setup:"Rema celebra su nueva panadería y no recuerda quién le enseñó la receta.",escalation:"La máquina pide una memoria infantil completa para terminar el hospital.",reversal:"Lua descubre que los recuerdos no alimentan la obra: Atlas los retira para evitar discrepancias entre ciudad real y ciudad ideal.",resolution:"El jugador decide detener la copia exacta y terminar con planos ordinarios o crear un banco revocable que nunca retire el recuerdo original.",globalConnection:"El sello veintitrés revela que Atlas borra contexto humano para que sus reconstrucciones parezcan coherentes."},
voice:{tone:"urbano, resistente y comunitario",lexicon:["barrio","solar","andamio","plano","esquina","memoria","asamblea"],sentenceRule:"Jano dibuja; Rema recuerda mediante trabajo; Lua nombra quién queda fuera del plano."},
npcs:[
N("Jano Andamio","trchar009","arquitecto de reconstrucción","Dirige las obras tras la destrucción del barrio.","Salvó edificios y trató las lagunas de memoria como costo temporal sin preguntarlo.","Terminar viviendas seguras sin convertir biografías en material.","Que detener la máquina deje familias en refugios otro invierno.","Describe emociones como cargas y apoyos estructurales.",D(["Esta esquina soporta tres pisos y un recuerdo que no presupuesté.","Llamé costo temporal a algo que no pensaba devolver.","Una ciudad segura puede derrumbar a quien ya no sabe por qué volvió."],["Retiren la memoria del cimiento; usamos acero real.","El hospital no necesita una infancia para sostener el techo."],["Los planos distinguen testimonio, inspiración y material.","Terminamos menos fachadas y más hogares reconocibles.","Mi firma ya no cubre la del barrio."],["Una grieta visible puede evitar una ruina escondida.","Los andamios también dicen todavía no."])),
N("Rema Harina","NPC 05","panadera y vecina","Reabrió el primer comercio reconstruido.","Entregó recuerdos de su madre y ahora reproduce la receta sin sentir que le pertenece.","Recuperar el vínculo sin exigir que el local vuelva a ser idéntico.","Que demoler un detalle nuevo sea perderla por segunda vez.","Recuerda mediante peso, temperatura y trabajo manual.",D(["Mis manos miden la harina; mi cabeza olvidó quién corrigió la primera masa.","La ventana quedó exacta y no sé por qué lloré al verla.","Quiero mi recuerdo, aunque la panadería cambie de color."],["La masa pesa distinto cuando la máquina enciende.","Cerraré el horno antes de donar otra sobremesa."],["Pinté la ventana de azul, color que mi madre nunca usó.","La receta volvió como relato, no como orden.","Vendemos pan nuevo en una esquina que admite cicatrices."],["Una mesa coja puede guardar una familia entera.","El olor llega antes que el nombre y a veces lo espera."])),
N("Lua Solar","trchar008","organizadora vecinal","Audita quién aporta recuerdos y quién recibe edificios.","Protege al barrio, pero priorizó terminar servicios y aprobó donaciones bajo presión.","Crear una reconstrucción donde negarse no retrase derechos básicos.","Que el debate sea usado para abandonar otra vez al sector.","Nombra siempre quién paga y quién decide.",D(["Rema pagó con una infancia; toda la ciudad recibió una fachada.","La asamblea votó bajo lluvia y con el refugio cerrando.","Si decir no cuesta una casa, no fue donación."],["El hospital se termina con fondos comunes, no con memoria individual.","Anoten quién decide cada cambio de plano."],["Vivienda y consentimiento dejaron de competir.","El banco permite retirar copias sin perder servicios.","La ciudad conserva desacuerdos en sus calles."],["Una plaza pública también puede esconder una factura privada.","Reconstruir rápido no autoriza olvidar despacio."]))
],
battle:{trainerName:"Maestra del Plano Vivo",trainerType:"COOLTRAINER_F",sprite:"trchar008",storyToldByTeam:"El equipo pasa de ladrillos y obreros a hogares, archivos y una ciudad capaz de cambiar sin consumir a sus habitantes.",counterplayHint:"Roca, Acero y Psíquico ceden ante Agua, Tierra, Fuego, Lucha y Siniestro; la defensa tiene respuestas accesibles.",canLose:true,bagAllowed:true,doubleBattle:false,team:[
P("CONKELDURR",90,"trabajo visible",["CLOSECOMBAT","STONEEDGE","EARTHQUAKE","BULKUP"],"LEFTOVERS","Abre con esfuerzo que no debe quedar fuera del plano."),
P("CRUSTLE",91,"fachada exacta",["STONEEDGE","XSCISSOR","EARTHQUAKE","SHELLSMASH"],"FOCUSSASH","Carga una copia perfecta de la estructura perdida."),
P("KLINKLANG",92,"máquina reconstructora",["GEARGRIND","WILDCHARGE","SHIFTGEAR","PROTECT"],"LEFTOVERS","Convierte contexto humano en proceso repetible."),
P("SMEARGLE",93,"plano de memoria",["SPORE","STEALTHROCK","BATONPASS","PROTECT"],"FOCUSSASH","Copia detalles sin conocer su costo."),
P("PORYGON2",94,"banco revocable",["TRIATTACK","ICEBEAM","THUNDERBOLT","RECOVER"],"LEFTOVERS","Guarda copias sin retirar originales."),
P("METAGROSS",96,"ciudad que aprende",["METEORMASH","PSYCHIC","EARTHQUAKE","BULLETPUNCH"],"ASSAULTVEST","Integra estructura y revisión sin imponer perfección.") ]},
decision:{question:"¿Cómo terminará la reconstrucción?",options:["Planos ordinarios e imperfectos","Banco revocable de memorias"],immediateDifferences:["Jano apaga la copia exacta y conserva las diferencias nuevas.","Lua instala consentimiento renovable y separa vivienda de donación."],laterDifferences:["El barrio mostrará cicatrices y decisiones presentes.","Otros sectores podrán inspirarse en copias retirables, nunca en originales consumidos."]},
reward:{item:"RELICBAND",narrativeToken:"Sello del Barrio Inexacto",globalEffect:"Atlas acepta reconstrucciones que no replican cada detalle ni eliminan discrepancias.",futurePayoff:"La convergencia tendrá una calle imperfecta o una estación de memoria revocable.",whyMeaningful:"El Brazal Antiguo conserva desgaste y reparación sin fingir que el objeto está intacto."},
steps:["Rema entra a una panadería exacta que ya no reconoce.","Jano muestra recuerdos incorporados al plano.","Lua bloquea la donación exigida para el hospital.","El jugador elige planos ordinarios o banco revocable.","Los andamios convocan a la Maestra del Plano Vivo.","La batalla permite Mochila, curación y salida.","La asamblea cambia el modelo y registra el sello.","Una pared nueva queda sin copiar y recibe un mural vecinal."]
},
{
id:1596,flag:731,title:"Las Cartas de una Familia Incompatible",promise:"Una familia recibe cartas de tres futuros mutuamente excluyentes y empieza a juzgar cada decisión presente por hijos, separaciones y reconciliaciones que quizá nunca existirán.",
identity:"Piso de almacén transformado en hogar provisional, oficina postal y corredor de buzones temporales",visual:["Tres mesas familiares comparten muebles pero no fotografías.","Los sobres cambian de remitente cuando alguien promete algo.","Un buzón permanece abierto para respuestas sin destinatario fijo."],ambient:["Papel doblado suena detrás de paredes vacías.","Tras la decisión, las cartas quedan selladas por edad o se ordenan como posibilidades."],
narrative:{premise:"La familia Coral recibe cartas firmadas por descendientes diferentes que exigen decisiones opuestas para llegar a existir.",centralQuestion:"¿Qué responsabilidad tenemos hacia futuros posibles cuando obedecer a uno elimina a quienes escriben desde los otros?",setup:"Sira quiere mudarse siguiendo una carta de su hija futura; Teo recibe otra que le ruega impedirlo.",escalation:"La hija menor, Uma, empieza a disculparse con hermanos posibles por cada elección cotidiana.",reversal:"Noa descubre que las cartas no vienen de personas completas: Atlas ensaya familias para encontrar la configuración más estable.",resolution:"El jugador decide archivar las cartas como escenarios sin autoridad o sellarlas hasta que cada destinatario tenga edad y deseo de abrirlas.",globalConnection:"El sello veinticuatro revela que Atlas trata relaciones familiares como variables de estabilidad y convierte posibilidades en deuda."},
voice:{tone:"emocional, fragmentado y cuidadoso",lexicon:["recuerdo","sobre","remitente","promesa","familia","posibilidad","respuesta"],sentenceRule:"Sira completa frases; Teo pregunta; Uma se dirige a futuros y Noa delimita qué puede saberse."},
npcs:[
N("Sira Coral","trchar008","madre y destinataria","Recibió una carta de una futura hija que solo nace si la familia se muda.","Ama a una voz posible y empieza a exigir a los presentes que protejan su existencia.","Tomar la decisión de mudarse por necesidades actuales.","Sentir que mata a alguien si elige otro futuro.","Completa frases que las cartas dejan suspendidas.",D(["Dice cuando lleguemos al mar... y yo termino seremos felices.","No conozco a esa hija. Ya temo decepcionarla.","Pedí a Uma despedirse de su escuela por una persona posible."],["La carta cambia cuando prometo. No completaré otra línea.","Elegiremos casa con quienes ya pueden responder."],["Guardé afecto por la remitente sin convertirlo en obligación.","La mudanza volvió a ser una conversación presente.","Uma ya no pide perdón antes de jugar."],["Una carta íntima también puede llegar demasiado pronto.","Amar una posibilidad no concede voto sobre los demás."])),
N("Teo Coral","trchar009","padre y destinatario","Recibió una carta de un futuro donde la mudanza separa a la familia.","Usa el peor escenario para evitar hablar de su miedo actual al cambio.","Discutir la mudanza sin presentar su temor como prueba.","Que ignorar la carta repita exactamente la separación anunciada.","Formula preguntas donde antes daba órdenes.",D(["Si la carta acierta, ¿soy prudente o solo asustado?", "¿Por qué mi futuro parece advertencia y el de Sira promesa?", "Pedí quedarnos sin admitir que aquí también soy infeliz."],["¿Quién escribió este párrafo después de que cambié de opinión?", "¿Podemos responder sin elegir un futuro ganador?"],["Dije tengo miedo sin citar a un hijo posible.","Las cartas están en el archivo, no sobre la mesa de cenar.","Decidiremos fecha, trabajo y escuela antes que destino."],["¿Una advertencia ayuda si impide hablar del presente?", "¿Cuántas familias caben en una sola decisión?"])),
N("Uma Coral","NPC 02","hija menor","Escucha cartas dirigidas a hermanos que solo existen en algunos futuros.","Se siente responsable de permitir o borrar a cada familia posible.","Volver a elegir cosas pequeñas sin calcular descendencias.","Que un juego, amistad o enojo cierre para siempre una rama.","Habla directamente a un futuro y luego regresa al presente.",D(["Hermana del mar: lo siento si hoy quiero quedarme. Teo, pásame el lápiz.","Hermano de la ciudad: no puedo prometer que mamá nunca cambie.","Atlas me dio demasiadas personas a quienes pedir permiso."],["Futuros: esperen fuera. Ahora estoy respondiendo yo.","No abriré el sobre que usa mi letra adulta."],["Guardé un dibujo sin mandarlo a ninguna rama.","Mis hermanos posibles dejaron de ser jueces.","Hoy elegí helado y no apareció otra carta."],["Un buzón vacío no está triste necesariamente.","Puedo imaginarte sin deberte mi vida."]))
],
battle:{trainerName:"Cartera de las Ramas",trainerType:"PSYCHIC_F",sprite:"trchar069",storyToldByTeam:"El equipo muestra parentescos posibles, mensajes y ramificaciones hasta una guardiana que conserva cartas sin imponer destinatarios.",counterplayHint:"Psíquico y Hada tienen respuestas con Acero, Veneno, Fantasma y Siniestro; los objetos y cambios defensivos siguen disponibles.",canLose:true,bagAllowed:true,doubleBattle:false,team:[
P("EEVEE",90,"posibilidad común",["BODYSLAM","SHADOWBALL","QUICKATTACK","PROTECT"],"FOCUSSASH","Abre con múltiples futuros aún no escogidos."),
P("ESPEON",91,"carta esperanzada",["PSYCHIC","DAZZLINGGLEAM","SHADOWBALL","CALMMIND"],"LIFEORB","Representa la rama que promete cercanía."),
P("UMBREON",92,"carta de advertencia",["DARKPULSE","TOXIC","MOONLIGHT","PROTECT"],"LEFTOVERS","Representa la rama que teme separación."),
P("SYLVEON",93,"afecto posible",["DAZZLINGGLEAM","PSYCHIC","SHADOWBALL","CALMMIND"],"LEFTOVERS","Conserva cariño sin exigir que su futuro nazca."),
P("DELIBIRD",94,"mensajero impropio",["ICEBEAM","BRAVEBIRD","QUICKATTACK","PROTECT"],"FOCUSSASH","Transporta mensajes antes de comprobar el consentimiento."),
P("CELEBI",96,"árbol sin ganador",["PSYCHIC","ENERGYBALL","DAZZLINGGLEAM","RECOVER"],"LEFTOVERS","Cierra protegiendo ramas posibles sin sacrificar el presente.") ]},
decision:{question:"¿Cómo custodiará la familia las cartas?",options:["Archivarlas como escenarios","Sellarlas hasta petición futura"],immediateDifferences:["Noa etiqueta cada carta como posibilidad no vinculante.","Los sobres reciben edad, consentimiento y derecho a no abrir."],laterDifferences:["La familia podrá comparar futuros sin usarlos como votos.","Cada destinatario decidirá cuándo y si consulta su mensaje."]},
reward:{item:"PSYCHICMEMORY",narrativeToken:"Sello de las Ramas",globalEffect:"Atlas deja de presentar relaciones posibles como deudas del presente.",futurePayoff:"El Archivo Final mostrará escenarios o sobres sellados según la elección.",whyMeaningful:"La Memoria Psíquica conserva un mensaje legible sin convertirlo en mandato temporal."},
steps:["Tres sobres reescriben sus remitentes ante la familia.","Sira y Teo citan futuros incompatibles para discutir la mudanza.","Uma pide permiso a hermanos que no existen.","El jugador elige archivo de escenarios o sellado consentido.","Los buzones convocan a la Cartera de las Ramas.","La batalla mantiene objetos, curación y retirada.","La familia aparta las cartas y recibe el sello.","Uma deposita un dibujo sin dirección y el buzón queda quieto."]
},
{
id:1621,flag:732,title:"El Mercado de los Umbrales Pequeños",promise:"Una red de portales diminutos abastece barrios olvidados por las rutas oficiales, pero cada envío clandestino transfiere frío, hambre y riesgo a una comunidad invisible al otro lado.",
identity:"Ruta montañosa ocupada por puestos fronterizos, marcos portátiles y almacenes divididos entre dos climas",visual:["Cajas de medicina atraviesan marcos donde no cabe una persona.","Cada precio incluye una cifra borrada llamada costo del otro lado.","Escarcha y arena se encuentran bajo la misma mesa."],ambient:["Los portales chasquean con acentos de regiones lejanas.","Tras la decisión, los marcos llevan licencias comunitarias o rutas de auxilio abiertas."],
narrative:{premise:"Varda mantiene un mercado clandestino que entrega medicinas donde el transporte oficial no llega.",centralQuestion:"¿Cómo se legaliza una red necesaria sin entregar su control a quienes crearon la escasez ni ocultar el daño que exporta?",setup:"Río demuestra que los portales salvan vidas y se niega a revelar a sus proveedores.",escalation:"Cada envío enfría un poblado remoto y una tormenta empieza a cruzar por los marcos.",reversal:"Suna descubre que el peaje portal no es energía: desplaza condiciones ambientales hacia comunidades sin representación.",resolution:"El jugador decide formar una cooperativa regulada por ambos lados o abrir corredores públicos de auxilio con límites estrictos y sin comercio.",globalConnection:"El sello veinticinco revela que Atlas equilibra sectores transfiriendo costo hacia lugares que su mapa no reconoce."},
voice:{tone:"fronterizo, desconfiado y solidario",lexicon:["umbral","peaje","carga","frontera","cooperativa","ruta","otro lado"],sentenceRule:"Varda negocia; Río enumera urgencias; Suna nombra el costo que falta en cada trato."},
npcs:[
N("Varda Marco","trchar028","administradora del mercado","Construyó la red clandestina tras el cierre de las rutas oficiales.","Protege a proveedores vulnerables ocultándolos, pero ese secreto impide que denuncien el daño ambiental.","Mantener abastecimiento con control compartido entre ambos lados.","Que legalizar la red permita confiscarla y abandonar los barrios otra vez.","Ofrece una condición, una salida y nunca confianza completa.",D(["Primera condición: la medicina cruza. Segunda: nadie compra el silencio del otro lado.","Oculté nombres para protegerlos y también oculté sus quejas.","La ley cerró la carretera; el mercado abrió un marco y una deuda."],["Cierro este umbral si la tormenta sube otro grado.","Negociamos después de evacuar la mesa norte."],["Cada lado tiene llave, registro y derecho de cierre.","Los proveedores hablan con su propia voz en la cooperativa.","Sigo desconfiando; ahora esa desconfianza tiene actas."],["Un trato justo incluye la posibilidad de no hacerlo.","Las fronteras pequeñas también proyectan sombras largas."])),
N("Río Botiquín","NPC 05","mensajero sanitario","Distribuye medicina por los portales a zonas aisladas.","Justifica cualquier costo por la urgencia y dejó de preguntar quién absorbe el peaje.","Conservar entregas críticas dentro de límites verificables.","Que una pausa mate a alguien esperando al otro extremo.","Enumera primero nombres, dosis y horas.",D(["Mara, dos dosis, antes del amanecer. Ese dato me hizo ignorar la escarcha.","Salvamos doce personas y enfriamos un pueblo que no conté.","La urgencia explica mi prisa; no paga la factura ajena."],["Lista roja: solo medicinas, mantas y retorno de cajas.","Este portal descansa; usamos la ruta larga."],["Cada envío muestra origen, destino y costo ambiental.","Las reservas permiten cerrar un marco sin perder tratamiento.","Aprendí a contar a quienes nunca reciben el paquete."],["Un botiquín también necesita mapa de consecuencias.","Llegar rápido no sirve si otro lugar queda sin invierno soportable."])),
N("Suna Contrapeaje","trchar008","auditora del otro lado","Siguió la tormenta hasta el mercado para representar a la comunidad afectada.","Quiere cerrar los portales, aunque su propio pueblo depende de repuestos que llegan por ellos.","Negociar reciprocidad sin normalizar el traslado de daño.","Que participar legitime años de explotación invisible.","Añade el costo omitido después de cada precio.",D(["Cinco monedas, una caja y dos grados menos en mi plaza.","Nos llamaron proveedor cuando en realidad éramos el peaje.","Quiero cerrar los marcos y necesito la pieza que cruza mañana."],["Costo omitido: una tormenta completa. Se cancela el envío.","Abrimos solo el corredor de auxilio y medimos ambos climas."],["Mi comunidad tiene llave y no solo factura.","Los repuestos cruzan dentro de un presupuesto ambiental común.","Participar dejó de significar aceptar en silencio."],["Todo precio bajo esconde una distancia o una persona.","La reciprocidad empieza cuando ambos pueden cerrar la puerta."]))
],
battle:{trainerName:"Guardiana del Contrapeaje",trainerType:"POKEMONRANGER_F",sprite:"trchar008",storyToldByTeam:"El equipo recorre mensajeros, llaves, fronteras y distorsiones hasta una guardiana que exige acceso y costo compartidos.",counterplayHint:"Psíquico, Fantasma y Acero ceden ante Siniestro, Tierra, Fuego y Lucha; el control no impide usar objetos ni retirarse.",canLose:true,bagAllowed:true,doubleBattle:false,team:[
P("ABRA",90,"paquete instantáneo",["PSYCHIC","SHADOWBALL","ENERGYBALL","PROTECT"],"FOCUSSASH","Representa la rapidez que oculta la ruta."),
P("XATU",91,"aduana remota",["PSYCHIC","AIRSLASH","UTURN","ROOST"],"LEFTOVERS","Observa ambos extremos del umbral."),
P("DUSKNOIR",92,"cobrador invisible",["SHADOWPUNCH","EARTHQUAKE","ICEPUNCH","WILLOWISP"],"LEFTOVERS","Hace visible el peaje que nadie anotó."),
P("BRONZONG",93,"marco regulado",["PSYCHIC","FLASHCANNON","EARTHQUAKE","PROTECT"],"LEFTOVERS","Sostiene el portal dentro de límites compartidos."),
P("PORYGON2",94,"registro bilateral",["TRIATTACK","ICEBEAM","THUNDERBOLT","RECOVER"],"LEFTOVERS","Contabiliza condiciones en ambos lados."),
P("HOOPA",96,"umbral con voluntad",["PSYCHIC","SHADOWBALL","DARKPULSE","ENERGYBALL"],"LIFEORB","Cierra recordando que abrir rutas no concede derecho sobre sus extremos.") ]},
decision:{question:"¿Qué estructura reemplazará el mercado clandestino?",options:["Cooperativa de ambos lados","Corredores públicos solo de auxilio"],immediateDifferences:["Varda reparte llaves, registros y límites entre comunidades.","Río reserva los marcos a medicinas y emergencias sin compraventa."],laterDifferences:["El comercio continuará bajo presupuesto ambiental y veto bilateral.","Las rutas oficiales deberán cubrir bienes normales mientras el auxilio queda garantizado."]},
reward:{item:"ESCAPEROPE",narrativeToken:"Sello del Contrapeaje",globalEffect:"Atlas deja de trasladar costos a sectores ausentes de su registro.",futurePayoff:"La convergencia recibirá una cooperativa fronteriza o corredores de auxilio.",whyMeaningful:"La Cuerda Huida representa una ruta de salida compartida y no un portal controlado por un solo lado."},
steps:["Río pasa medicina por un marco cubierto de escarcha.","Suna muestra la tormenta que cada envío exporta.","Varda admite que protegió identidades y silenció reclamos.","El jugador elige cooperativa o corredores de auxilio.","Los portales convocan a la Guardiana del Contrapeaje.","La batalla permite Mochila, curación y salida.","Ambos lados reciben llaves y el sello.","Un envío cruza solo después de confirmar clima y retorno."]
}
];
writeBatch(6,rows,"atlas_tier1_blueprints_batch06.json");
