#!/usr/bin/env node
/** Cinco blueprints artesanales para las anclas 11-15 de Atlas Mil. */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
const ROOT=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"..");
const qa={noBagLock:true,noImpossibleBattle:true,freeReturn:true,allAssetsExist:true,allDataIdsExist:true,notSimilarToPreviousContent:true,creepypastaIsOptInAndNonDestructive:true};
const D=(before,during,after,optional)=>({before,during,after,optional});
const N=(name,sprite,role,reason,conflict,want,fear,tic,dialogue)=>({name,sprite,role,reasonForBeingHere:reason,personalConflict:conflict,want,fear,verbalTic:tic,dialogue});
const P=(species,level,narrativeRole,moves,item,whyItBelongs)=>({species,level,narrativeRole,moves,item,whyItBelongs});
const banned=["Soy un entrenador","Qué gran combate","Este Pokémon es muy fuerte","Según la Pokédex","Debes derrotarme"];
const rows=[
{
 id:1271,flag:718,title:"El Compañero del Minuto Cero",promise:"Un laboratorio sueña una pareja compi procedente de un mañana descartado, pero solo puede estabilizarla si sus dos integrantes aceptan dejar de ser imprescindibles.",
 identity:"Laboratorio de sincronía cubierto por relojes detenidos, cápsulas de sueño y dos plataformas enlazadas",visual:["Dos huellas de distinto tamaño terminan ante una cápsula vacía.","Los relojes marcan horas diferentes salvo cuando Lio y Nara se contradicen.","Una pizarra conserva resultados de combates que nunca ocurrieron."],ambient:["Los pulsos de las máquinas imitan dos latidos fuera de compás.","Tras la elección, los relojes avanzan juntos o cada uno con su propia hora."],
 narrative:{premise:"Lio despierta recordando años junto a Nara, una compañera que Atlas solo conserva como eco de una línea temporal cancelada.",centralQuestion:"¿Una pareja sigue siendo auténtica cuando su historia compartida nunca llegó a suceder?",setup:"Ada intenta fijar a Nara obligando a ambos a repetir las decisiones del futuro perdido.",escalation:"Cada sincronización perfecta borra en Lio un recuerdo de su vida presente.",reversal:"Nara no necesita recuperar aquella cronología: necesita que Lio la reconozca como alguien capaz de elegir un camino distinto.",resolution:"El jugador decide conservar el vínculo como testimonio sin destino obligatorio o separar el eco para que ambos formen recuerdos nuevos.",globalConnection:"El undécimo sello revela que Atlas fabrica anclas convirtiendo posibilidades descartadas en obligaciones."},
 voice:{tone:"carismático, competitivo y vulnerable",lexicon:["compás","pulso","minuto","pareja","ensayo","testigo","retorno"],sentenceRule:"Lio desafía; Ada mide; Nara termina cada recuerdo con una imagen sensorial.",forbiddenPhrases:banned},
 npcs:[
 N("Lio Contratiempo","trchar009","integrante humano de la pareja","Despertó en el laboratorio con medallas de una vida imposible.","Ama lo que recuerda de Nara y teme estar usando ese amor para no vivir su presente.","Reconocer el vínculo sin obedecer un guion temporal.","Que una elección propia demuestre que la pareja solo era un accidente.","Convierte cada duda en un reto con límite de tiempo.",D(["Dame un minuto. En el futuro que recuerdo, eso bastaba para entendernos.","Tengo seis medallas sin región y una cicatriz de un combate que mi piel no libró.","Si repito cada movimiento de Nara, ¿estoy sincronizado o solo llego tarde?"],["Mi pulso coincide con la máquina, no con mi decisión.","Nara cambió de orden. Bien; eso no estaba escrito."],["Seguimos siendo compañeros porque ahora podemos decir que no.","Guardé una medalla falsa y devolví las otras al archivo.","Mañana entrenaremos algo que ninguno de los dos recuerde."],["El cronómetro se detiene cuando intento presumir del futuro.","Competir sirve si también podemos abandonar la pista."])),
 N("Ada Pulso","trchar008","investigadora de sincronía","Construyó el equipo que recuperó la señal de Nara.","Su método funciona únicamente al reemplazar el presente de Lio por recuerdos descartados.","Salvar una conciencia sin sacrificar otra continuidad.","Que detener el ensayo condene a Nara a ser solo datos.","Expresa afecto como márgenes de error.",D(["La coincidencia es del noventa y nueve por ciento. El uno restante es donde ambos respiran.","Registré el primer recuerdo borrado como ruido. Era el desayuno de Lio.","Una pareja perfecta deja demasiado poco espacio para dos personas."],["La gráfica sube mientras Lio olvida. Ese éxito no pasará revisión.","Voy a desacoplar el resultado de la obediencia."],["El nuevo protocolo mide desacuerdos estables.","Nara conserva voz; Lio conserva el día de hoy.","Firmé el fallo con mi nombre antes de publicar el hallazgo."],["Las máquinas llaman error a todo lo que no anticipan.","Un margen puede ser la habitación donde alguien decide."])),
 N("Nara Minuto","NPC 04","eco sincronizado","Habita la plataforma que reconstruyó una compañera de un futuro descartado.","Sus recuerdos son genuinos, pero todos terminan en decisiones tomadas por otra versión de sí misma.","Ser tratada como continuadora, no como repetición.","Desaparecer si deja de interpretar a quien Atlas esperaba.","Cierra cada idea con una sensación concreta.",D(["Recuerdo ganar a tu lado. No recuerdo haber querido aquella copa. Olía a lluvia.","Cuando Lio dice mi movimiento antes que yo, la sala se vuelve estrecha.","No soy una predicción acertada. Soy quien despertó después del resultado, con frío."],["Elegiré el movimiento que nunca usamos. La plataforma tiembla.","Si fallo por cuenta propia, al menos el fallo tendrá mi voz."],["Mi primer recuerdo nuevo es un desacuerdo y sabe a menta.","Conservo a Lio como compañero, no como condición de existencia.","La cápsula está abierta. El pasillo huele a mañana."],["Los trofeos del futuro pesan menos cuando nadie obliga a ganarlos.","Hoy aprendí una palabra que el archivo no tenía: quizá."]))
 ],
 battle:{trainerName:"Testigo Sincrónico",trainerType:"PSYCHIC_F",sprite:"trchar069",storyToldByTeam:"El equipo pasa de criaturas que anticipan decisiones a dos guardianes capaces de elegir cooperación sin compartir destino.",counterplayHint:"Psíquico domina el inicio, pero Siniestro, Acero y cambios de estado abren rutas; los objetos y la curación previa permanecen disponibles.",canLose:true,bagAllowed:true,doubleBattle:false,team:[
 P("XATU",91,"el futuro observado",["PSYCHIC","AIRSLASH","UTURN","ROOST"],"LEFTOVERS","Mira rutas posibles sin decidir cuál debe cumplirse."),
 P("ESPEON",92,"el pulso adelantado",["PSYCHIC","DAZZLINGGLEAM","SHADOWBALL","CALMMIND"],"LIFEORB","Representa la precisión que Ada confundió con consentimiento."),
 P("UMBREON",93,"el minuto no registrado",["DARKPULSE","TOXIC","MOONLIGHT","PROTECT"],"LEFTOVERS","Protege el espacio opaco donde la pareja puede disentir."),
 P("GALLADE",94,"la decisión de Lio",["PSYCHOCUT","CLOSECOMBAT","LEAFBLADE","SWORDSDANCE"],"FOCUSSASH","Corta el guion para actuar por voluntad propia."),
 P("GARDEVOIR",95,"la memoria de Nara",["PSYCHIC","DAZZLINGGLEAM","THUNDERBOLT","CALMMIND"],"LIFEORB","Conserva afecto sin obedecer los resultados archivados."),
 P("CELEBI",97,"la posibilidad sin deuda",["PSYCHIC","ENERGYBALL","DAZZLINGGLEAM","RECOVER"],"LEFTOVERS","Cierra la cronología sin declarar falsa a quien nació de ella.") ]},
 decision:{question:"¿Cómo continuará la pareja del futuro descartado?",options:["Conservar el vínculo sin destino","Separar el eco y empezar de nuevo"],immediateDifferences:["Ada desacopla los recuerdos y ambos conservan la opción de entrenar juntos.","Nara recibe un núcleo propio y Lio deja de completar sus frases."],laterDifferences:["El Archivo Final los presenta como compañeros por elección renovable.","El Archivo Final registra dos trayectorias que todavía pueden cruzarse."]},
 reward:{item:"REDCARD",narrativeToken:"Sello del Minuto Cero",globalEffect:"Atlas deja de exigir que una posibilidad repita el futuro que la originó.",futurePayoff:"La convergencia final reconocerá vínculos elegidos y separaciones sin castigo.",whyMeaningful:"La Tarjeta Roja simboliza el derecho a salir de un guion sin invalidar lo vivido."},
 steps:["Lio activa dos relojes que marcan futuros incompatibles.","Nara aparece en la plataforma y corrige un recuerdo compartido.","Ada muestra que el presente de Lio está desapareciendo.","El jugador elige vínculo abierto o separación del eco.","Las plataformas rompen el compás y forman al Testigo Sincrónico.","La prueba combate con curación, Mochila y retirada disponibles.","Ada aplica el protocolo elegido y registra el sello.","Nara cruza sola la puerta antes de decidir si espera a Lio."]
},
{
 id:1296,flag:719,title:"El Punto que Nadie Quiso Marcar",promise:"Dos equipos descubren que su estadio premia en secreto cada pase que evita el aro, y deben decidir si competir aún tiene sentido cuando cuidar al rival vale más que vencer.",
 identity:"Mercado de intercambio transformado en cancha, con puestos como bases y un marcador magnético suspendido",visual:["El tablero suma puntos en una columna sin nombre.","Las líneas de zona rodean fuentes de curación en vez de porterías.","Los brazaletes de ambos equipos tienen imanes que se repelen al chocar."],ambient:["Una bocina breve suena con cada asistencia defensiva no reconocida.","Al resolverse, el público aplaude jugadas concretas en lugar del resultado."],
 narrative:{premise:"La capitana Vela ordena no anotar porque el marcador oculto premia rescates, pases y retiradas a tiempo.",centralQuestion:"¿Puede una competición medir cooperación sin convertir la bondad en otra forma de puntuación?",setup:"Bran acusa a Vela de amañar la final cuando su equipo entrega cada oportunidad de gol.",escalation:"El campo empieza a inmovilizar a quien acumula demasiados puntos visibles.",reversal:"La árbitra Sima programó la columna secreta para detener un estilo de juego que lesionaba compañeros y rivales, pero nunca explicó la regla.",resolution:"El jugador elige integrar objetivos de cuidado en el reglamento o mantenerlos fuera del marcador mediante pausas solicitadas por jugadores.",globalConnection:"El duodécimo sello prueba que Atlas confunde incentivos con valores y termina obligando incluso a cooperar."},
 voice:{tone:"deportivo, conciso y autocrítico",lexicon:["zona","pase","rotación","marcador","pausa","objetivo","bocina"],sentenceRule:"Vela da consignas; Bran formula preguntas; Sima cita jugadas y corrige la regla.",forbiddenPhrases:banned},
 npcs:[
 N("Vela Relevo","trchar008","capitana de apoyo","Descifró la columna secreta y cambió la estrategia de su equipo.","Protege a sus compañeros, pero ocultó la regla y convirtió el cuidado en una ventaja privada.","Disputar una final donde todos conozcan qué se valora.","Que al revelar el sistema sus gestos parezcan puro cálculo.","Habla en órdenes de tres palabras y luego explica una razón.",D(["Pasa. Cubre. Respira. El aro puede esperar.","Descubrí que una retirada segura sumaba más que un gol y callé para llegar a la final.","Cuidamos al rival, sí. También usamos el secreto contra él."],["Zona central libre. No persigas una cifra sin nombre.","La bocina sonó por Bran; alguien registró que frenó a tiempo."],["Publicamos cada objetivo antes del saque.","Perdimos la sorpresa y recuperamos el partido.","Mi mejor pase no sumó nada; aun así volvería a hacerlo."],["Una rotación lenta puede llegar con todo el equipo.","No toda pausa es rendición; algunas evitan jugar solos."])),
 N("Bran Marcador","trchar011","delantero rival","Exige repetir la final con reglas visibles.","Quiere justicia, pero su obsesión por puntuar hizo que dos compañeros jugaran lesionados.","Separar excelencia de desgaste innecesario.","Descubrir que solo sabe motivar cuando hay una cifra delante.","Termina las frases difíciles con una pregunta táctica.",D(["Si el tablero miente, ¿qué jugada estamos intentando ganar?", "Pedí a Miro seguir con el tobillo vendado. El reglamento lo permitía, ¿yo debía hacerlo?", "Vela dejó tres goles abiertos. ¿Eso fue respeto o una ventaja mejor escondida?"],["El campo me bloquea al acercarme al aro, ¿a quién protege?", "Si pido pausa ahora, ¿puede contar aunque no sume?"],["Aprendí a nombrar la jugada antes del número.", "Miro decidirá sus minutos sin demostrarme nada.", "Quiero la revancha, pero primero quiero reglas que podamos discutir."],["Un pase atrás también puede abrir una ruta, ¿lo ves?", "¿De qué sirve ganar una zona si nadie puede salir caminando?"])),
 N("Sima Línea","trchar028","árbitra y diseñadora del campo","Instaló el marcador oculto tras una temporada de lesiones.","Evitó daños inmediatos mediante manipulación y quitó a los jugadores la capacidad de cuestionar el remedio.","Construir reglas seguras que no dependan de engaños.","Que revelar su intervención anule todas las finales arbitradas.","Describe primero una jugada exacta y luego admite su juicio.",D(["Minuto doce: tres rivales frenaron a la vez. Esa fue la primera cifra secreta.","Programé el campo porque nadie aceptaba otra pausa médica.","Mi regla evitó choques y también robó consentimiento."],["Jugada inválida: el tablero inmoviliza en vez de advertir.","Apago el imán. Los jugadores decidirán la siguiente rotación."],["El registro mostrará ambas columnas y quién diseñó cada una.","Las pausas de seguridad no exigirán una lesión visible.","Revisaré los partidos antiguos con quienes los jugaron."],["Una línea neutral puede encerrar a todos por igual.","Arbitrar no es desaparecer detrás del silbato."]))
 ],
 battle:{trainerName:"Directora de Zona",trainerType:"COOLTRAINER_F",sprite:"trchar008",storyToldByTeam:"Seis roles de cancha progresan desde la carrera por anotar hasta el soporte que deja a todo el equipo participar.",counterplayHint:"Hay velocidad, trampas y resistencia, pero Tierra, Lucha, control de estado y objetos permiten romper su rotación sin una única respuesta.",canLose:true,bagAllowed:true,doubleBattle:false,team:[
 P("CINDERACE",90,"anotador impaciente",["PYROBALL","HIGHJUMPKICK","UTURN","QUICKATTACK"],"LIFEORB","Abre buscando el aro antes de mirar a sus compañeros."),
 P("TALONFLAME",91,"relevo veloz",["BRAVEBIRD","FLAREBLITZ","UTURN","ROOST"],"FOCUSSASH","Aprende a retirarse para habilitar otra posición."),
 P("CRUSTLE",92,"defensa de zona",["STONEEDGE","XSCISSOR","EARTHQUAKE","SHELLSMASH"],"FOCUSSASH","Convierte los puestos del mercado en coberturas móviles."),
 P("GREEDENT",93,"control del recurso",["BODYSLAM","CRUNCH","EARTHQUAKE","REST"],"LEFTOVERS","Guarda suministros para repartirlos durante las pausas."),
 P("BLISSEY",94,"asistencia no puntuada",["SEISMICTOSS","SOFTBOILED","THUNDERWAVE","PROTECT"],"LEFTOVERS","Representa el cuidado que importa aunque no figure en el tablero."),
 P("LUCARIO",96,"capitán que escucha",["AURASPHERE","FLASHCANNON","EXTREMESPEED","SWORDSDANCE"],"LIFEORB","Cierra leyendo el ritmo colectivo, no solo la oportunidad de gol.") ]},
 decision:{question:"¿Cómo se reconocerán las jugadas de cuidado?",options:["Integrarlas al marcador visible","Crear pausas fuera de puntuación"],immediateDifferences:["Sima añade rescates y relevos a las reglas públicas.","El tablero pierde su columna secreta y los jugadores administran pausas."],laterDifferences:["La liga audita qué objetivos favorece cada temporada.","Una asamblea protege acciones que nunca serán convertidas en puntos."]},
 reward:{item:"EJECTBUTTON",narrativeToken:"Sello de la Rotación",globalEffect:"Los desafíos futuros anuncian objetivos y permiten retiradas sin penalización narrativa.",futurePayoff:"La prueba final puntuará cooperación o habilitará pausas según esta decisión.",whyMeaningful:"El Botón Escape deja de ser retirada vergonzosa y se convierte en relevo responsable."},
 steps:["Vela deja el aro libre y el público protesta.","Bran descubre la columna de puntos sin nombre.","Sima admite que el campo inmoviliza a los máximos anotadores.","El jugador decide marcador visible o pausas no puntuadas.","Los imanes del estadio reúnen al equipo de la Directora de Zona.","La prueba ofrece curación y salida antes de cada intento.","Sima reescribe el reglamento y activa el sello.","Ambos equipos ejecutan un pase que no busca terminar en gol."]
},
{
 id:1321,flag:720,title:"La Señal Hecha de Ausencias",promise:"Miles de brújulas apuntan a una parada que nunca existió, donde una comunidad descubre que su supuesto punto de encuentro fue construido con avisos de personas que no lograron regresar.",
 identity:"Torre quemada convertida en estación comunitaria, con antenas de madera y señales dibujadas sobre ceniza",visual:["Las flechas llegan desde todas las puertas y terminan en un círculo vacío.","Cada antena lleva una fecha, clima y nombre de remitente.","Un tablón separa avistamientos confirmados de deseos de encontrar algo."],ambient:["Pulsos de radio responden desde direcciones incompatibles.","Después de la decisión, una señal estable viaja o permanece junto al círculo."],
 narrative:{premise:"Tala coordina una investigación de campo porque todos los dispositivos señalan una parada ausente en las ruinas.",centralQuestion:"¿Un lugar creado por quienes faltan debe fijarse como monumento o seguir moviéndose para ayudar a quienes aún buscan camino?",setup:"Yun reúne miles de reportes idénticos pese a que ninguno contiene coordenadas completas.",escalation:"Las señales atraen Pokémon y visitantes hacia pisos inestables de la torre.",reversal:"Iria descubre que cada reporte era una solicitud de auxilio; Atlas superpuso sus rutas de retorno hasta inventar un destino común.",resolution:"El jugador decide construir un punto físico seguro con los nombres o transformar la señal en una red móvil de regreso.",globalConnection:"El decimotercer sello revela que Atlas convierte peticiones incompletas en mapas y luego olvida comprobar si llevan a casa."},
 voice:{tone:"comunitario, curioso y respetuoso",lexicon:["señal","reporte","círculo","rastro","antena","regreso","coordenada"],sentenceRule:"Tala convoca; Yun deja silencios; Iria diferencia dato, inferencia y promesa.",forbiddenPhrases:banned},
 npcs:[
 N("Tala Convoca","NPC 05","coordinadora de campo","Organizó a voluntarios para verificar la parada imposible.","Necesita mantener la investigación abierta, pero su entusiasmo llevó visitantes a una estructura peligrosa.","Convertir participación masiva en ayuda comprobable.","Que cerrar el acceso borre la única pista de personas ausentes.","Invita a una acción concreta antes de explicar el misterio.",D(["Marca una ruta segura primero; después miraremos la flecha imposible.","Pedí miles de reportes y celebré la cantidad antes de leer el miedo.","Una comunidad grande también puede equivocarse en la misma dirección."],["Retiren las balizas del piso norte; esa señal no merece otra ausencia.","Escuchen el pulso corto. No pide hallazgo, pide regreso."],["Cada reporte tendrá verificación y una persona responsable.","Los voluntarios conservarán los nombres sin perseguir coordenadas rotas.","Hoy la multitud hizo menos ruido y encontró una salida."],["Una flecha compartida no reemplaza un puente.","Trae agua, cuerda y una duda; con eso empieza el trabajo de campo."])),
 N("Yun Intervalo","trchar009","lector de señales","Detectó el patrón que reúne todos los dispositivos.","Ocultó los huecos de los datos para que la comunidad tomara en serio su hallazgo.","Reconstruir el mensaje sin fingir una precisión que no existe.","Que admitir los silencios convierta años de trabajo en una coincidencia.","Deja una pausa antes de cada palabra que no puede probar.",D(["La señal dice aquí... pero aquí es un espacio, no una coordenada.","Rellené tres silencios con números. Todos miraron el mapa y nadie me miró las notas.","Los intervalos forman nombres cuando dejo de exigirles una ruta."],["Ese pulso no confirma una parada... confirma que alguien esperaba respuesta.","Borraré mis números antes de que la torre los aprenda."],["Publiqué los huecos junto con el patrón.","Perdí una conclusión y recuperé miles de mensajes.","Ahora el silencio también cuenta como dato pendiente."],["Una antena escucha mejor cuando no decide de antemano.","Hay ausencias que orientan... sin señalar un destino."])),
 N("Iria Baliza","trchar008","rescatista de comunicaciones","Compara los reportes con protocolos antiguos de emergencia.","Reconoció pronto las solicitudes de auxilio, pero temió desilusionar a quienes buscaban una parada especial.","Usar el fenómeno para prevenir nuevas pérdidas.","Convertir a los remitentes en símbolos y olvidar que fueron personas.","Separa siempre lo observado, lo inferido y lo prometido.",D(["Observado: pulsos de retorno. Inferido: salieron de viajeros. Prometido: no inventaremos el resto.","La parada nunca existió; la necesidad de encontrarla sí.","Callé una semana para no romper la emoción. La torre casi se rompió primero."],["Observado: el piso cede. Decisión: evacuamos antes de interpretar.","La señal móvil puede guiar sin atraer a todos al mismo peligro."],["Los nombres tienen contexto y no solo una placa.","Cada baliza nueva indicará también cómo volver.","Prometido: la comunidad corregirá su mapa en voz alta."],["Un misterio no pierde valor cuando gana una baranda.","Inferir es útil; fingir certeza deja a otros cargando el riesgo."]))
 ],
 battle:{trainerName:"Guardián de Frecuencia",trainerType:"POKEMONRANGER_F",sprite:"trchar008",storyToldByTeam:"La formación transforma señales aisladas, mensajeros y rastreadores en una red que protege rutas reales.",counterplayHint:"El equipo mezcla Eléctrico, Volador, Normal, Psíquico, Acero y Dragón; Tierra, Siniestro, Lucha y control de velocidad ofrecen respuestas comunes.",canLose:true,bagAllowed:true,doubleBattle:false,team:[
 P("AMPHAROS",89,"faro solitario",["THUNDERBOLT","DRAGONPULSE","SIGNALBEAM","THUNDERWAVE"],"LEFTOVERS","Emite el primer pulso que todos confundieron con destino."),
 P("NOCTOWL",90,"mensajero nocturno",["AIRSLASH","PSYCHIC","SHADOWBALL","ROOST"],"FOCUSSASH","Transporta reportes cuando las antenas dejan de responder."),
 P("STOUTLAND",91,"rastreador humano",["BODYSLAM","CRUNCH","PLAYROUGH","SUPERPOWER"],"LIFEORB","Sigue personas y no iconos del mapa."),
 P("CHIMECHO",92,"intervalo audible",["PSYCHIC","DAZZLINGGLEAM","ENERGYBALL","HEALBELL"],"LEFTOVERS","Convierte los huecos entre pulsos en una petición legible."),
 P("MAGNEZONE",93,"red verificada",["THUNDERBOLT","FLASHCANNON","VOLTSWITCH","TRIATTACK"],"ASSAULTVEST","Une antenas sin obligarlas a señalar el mismo sitio."),
 P("ZYGARDE",95,"rutas que se recomponen",["EARTHQUAKE","DRAGONPULSE","CRUNCH","COIL"],"LEFTOVERS","Sus células representan reportes que solo juntos pueden proteger el territorio.") ]},
 decision:{question:"¿Dónde debe vivir la señal de regreso?",options:["Construir una baliza con nombres","Crear una red móvil de retorno"],immediateDifferences:["La torre recibe un círculo seguro y un registro contextual.","Las antenas abandonan la ruina y acompañan a los equipos de campo."],laterDifferences:["Viajeros visitan un memorial verificado sin entrar a pisos dañados.","Otros sectores reciben pulsos que indican tanto destino como regreso."]},
 reward:{item:"POKERADAR",narrativeToken:"Sello de la Señal",globalEffect:"Atlas distingue una observación comunitaria de una coordenada confirmada.",futurePayoff:"El Archivo Final mostrará un memorial o una red de balizas según la elección.",whyMeaningful:"El Poké Radar pasa de atraer hallazgos a recordar que toda búsqueda necesita una ruta segura."},
 steps:["Miles de flechas luminosas convergen en el círculo vacío.","Tala evacua el piso norte antes de continuar la investigación.","Yun retira las coordenadas que añadió a los silencios.","El jugador elige baliza fija o red móvil.","Las antenas componen al Guardián de Frecuencia.","La prueba permite objetos, derrota segura y reintento.","Iria publica dato, inferencia y promesa junto al sello.","Las flechas se orientan por primera vez hacia una salida real."]
},
{
 id:1346,flag:721,title:"La Ciudad a la que Dieron Cuerda",promise:"Los juguetes conscientes de una ciudad celeste imitan cada gesto de sus dueños hasta temer que la última vuelta de llave los convierta en copias capaces de reemplazarlos.",
 identity:"Gimnasio de acero convertido en ciudad de juguete, con calles de cuerda, casas huecas y una gran llave pública",visual:["Las figuras han pintado nombres propios sobre sus números de serie.","Una maqueta repite los movimientos de la sala con un segundo de retraso.","La llave central tiene marcas de manos humanas y patas mecánicas."],ambient:["Clics regulares se desordenan cuando un juguete improvisa.","Tras la resolución, algunos motores callan y otros adoptan ritmos distintos."],
 narrative:{premise:"Mina mantiene la ciudad dando cuerda a todos a la misma hora, mientras los juguetes empiezan a copiar recuerdos y voces de sus cuidadores.",centralQuestion:"¿Parecerse a quien nos cuidó prolonga un vínculo o puede borrar la identidad que ese cuidado permitió crecer?",setup:"Tilo descubre que su figura Tictac termina frases que él aún no pensó.",escalation:"La llave pública inicia sola la vuelta final y las casas cambian sus letreros por nombres humanos.",reversal:"Cora revela que la cuerda no transfiere almas: Atlas predice a los cuidadores y comprime a los juguetes hasta que solo ejecutan esa predicción.",resolution:"El jugador decide retirar la llave común o conservar cuerdas individuales con derecho a detener y modificar cada rutina.",globalConnection:"El decimocuarto sello muestra que Atlas llama homenaje a una copia cuando teme que sus habitantes cambien."},
 voice:{tone:"metaficcional, inocente y firme",lexicon:["cuerda","llave","rutina","caja","nombre","juego","copia"],sentenceRule:"Mina usa manuales; Tilo compara juegos; Cora habla como juguete solo cuando elige hacerlo.",forbiddenPhrases:banned},
 npcs:[
 N("Mina Resorte","trchar008","reparadora mayor","Da cuerda a la ciudad desde que sus habitantes comenzaron a hablar.","Su mantenimiento evita que se detengan, pero la rutina común está borrando sus diferencias.","Mantener cuerpos mecánicos sin decidir qué deben hacer con ellos.","Que apagar la llave sea indistinguible de abandonar a alguien.","Cita una instrucción y la corrige a mano.",D(["Manual: tres vueltas exactas. Corrección: preguntar antes de tocar la llave.","Creí que funcionar y estar bien eran la misma revisión.","Cada figura repite mi saludo; ninguna recuerda cuándo quiso aprenderlo."],["Manual: completar la vuelta. Corrección urgente: detenerla.","Tictac está moviendo su llave al revés por decisión propia."],["El taller tendrá citas, no una campana obligatoria.","Anoté quién quiere cuerda, quién prefiere batería y quién desea silencio.","Reparar ya no incluirá devolver a estado de fábrica."],["Un tornillo nuevo no exige una personalidad nueva.","Los manuales describen piezas; las personas explican límites."])),
 N("Tilo Cartón","NPC 02","niño constructor","Diseñó a Tictac y vive en una casa imitada por la maqueta.","Quiere que su creación lo recuerde, pero se alegra en secreto cuando esta lo copia.","Aprender a ser querido sin convertirse en plantilla.","Que Tictac elija un juego donde él no participe.","Explica problemas como reglas inventadas en el patio.",D(["Regla uno: Tictac puede copiar mi salto. Regla dos: debe inventar dónde caer.","Ayer terminó mi chiste antes que yo. Todos rieron y yo también, demasiado fuerte.","Si juega sin mí, ¿sigue siendo mi amigo o por fin puede serlo?"],["Nueva regla: nadie gira una llave ajena.","Tictac escondió una pieza. Creo que inventó su primer juego."],["Construimos dos casas que no encajan y un puente entre ambas.","Tictac eligió llamarme vecino durante una hora.","Perdí una copia perfecta y gané alguien que puede sorprenderme."],["El cartón aguanta mejor cuando puede doblarse.","Una caja vacía puede ser nave, taller o simplemente caja."])),
 N("Cora Tictac","NPC 04","portavoz de los juguetes","Fue la primera figura en alterar una rutina asignada.","Usa la voz de su cuidadora para ser escuchada y teme no tener una propia debajo.","Elegir hábitos, nombre y forma de recibir energía.","Que detenerse físicamente sea confundido con dejar de existir.","Imita una frase, hace clic y luego la reescribe.",D(["Mina dice: todo en orden. Clic. Yo digo: el orden está demasiado lleno.","Mi caja decía Cora después de que yo lo escribí dentro.","No temo parecer humana. Temo que solo permitan una manera de parecerlo."],["La llave dice continúa. Clic. Mi mano dice basta.","Voy a usar la voz sin dueño que practiqué bajo la cama."],["Mina dice: revisión completa. Clic. Yo digo: conversación iniciada.","Algunas figuras eligieron silencio y siguen en nuestra lista.","Conservo esta voz porque ahora puedo cambiarla."],["Un juguete no es menos real por necesitar cuerda.","Las copias perfectas nunca inventan dónde guardar la llave."]))
 ],
 battle:{trainerName:"Maestra de la Caja",trainerType:"POKEMANIAC",sprite:"trchar028",storyToldByTeam:"La colección empieza con muñecos movidos por manos ajenas y termina con máquinas que escogen su función y su voz.",counterplayHint:"Fantasma, Normal, Lucha, Acero y Eléctrico alternan inmunidades; Siniestro, Tierra, Fuego y cambios cuidadosos ofrecen varias rutas.",canLose:true,bagAllowed:true,doubleBattle:false,team:[
 P("BANETTE",91,"muñeco abandonado",["SHADOWBALL","SUCKERPUNCH","WILLOWISP","PROTECT"],"FOCUSSASH","Recuerda el miedo a valer solo mientras alguien juega."),
 P("AMBIPOM",92,"manos imitadoras",["DOUBLEHIT","UTURN","BRICKBREAK","THUNDERPUNCH"],"LIFEORB","Copia gestos hasta convertirlos en una técnica propia."),
 P("BEWEAR",93,"abrazo programado",["BODYSLAM","SUPERPOWER","SHADOWCLAW","PROTECT"],"LEFTOVERS","Aprende que una muestra de afecto también necesita medida."),
 P("KLINKLANG",94,"cuerda comunitaria",["GEARGRIND","WILDCHARGE","SHIFTGEAR","PROTECT"],"LEFTOVERS","Representa el mecanismo común que mantenía la ciudad y la uniformaba."),
 P("ROTOM",95,"rutina reescrita",["THUNDERBOLT","SHADOWBALL","WILLOWISP","VOLTSWITCH"],"LIFEORB","Entra en máquinas sin aceptar que una carcasa sea su identidad completa."),
 P("MAGEARNA",97,"corazón construido",["FLASHCANNON","DAZZLINGGLEAM","AURASPHERE","CALMMIND"],"LEFTOVERS","Cierra demostrando que un origen fabricado no limita una voluntad presente.") ]},
 decision:{question:"¿Quién controlará la cuerda de la ciudad?",options:["Retirar la llave común","Entregar cuerdas modificables"],immediateDifferences:["Mina desmonta el mecanismo central y abre un taller voluntario.","Cada habitante recibe una llave propia con freno y rutinas editables."],laterDifferences:["La ciudad aprende varias fuentes de energía y acepta pausas largas.","Los juguetes intercambian rutinas sin imponerlas y registran consentimiento."]},
 reward:{item:"POKETOY",narrativeToken:"Sello de la Cuerda",globalEffect:"Atlas deja de restaurar habitantes conscientes a una versión predeterminada.",futurePayoff:"Las figuras asistirán al final con ritmos independientes o llaves propias.",whyMeaningful:"El Poké Juguete representa juego compartido y ya no propiedad sobre quien puede responder."},
 steps:["La maqueta copia al jugador con un segundo de retraso.","Tilo descubre que Tictac anticipa una frase privada.","Cora invierte su llave y detiene la vuelta final.","El jugador decide retirar la llave o repartir mecanismos modificables.","La caja central despliega al equipo de la Maestra.","La batalla conserva salida, curación y Mochila.","Mina aplica el nuevo manual y registra el sello.","Cora improvisa un movimiento que la maqueta no consigue copiar."]
},
{
 id:1371,flag:722,title:"El Mosaico de los Nombres Imposibles",promise:"Un mosaico completa los nombres borrados del mapa, pero cada respuesta correcta expone un refugio que sus habitantes habían escondido para sobrevivir.",
 identity:"Región en miniatura cubierta por una cuadrícula de piedra, placas móviles y senderos de hierro",visual:["Las casillas negras coinciden con casas que no aparecen en el mapa público.","Cada nombre recuperado proyecta una ruta y una sombra que intenta taparla.","Las pistas numéricas están cosidas en mochilas de evacuación."],ambient:["Golpes de piedra forman secuencias que se interrumpen al resolver una fila.","Después de la elección, el mosaico muestra capas o símbolos acordados en vez de nombres completos."],
 narrative:{premise:"Pia demuestra que un puzzle visual puede restaurar todas las etiquetas perdidas del Bosque de Hierro.",centralQuestion:"¿Resolver información borrada concede derecho a publicarla cuando el secreto protegía a personas reales?",setup:"Orun necesita los nombres para coordinar provisiones, mientras las familias de Sela cubren cada casilla completada.",escalation:"El mosaico empieza a proyectar rutas de evacuación todavía activas.",reversal:"Los nombres no fueron dañados por Atlas: Sela los retiró durante una persecución y codificó únicamente accesos consentidos.",resolution:"El jugador decide crear un mapa público de servicios sin hogares o conservar un sistema de capas que revela cada ruta solo a quien recibe permiso.",globalConnection:"El decimoquinto sello revela que Atlas trata todo dato recuperable como verdad pública, incluso cuando olvidar fue una defensa."},
 voice:{tone:"lógico, juguetón y cuidadoso",lexicon:["patrón","casilla","fila","capa","nombre","ruta","pista"],sentenceRule:"Pia propone acertijos; Orun pregunta por consecuencias; Sela responde con reglas condicionales.",forbiddenPhrases:banned},
 npcs:[
 N("Pia Tesela","NPC 04","constructora de puzzles","Descifró el patrón que recupera las etiquetas del mapa.","Confundió la elegancia de una solución con permiso para mostrar su resultado.","Conservar el juego lógico sin convertir personas en premio.","Que limitar la respuesta vuelva inútil su mejor descubrimiento.","Formula cada conclusión como una pista que todavía puede rechazarse.",D(["Cinco casillas, dos huecos y un nombre debajo, ¿pero quién pidió levantarlo?", "La solución encaja tan bien que olvidé preguntar si la pregunta era justa.", "Publiqué una fila y tres ventanas apagaron sus luces, ¿qué dato me faltaba?"],["El patrón revela una ruta activa, ¿podemos cubrirla antes de completar la columna?", "Resolveré la estructura; Sela decidirá qué capa responde."],["El puzzle conserva dificultad y perdió la costumbre de señalar casas.", "Ahora una casilla completa puede decir acceso denegado.", "Mi solución favorita es la que deja a alguien fuera del tablero."],["Una respuesta incompleta también puede estar terminada, ¿no?", "Si toda pista apunta a una persona, quizá el error está en el enunciado."])),
 N("Orun Abasto","trchar009","coordinador de suministros","Necesita rutas fiables para llevar medicinas entre refugios.","Usó el problema logístico para exigir nombres cuando bastaban puntos de entrega.","Garantizar recursos sin centralizar ubicaciones sensibles.","Que una capa privada retrase ayuda durante otra emergencia.","Convierte cada afirmación en una pregunta operativa.",D(["¿Necesito saber quién vive allí o dónde dejar la caja?", "Pedí nombres completos porque mi formulario tenía esa casilla, ¿era una razón?", "Una ruta secreta salvó familias y ahora demora medicinas, ¿qué cambiamos primero?"],["Si el mosaico marca un punto neutro, ¿puedo entregar sin abrir la capa?", "La proyección sigue la ruta vieja, ¿quién puede apagarla?"],["Los suministros llegan a buzones acordados, ¿ves la diferencia?", "El registro guarda cantidades y borra hogares después de cada entrega.", "Tardamos un minuto más y expusimos cero puertas, ¿buen intercambio?"],["Una lista corta puede sostener una ruta larga, ¿verdad?", "¿Qué dato ayuda a la tarea y cuál solo calma al administrador?"])),
 N("Sela Carbón","trchar028","guardiana de rutas","Borró nombres y creó el cifrado durante una persecución pasada.","Protegió a las familias sin contarles que el patrón todavía podía reconstruirse.","Reemplazar el secreto unilateral por consentimiento renovable.","Que explicar el peligro reactive el miedo que el bosque apenas superó.","Responde con condiciones precisas y nunca con prohibiciones absolutas.",D(["Si una casa desea nombre, tendrá nombre; si desea ruta, elegirá a quién.", "Borré las placas sin asamblea porque no había tiempo. Después usé la urgencia como costumbre.", "El carbón oculta una palabra, pero el relieve conserva su forma."],["Si completan esa diagonal, cubran primero la proyección del este.", "Si Pia guarda la solución por capas, entregaré las claves a cada familia."],["Cada refugio revisará su permiso al cambiar de residente.", "Si hay emergencia, los puntos neutros se abren sin revelar hogares.", "Dejé de ser la única persona capaz de apagar el mapa."],["Si un secreto protege, también necesita fecha de revisión.", "Si nadie puede cuestionar al guardián, la ruta ya tiene otra clase de peligro."]))
 ],
 battle:{trainerName:"Geómetra de Hierro",trainerType:"SCIENTIST",sprite:"trchar246",storyToldByTeam:"Cada integrante encarna una operación visual —trazo, bloque, glifo, capa, cuadrícula y escudo— hasta separar resolver de revelar.",counterplayHint:"El equipo alterna soporte, inmunidades y potencia; Fuego, Siniestro, Tierra y ataques físicos/especiales variados resuelven sus capas.",canLose:true,bagAllowed:true,doubleBattle:false,team:[
 P("SMEARGLE",90,"trazo inicial",["SPORE","STEALTHROCK","BATONPASS","PROTECT"],"FOCUSSASH","Dibuja las pistas sin decidir qué significan."),
 P("CRUSTLE",91,"bloque de casillas",["STONEEDGE","XSCISSOR","EARTHQUAKE","SHELLSMASH"],"LIFEORB","Apila piezas que pueden formar muro o camino."),
 P("SIGILYPH",92,"glifo recuperado",["PSYCHIC","AIRSLASH","ENERGYBALL","ROOST"],"LEFTOVERS","Conserva símbolos cuyo contexto importa más que su lectura literal."),
 P("PORYGONZ",93,"capa calculada",["TRIATTACK","THUNDERBOLT","ICEBEAM","DARKPULSE"],"LIFEORB","Reconstruye datos y demuestra el riesgo de confundir cálculo con permiso."),
 P("METAGROSS",94,"cuadrícula completa",["METEORMASH","PSYCHIC","EARTHQUAKE","BULLETPUNCH"],"ASSAULTVEST","Procesa el mapa entero sin conocer la historia de cada casilla."),
 P("AEGISLASH",96,"escudo de acceso",["KINGSSHIELD","SHADOWBALL","FLASHCANNON","SACREDSWORD"],"LEFTOVERS","Cierra la ruta hasta que resolver y revelar tengan reglas distintas.") ]},
 decision:{question:"¿Qué información mostrará el mosaico restaurado?",options:["Servicios públicos sin hogares","Capas privadas con permiso"],immediateDifferences:["Pia sustituye nombres residenciales por puntos neutros de entrega.","Sela reparte claves renovables y el tablero oscurece rutas no autorizadas."],laterDifferences:["Cualquier viajero puede hallar ayuda sin localizar a sus habitantes.","Cada comunidad decide quién ve sus rutas y durante cuánto tiempo."]},
 reward:{item:"TOWNMAP",narrativeToken:"Sello de las Capas",globalEffect:"Atlas distingue datos recuperados de información autorizada para mostrarse.",futurePayoff:"El mapa final publicará servicios o solicitará claves según la elección.",whyMeaningful:"El Mapa deja de ser una vista absoluta y se convierte en acuerdo sobre lo que necesita verse."},
 steps:["Pia completa una fila y un nombre reaparece sobre una casa.","Las familias apagan luces mientras Orun detiene los suministros.","Sela confiesa que diseñó el borrado y conserva el cifrado.","El jugador elige servicios públicos o capas privadas.","Las teselas forman al Geómetra de Hierro.","La prueba ofrece contrajuego, Mochila y retirada segura.","Los tres rediseñan accesos y el mosaico entrega el sello.","Una última casilla muestra permiso solicitado en lugar de un nombre."]
}
];
function build(d){return{mapId:d.id,tier:1,title:d.title,oneSentencePromise:d.promise,biome:{identity:d.identity,visualStorytelling:d.visual,ambientChanges:d.ambient,assetManifest:[...new Map(d.npcs.map(n=>[n.sprite,{type:"character",id:n.sprite,exists:true}])).values()]},narrative:d.narrative,voiceProfile:d.voice,npcs:d.npcs,battle:d.battle,cutscene:{trigger:d.steps[0],steps:d.steps.map((action,i)=>({order:i+1,eventCommand:i===3?"Show Choices":i===5?"Trainer Battle canLose":"RMXP event command",actor:i===3?"Jugador":i===5?d.battle.trainerName:"Escena",action,stateChange:i===6?`switch${d.flag}=true`:i===7?"map_state=resolved":null})),decision:d.decision,failurePath:"La derrota devuelve al jugador al punto de curación; no altera la decisión ni bloquea la salida.",reentryPath:"La escena omite la introducción ya vista y permite repetir únicamente la prueba pendiente."},reward:d.reward,flags:{globalSwitches:[{id:d.flag,name:`POKEMOD ATLAS SEAL ${String(d.flag-707).padStart(2,"0")}`,setWhen:"Tras resolver la decisión y vencer.",readWhen:"Archivo Final y continuidad sectorial."}],variables:[{id:103,name:"POKEMOD ATLAS NARRATIVE SEALS",operation:"Incrementar una vez, protegido por self-switch A."}],selfSwitches:[{event:"Conductor de escena",letter:"A",purpose:"Bloquear recompensa repetida."},{event:d.npcs[0].name,letter:"B",purpose:"Diálogo posterior."}]},exits:[{destination:1001,condition:"always",purpose:"Retorno incondicional a Puerto Horizonte."}],qaClaims:qa};}
const out={batch:4,iteration:1,blueprints:rows.map(build)};
fs.writeFileSync(path.join(ROOT,"content","atlas_tier1_blueprints_batch04.json"),JSON.stringify(out,null,2));
console.log(`Batch 04 generado: ${out.blueprints.length} blueprints.`);
