#!/usr/bin/env node
/** Cuatro blueprints Tier 1 escritos para el segundo lote narrativo. */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
const ROOT=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"..");
const qaClaims={noBagLock:true,noImpossibleBattle:true,freeReturn:true,allAssetsExist:true,allDataIdsExist:true,notSimilarToPreviousContent:true,creepypastaIsOptInAndNonDestructive:true};
const data=[
{
 mapId:1046,title:"La Copa del Huevo Vacío",promise:"Una campeona escolar intenta renunciar a un premio vivo antes de que el torneo convierta una elección compasiva en una derrota pública.",
 biome:"Guardería convertida en patio de torneo, con gradas pequeñas y una incubadora apagada",visual:["Una copa demasiado grande tapa la puerta de la incubadora.","Los marcadores muestran aplausos, no puntos.","Seis cintas de participante cuelgan de una cuna vacía."],ambient:["El anuncio cambia de fanfarria a ruido de recreo tras la decisión.","La incubadora enciende una luz sin revelar qué nacerá."],
 narrative:{premise:"Yara ganó una copa cuyo premio es decidir el futuro de un huevo que ya eligió a otra cuidadora.",centralQuestion:"¿Renunciar a un premio puede ser la forma más honesta de ganarlo?",setup:"La escuela exige que Yara acepte el huevo frente al público.",escalation:"El marcador interpreta cada negativa como cobardía y aumenta la presión del torneo.",reversal:"El huevo responde a la voz de Pía, no a la campeona ni al director.",resolution:"El jugador ayuda a convertir la final en una evaluación de cuidado, no de propiedad.",globalConnection:"El segundo sello demuestra que Atlas confunde reconocimiento con pertenencia."},
 voice:{tone:"rápido, bromista y vulnerable",lexicon:["chispa","recreo","copa","cinta","incubadora","renuncia"],sentenceRule:"Yara acelera; Milo remata con chistes; Pía usa imágenes de crianza.",forbiddenPhrases:["Soy un entrenador","Qué gran combate","Este Pokémon es muy fuerte","Según la Pokédex","Debes derrotarme"]},
 npcs:[
  {name:"Yara Volt",sprite:"trchar008",role:"campeona escolar",reason:"Debe recibir el premio en la ceremonia.",conflict:"Quiere renunciar, pero teme que su familia interprete compasión como miedo.",want:"Que el huevo elija cuidador sin convertir la decisión en espectáculo.",fear:"Ser recordada como la campeona que huyó.",tic:"Habla cada vez más rápido cuando dice la verdad.",before:["Puedo ganar una final en cuatro turnos. Decir que no lleva toda la mañana.","La copa tiene mi nombre; el huevo ni siquiera conoce mi voz.","Si renuncio sonará a miedo. Si acepto, será miedo con aplausos."],during:["No mires el marcador. Solo sabe contar ruido.","Pía, háblale otra vez; la incubadora te está siguiendo."],after:["Renuncié al premio y no a lo que aprendí para conseguirlo.","Mi familia aplaudió tarde, pero esta vez escuché por qué.","La próxima copa tendrá una casilla para ninguna de las anteriores."],optional:["Milo ensayó tres chistes sobre huevos. Ninguno logró salir del cascarón.","La cinta pesa menos desde que no intenta decidir por mí."]},
  {name:"Milo Mic",sprite:"trchar007",role:"locutor estudiantil",reason:"Debe mantener animada una ceremonia que se está desarmando.",conflict:"Descubrió que el marcador premia volumen porque él alteró su programa.",want:"Confesar sin convertir a Yara en el centro de otro espectáculo.",fear:"Quedarse sin chistes cuando llegue el momento serio.",tic:"Hace una broma y luego corrige lo que realmente quiso decir.",before:["¡Bienvenidos a la final! La copa es enorme porque el presupuesto para sutileza era pequeño.","El marcador funciona perfecto. Perfecto para la regla equivocada, quiero decir.","Le enseñé a contar aplausos. Olvidé enseñarle cuándo callar."],during:["Eso no fue una ovación; fue una incubadora pidiendo turno.","Voy a apagar el marcador. Si me despiden, al menos será en silencio."],after:["Última hora: una campeona renuncia y el techo sigue en su sitio.","He restaurado puntos y borrado decibelios. La escuela sobrevivirá.","Mi siguiente programa reconocerá pausas. Técnicamente son difíciles de patrocinar."],optional:["La copa también sirve de paraguas para tres Pichu.","Un buen locutor sabe cuándo desaparecer de la frase."]},
  {name:"Pía Nido",sprite:"NPC 05",role:"ayudante de guardería",reason:"Lleva semanas cuidando el huevo sin figurar en el torneo.",conflict:"El huevo la eligió, pero teme que reclamarlo parezca ambición.",want:"Que la decisión se base en rutina, cuidado y consentimiento.",fear:"Que abran la incubadora para resolver una discusión de adultos.",tic:"Compara decisiones con temperatura y tiempo.",before:["Un huevo no necesita un ganador; necesita la misma voz mañana.","Cuando Yara se acerca, descansa. Cuando yo me alejo, baja la temperatura.","No quiero quedármelo por vencer a nadie. Quiero seguir llegando temprano."],during:["La luz está estable. Eso es un sí más claro que el marcador.","No abran la tapa; algunas respuestas necesitan calor, no testigos."],after:["La incubadora registró dos cuidadoras. Me gusta más que una campeona y una perdedora.","Yara vendrá los martes. Yo seguiré llegando antes del amanecer.","Cuando nazca, la primera decisión será suya: acercarse o esconderse."],optional:["Los huevos oyen discusiones como tormentas lejanas.","La paciencia también deja huellas; solo son más pequeñas."]}
 ],
 trainer:{name:"Prefecta Centella",type:"COOLTRAINER_F",sprite:"trchar008",story:"El equipo avanza desde crías presionadas a una evolución que elige su propio momento.",hint:"Los seis miembros mezclan apoyo, prioridad y cobertura; objetos, cambios y estados siguen disponibles.",team:[
  ["PICHU",88,"la promesa todavía pequeña",["THUNDERBOLT","CHARM","GRASSKNOT","PROTECT"],"FOCUSSASH"],["ELEKID",89,"la energía sin dirección",["THUNDERPUNCH","FIREPUNCH","ICEPUNCH","QUICKATTACK"],"LIFEORB"],["MAGBY",90,"la rabia ante el público",["FLAMETHROWER","PSYCHIC","FOCUSBLAST","CONFUSERAY"],"CHOICESPECS"],["RIOLU",91,"la confianza aprendida",["AURASPHERE","METEORMASH","EXTREMESPEED","SWORDSDANCE"],"FOCUSSASH"],["TOGETIC",92,"el cuidado compartido",["AIRSLASH","DAZZLINGGLEAM","ANCIENTPOWER","ROOST"],"LEFTOVERS"],["RAICHU",94,"la elección adulta",["VOLTTACKLE","IRONTAIL","BRICKBREAK","NASTYPLOT"],"LIFEORB"]]},
 cut:{trigger:"Hablar con Yara junto a la copa.",steps:["Yara rechaza la ceremonia delante del marcador.","Milo intenta bromear y el marcador convierte el ruido en puntos.","Pía acerca la incubadora sin abrirla.","El jugador decide apoyar una renuncia pública o pedir una evaluación privada.","Milo apaga su programa y confiesa la alteración.","La Prefecta propone una batalla de evaluación no eliminatoria.","La victoria activa el sello y registra a Yara y Pía como cuidadoras.","La incubadora enciende una luz y la salida queda libre."],question:"¿Cómo debe resolverse la ceremonia?",options:["Renuncia pública y clara","Evaluación privada de cuidado"],immediate:["El público aprende a escuchar un no.","La escuela suspende el premio mientras observa la rutina."],later:["Yara funda una regla de renuncia voluntaria.","Pía redacta el protocolo de elección del huevo."],failure:"La enfermería cura al equipo y la evaluación puede repetirse sin reiniciar la decisión.",reentry:"Milo omite la presentación y pregunta directamente si están listos."},
 reward:["LUCKYEGG","Sello de la Elección","La guardería reconoce cuidadores en lugar de propietarios.","El Archivo Final consulta si el jugador priorizó declaración pública o proceso privado.","El Huevo Suerte representa crecimiento elegido, no rendimiento impuesto."],flag:709
},
{
 mapId:1071,title:"El Campeón de Fecha Imposible",promise:"Un expediente anterior a la Liga obliga a decidir si una institución nació de un héroe borrado o de una falsificación creada para unir Kanto.",
 biome:"Centro Pokémon convertido en archivo provisional de una Liga que aún no debería existir",visual:["Seis retratos tienen fechas anteriores al edificio.","Una vitrina conserva una medalla sin región.","El sello oficial cambia de tinta bajo la luz del Centro."],ambient:["Las máquinas de curación marcan una fecha equivocada durante la investigación.","Tras la resolución, un reloj queda detenido en la fecha aceptada."],
 narrative:{premise:"Vera encuentra un expediente de Campeón firmado antes de la fundación de la Liga.",centralQuestion:"¿Una mentira que permitió cooperar sigue siendo fraude cuando todos conocen su origen?",setup:"El archivo describe un equipo y una final que nadie recuerda.",escalation:"La base de datos empieza a reconocer al jugador como retador de aquella temporada.",reversal:"Tomás admite que varios líderes inventaron al Campeón Cero para evitar una guerra entre gimnasios.",resolution:"El jugador conserva el expediente como mito fundador o lo reclasifica como acuerdo político.",globalConnection:"El tercer sello revela que Atlas trata las historias compartidas como infraestructura real."},
 voice:{tone:"documental, contenido y escéptico",lexicon:["expediente","folio","temporada","sello","acta","fundación"],sentenceRule:"Vera cita pruebas; Tomás responde con preguntas; K-0 habla en encabezados.",forbiddenPhrases:["Soy un entrenador","Qué gran combate","Este Pokémon es muy fuerte","Según la Pokédex","Debes derrotarme"]},
 npcs:[
  {name:"Vera Quill",sprite:"trchar028",role:"archivera de Liga",reason:"Audita documentos recuperados por Atlas.",conflict:"Su carrera depende de exponer falsificaciones, pero esta evitó violencia real.",want:"Publicar el expediente con todas sus contradicciones visibles.",fear:"Que la Liga borre el documento o lo convierta en propaganda.",tic:"Nombra folio y evidencia antes de emitir opinión.",before:["Folio uno: firma válida. Folio dos: edificio inexistente. ¿Cuál de los dos miente?","La tinta tiene cien años; la historia, según la Liga, tiene setenta.","No busco un héroe. Busco quién necesitaba que pareciera real."],during:["Ese orden de salida coincide con el acta, ¿pero quién lo recordó primero?","La base de datos acaba de añadir tu nombre sin pedirme permiso."],after:["Publicaré la falsificación junto a las vidas que protegió.","Un mito etiquetado sigue siendo evidencia; solo deja de fingir inocencia.","La Liga aceptó una nota al pie. Es una grieta pequeña y suficiente."],optional:["Los archivos no hablan. Crujen cuando alguien se sienta encima.","Una fecha imposible es una pregunta, no una orden de borrado."]},
  {name:"Tomás Rojo",sprite:"trchar069",role:"árbitro retirado",reason:"Es el último testigo del pacto entre gimnasios.",conflict:"Firmó el nombre del Campeón Cero y juró negarlo.",want:"Que el pacto sea juzgado por lo que evitó y por lo que ocultó.",fear:"Que los jóvenes repitan el engaño porque funcionó una vez.",tic:"Contesta cada afirmación con una pregunta precisa.",before:["¿Qué habrías ofrecido a ocho líderes que solo confiaban en una derrota?","¿Importa que el campeón no existiera si todos aceptaron perder contra él?","Firmé un nombre vacío. ¿Eso me vuelve árbitro o autor?"],during:["¿Reconoces al equipo porque es histórico o porque lo has visto mil veces?","Si ganas, ¿habrá existido por fin aquella final?"],after:["No necesito absolución. Necesito que nadie vuelva a llamar tradición a nuestro miedo.","El pacto evitó una guerra y fabricó décadas de silencio.","¿Puedes conservar ambas verdades sin convertir una en excusa?"],optional:["Una medalla sin región pesa como todas las demás.","Los jueces también dejan huellas en el campo." ]},
  {name:"K-0",sprite:"NPC 02",role:"auxiliar de archivo",reason:"Clasifica documentos según reglas escritas después del expediente.",conflict:"No puede archivar una temporada anterior a su propio sistema.",want:"Crear una categoría que admita origen incierto.",fear:"Que una excepción vuelva inútil todo el catálogo.",tic:"Habla mediante títulos de formulario.",before:["ESTADO: fecha válida, contexto ausente.","SOLICITUD: definir si un acuerdo puede competir en una Liga.","ERROR: el documento te reconoce como participante futuro."],during:["ACTUALIZACIÓN: el equipo histórico está respondiendo.","ADVERTENCIA: vencer no equivale a verificar."],after:["CLASIFICACIÓN NUEVA: mito fundador documentado.","NOTA: verdad política y verdad material pueden compartir carpeta.","RESPALDO: completado sin borrar la contradicción."],optional:["CAMPO VACÍO: nombre real del Campeón Cero.","SUGERENCIA: no rellenar por comodidad." ]}
 ],
 trainer:{name:"Campeón Cero",type:"COOLTRAINER_M",sprite:"trchar007",story:"Seis arquetipos de la primera Liga forman un campeón colectivo en lugar de una persona.",hint:"El equipo alterna clima, control y atacantes mixtos; no comparte una sola debilidad y recompensa leer el orden.",team:[
  ["ARCANINE",91,"valor atribuido al héroe",["FLAREBLITZ","CRUNCH","WILLOWISP","MORNINGSUN"],"LEFTOVERS"],["LAPRAS",92,"la ruta entre regiones",["SURF","ICEBEAM","SING","PERISHSONG"],"LEFTOVERS"],["EXEGGUTOR",93,"las voces de varios líderes",["PSYCHIC","GIGADRAIN","SLEEPPOWDER","LEECHSEED"],"CHOICESPECS"],["MACHAMP",94,"la fuerza pública del mito",["CLOSECOMBAT","STONEEDGE","BULLETPUNCH","KNOCKOFF"],"LIFEORB"],["ALAKAZAM",95,"el plan secreto",["PSYCHIC","SHADOWBALL","FOCUSBLAST","RECOVER"],"FOCUSSASH"],["DRAGONITE",97,"el símbolo final adoptado",["DRAGONPULSE","HURRICANE","EARTHQUAKE","DRAGONDANCE"],"LIFEORB"]]},
 cut:{trigger:"Examinar la medalla sin región.",steps:["Vera bloquea temporalmente la vitrina.","K-0 muestra la fecha imposible en las máquinas.","Tomás reconoce su firma y su juramento.","El jugador elige mito fundador o acuerdo político.","La base de datos genera al Campeón Cero.","Se libra una recreación con derrota no bloqueante.","Vera añade la clasificación elegida y activa el sello.","Los relojes vuelven a la fecha actual salvo uno."],question:"¿Cómo debe publicarse el expediente?",options:["Mito fundador documentado","Acuerdo político dramatizado"],immediate:["La medalla se exhibe con autoría colectiva.","La medalla se conserva como instrumento diplomático."],later:["Los campeones discuten quién hereda un mito.","Los líderes estudian el pacto como precedente peligroso."],failure:"K-0 restaura al equipo y conserva la elección sin validar el expediente.",reentry:"La simulación se reinicia desde la formación del equipo, no desde la confesión."},
 reward:["ABILITYPATCH","Sello del Folio Cero","Desbloquea documentos con autoría colectiva.","El Archivo Final cita el modo elegido para describir su propio origen.","El parche simboliza aceptar que una función puede cambiar sin negar su historial."],flag:710
},
{
 mapId:1096,title:"El Gremio de la Camilla Vacía",promise:"Un gremio recibe encargos firmados por exploradores desaparecidos y descubre que las misiones fueron enviadas por sus versiones futuras para impedir un rescate equivocado.",
 biome:"Centro Pokémon adaptado como gremio de expedición con tablón, camillas y mapas de túneles",visual:["Una camilla vacía tiene barro fresco bajo las ruedas.","Los encargos nuevos usan papel envejecido.","Tres mapas terminan en la misma habitación dibujada desde ángulos distintos."],ambient:["El tablón golpea la pared antes de que aparezca cada encargo.","Tras la misión, las campanillas del gremio suenan una sola vez."],
 narrative:{premise:"Bruna recibe encargos de rescate firmados por miembros que llevan semanas desaparecidos.",centralQuestion:"¿Debe un gremio obedecer una advertencia futura cuando hacerlo condena la versión presente de sus compañeros?",setup:"Cada nota evita una ruta y deja una camilla preparada.",escalation:"Tilo descubre que su propia firma aparece en el próximo encargo.",reversal:"Las notas no piden rescatar al equipo; piden impedir que el gremio abra el túnel que los atrapará.",resolution:"El jugador sella el túnel o lo convierte en ruta vigilada y enfrenta la proyección defensiva del gremio.",globalConnection:"El cuarto sello prueba que Atlas puede recibir consecuencias antes que sus causas."},
 voice:{tone:"cálido, gremial y pragmático",lexicon:["encargo","tablón","camilla","turno","ruta","regreso"],sentenceRule:"Bruna usa lenguaje laboral; Tilo exagera; Senda cuenta respiraciones.",forbiddenPhrases:["Soy un entrenador","Qué gran combate","Este Pokémon es muy fuerte","Según la Pokédex","Debes derrotarme"]},
 npcs:[
  {name:"Bruna Posta",sprite:"trchar016",role:"jefa de encargos",reason:"Mantiene operativo el gremio mientras falta el equipo principal.",conflict:"Cada misión aceptada puede producir la desaparición que intenta prevenir.",want:"Proteger a sus miembros sin convertir el miedo en una orden permanente.",fear:"Que dejar el tablón vacío sea otra forma de abandonarlos.",tic:"Asigna turnos incluso a emociones.",before:["Turno uno: leer la nota. Turno dos: no fingir que la fecha es normal.","Una camilla preparada puede ser prudencia o invitación. Aún no decido cuál.","Nadie entra al túnel solo, ni siquiera para demostrar que no tiene miedo."],during:["Tilo, tu turno es respirar; el heroísmo puede esperar en la fila.","La ruta está intentando convertirse en recuerdo antes de que la caminemos."],after:["Cerramos una entrada, no una búsqueda.","El equipo futuro dejó de escribir. Espero que eso sea una buena noticia.","Añadiré vigilancia al turno de noche y dudas al de la mañana."],optional:["Los encargos urgentes usan tinta roja. Los desesperados no usan tinta.","El gremio cobra por rutas, no por despedidas." ]},
  {name:"Tilo Brinco",sprite:"NPC 05",role:"explorador novato",reason:"Su firma aparece en una nota fechada tres semanas adelante.",conflict:"Quiere demostrar que no será la persona asustada que escribió el mensaje.",want:"Entender por qué su futuro eligió advertir en lugar de escapar.",fear:"Que obedecer la nota lo convierta exactamente en aquel futuro.",tic:"Convierte cada preocupación en una hazaña imaginaria.",before:["Mi firma futura tiene mejor letra. Eso es lo más ofensivo de todo.","Podría entrar, volver y dejarme una nota diciendo que dejé una nota.","Bruna dice que espere. Esperar también cuenta como misión si lo haces con mochila."],during:["La proyección conoce mi paso de victoria. Ni siquiera lo he estrenado.","De acuerdo, futuro yo: la advertencia fue suficientemente dramática."],after:["No entré y aun así hice algo difícil. No estaba en el folleto del gremio.","Guardaré la nota, pero practicaré una firma distinta.","La próxima hazaña será aprender cuándo una puerta merece seguir cerrada."],optional:["La camilla chirría cuando presumo. Creo que trabaja para Bruna.","Tengo una cuerda de treinta metros y cero planes sensatos." ]},
  {name:"Doctora Senda",sprite:"NPC 16",role:"médica de expedición",reason:"Preparó la camilla mencionada en las notas futuras.",conflict:"Reconoce síntomas de una expedición que aún no ocurrió.",want:"Convertir la advertencia en protocolo verificable.",fear:"Que el misterio haga olvidar necesidades médicas simples.",tic:"Cuenta pulsos antes de responder.",before:["Sesenta y dos pulsos. La nota tenía razón sobre tu ansiedad, Tilo.","El barro de la camilla contiene esporas del túnel cerrado.","No necesito creer en el futuro para tratar evidencia presente."],during:["Pulso estable. Proyección inestable. Continúen en ese orden.","La ruta reacciona al pánico; usen turnos y objetos, no prisa."],after:["Ningún herido llegó porque evitamos producirlo.","Archivaré la camilla como equipo utilizado. Prevenir también deja desgaste.","Las esporas desaparecieron cuando sellamos la causa."],optional:["Una buena misión termina con vendas sin abrir.","Los misterios también deben lavarse las manos." ]}
 ],
 trainer:{name:"Equipo Retorno",type:"POKEMONRANGER_M",sprite:"trchar009",story:"Cada miembro representa una función de expedición que intenta impedir su propio fracaso futuro.",hint:"Hay clima, hazards y soporte; eliminar al controlador de campo reduce la presión y la Mochila sigue disponible.",team:[
  ["PELIPPER",89,"mensajero meteorológico",["SURF","HURRICANE","RAINDANCE","TAILWIND"],"FOCUSSASH"],["AUDINO",90,"médica de campo",["WISH","PROTECT","HEALBELL","HYPERVOICE"],"LEFTOVERS"],["EXCADRILL",91,"excavador que debe detenerse",["EARTHQUAKE","IRONHEAD","RAPIDSPIN","STEALTHROCK"],"LIFEORB"],["CHANDELURE",92,"baliza del túnel",["SHADOWBALL","FLAMETHROWER","ENERGYBALL","TRICKROOM"],"CHOICESPECS"],["LUCARIO",93,"disciplina del gremio",["AURASPHERE","FLASHCANNON","DARKPULSE","EXTREMESPEED"],"LIFEORB"],["FLYGON",95,"guía de regreso",["EARTHQUAKE","DRAGONPULSE","ROCKSLIDE","UTURN"],"FOCUSSASH"]]},
 cut:{trigger:"Retirar del tablón la nota con la firma de Tilo.",steps:["La camilla se desplaza sola hasta el mapa del túnel.","Senda compara barro y esporas con la nota futura.","Tilo intenta aceptar el encargo sin autorización.","El jugador elige sellar el túnel o mantener una ruta vigilada.","Bruna convoca la proyección Equipo Retorno.","La batalla prueba si el gremio puede retirarse con disciplina.","La ruta elegida cambia en el tablón y se activa el sello.","Las notas futuras dejan de aparecer y la salida permanece abierta."],question:"¿Qué hacer con el túnel?",options:["Sellarlo hasta entenderlo","Mantener una ruta vigilada"],immediate:["El gremio redirige todos los encargos.","Senda establece turnos y puntos médicos."],later:["El Archivo registra una ausencia evitada.","El Archivo registra una ruta que exige responsabilidad continua."],failure:"Senda cura al equipo y la proyección vuelve al tablón sin cerrar rutas.",reentry:"Bruna conserva la decisión provisional y permite repetir solo la prueba."},
 reward:["ESCAPEROPE","Sello del Regreso","Las rutas futuras pueden reconocer retiradas como éxito.","El Archivo Final ofrece una salida adicional si el jugador valoró regresar.","La Cuerda Huida deja de simbolizar fracaso y se convierte en herramienta oficial del gremio."],flag:711
},
{
 mapId:1121,title:"Operación Rescate Demasiado Perfecto",promise:"Una patrulla que evacuó cada Pokémon de un incendio descubre que salvar individuos puede destruir un hábitat si nadie pregunta quién debe regresar.",
 biome:"Centro de coordinación Ranger rodeado por un corredor ecológico inexplicablemente vacío",visual:["Los comederos están llenos y no tienen huellas.","Las jaulas de transporte están abiertas hacia el bosque.","Un mapa de calor muestra vida alrededor de la ruta, nunca dentro."],ambient:["Los sonidos de aves desaparecen al acercarse al centro.","Tras la decisión regresan llamadas distintas según el plan de repoblación."],
 narrative:{premise:"Cora celebra un rescate sin bajas, pero la fauna se niega a regresar al corredor restaurado.",centralQuestion:"¿Cuándo termina un rescate y comienza la obligación de devolver autonomía al ecosistema?",setup:"La patrulla atribuye el vacío a trauma posterior al incendio.",escalation:"Eli descubre repelentes Ranger todavía activos bajo el suelo.",reversal:"Jo confiesa que mantuvo las balizas para proteger estadísticas perfectas, no a los Pokémon.",resolution:"El jugador retira todas las balizas o mantiene una red mínima controlada por comportamiento animal.",globalConnection:"El quinto sello enseña que Atlas puede preservar tanto una solución que impide que el mundo vuelva a vivir."},
 voice:{tone:"operativo, compasivo y autocrítico",lexicon:["pulso","corredor","baliza","reingreso","hábitat","protocolo"],sentenceRule:"Cora da órdenes cortas; Eli describe rastros; Jo habla en porcentajes hasta confesar.",forbiddenPhrases:["Soy un entrenador","Qué gran combate","Este Pokémon es muy fuerte","Según la Pokédex","Debes derrotarme"]},
 npcs:[
  {name:"Cora Pulso",sprite:"trchar016",role:"capitana Ranger",reason:"Dirigió la evacuación y debe autorizar el reingreso.",conflict:"Su operación perfecta está manteniendo vacío aquello que salvó.",want:"Corregir el protocolo sin deshonrar al equipo que arriesgó su vida.",fear:"Que admitir el error vuelva sospechoso cada rescate anterior.",tic:"Da una orden y luego pregunta a quién afecta.",before:["Patrulla, alto. ¿Alto para nosotros o para todo lo que intenta volver?","Cero bajas, cero nidos, cero huellas. Esa suma no es una victoria.","Retiraremos una baliza por vez y observaremos antes de felicitarnos."],during:["No persigan al primer Pokémon que aparezca; déjenlo elegir distancia.","La red está defendiendo el corredor de sus habitantes."],after:["Informe corregido: el rescate terminó hoy, no el día del incendio.","El equipo aceptó la enmienda. Las estadísticas tendrán que aprender humildad.","Escucha: no regresaron todos, pero regresaron por su cuenta."],optional:["Una orden corta puede tener una sombra muy larga.","El uniforme no vuelve neutral una buena intención." ]},
  {name:"Eli Rastro",sprite:"trchar009",role:"ecólogo de campo",reason:"Mide el reingreso de especies después del incendio.",conflict:"Sospechó de las balizas, pero calló para no enfrentar a la patrulla.",want:"Que la fauna marque el ritmo de recuperación.",fear:"Que su silencio sea tratado como prudencia científica.",tic:"Describe lo que falta antes de lo que ve.",before:["No hay plumas en el barro ni mordidas en la fruta. El vacío también deja muestras.","Las raíces crecieron alrededor de algo que sigue emitiendo.","Escribí 'trauma' porque era más cómodo que escribir 'nosotros'."],during:["Tropius mira el corredor y no entra. Esa es una medición, no un capricho.","Las balizas imitan depredadores sin saber cuándo detenerse."],after:["La primera huella cruzó el límite y volvió a salir. Perfecto: pudo elegir.","Publicaré mi demora junto al hallazgo.","Un hábitat sano no obedece el calendario del informe."],optional:["La ausencia tiene dirección si aprendes a mirar tallos doblados.","No todo silencio pertenece a un misterio." ]},
  {name:"Jo Cifra",sprite:"NPC 01",role:"operador de balizas",reason:"Mantuvo activa la red de seguridad después de la evacuación.",conflict:"Protegió un índice de éxito porque temía perder su puesto.",want:"Reparar el corredor sin ser reducido a un villano conveniente.",fear:"Que nadie distinga presión institucional de decisión personal.",tic:"Usa porcentajes cuando evita decir yo.",before:["La red conserva un noventa y nueve coma ocho por ciento de eficacia.","El reingreso no figuraba en mis objetivos trimestrales.","Puedo apagarla. Lo que no sé es cómo explicar por qué no lo hice ayer."],during:["La señal está subiendo; no, yo la dejé subir.","Ese Zoroark aprendió mi patrón mejor que yo."],after:["Registro personal: elegí la cifra y el corredor pagó la diferencia.","Aceptaré la sanción y también el turno de desmontaje.","El porcentaje de retorno ya no será una meta; será una observación."],optional:["Cien por ciento es una cifra sospechosa en un bosque.","Las balizas no mienten. Yo elegí qué pregunta hacerles." ]}
 ],
 trainer:{name:"Guardiana del Pulso",type:"POKEMONRANGER_F",sprite:"trchar016",story:"El equipo representa un ecosistema evacuado que prueba si el jugador sabe abrir espacio en vez de ocuparlo.",hint:"Clima, estados y prioridad castigan ataques automáticos; retirar hazards y usar curación permite recuperar el control.",team:[
  ["TROPIUS",90,"dosel que intenta regresar",["LEAFSTORM","AIRSLASH","SUNNYDAY","SYNTHESIS"],"LEFTOVERS"],["SAWSBUCK",91,"migración interrumpida",["HORNLEECH","JUMPKICK","MEGAHORN","SWORDSDANCE"],"LIFEORB"],["ARIADOS",92,"red confundida con protección",["TOXIC","MEGAHORN","SUCKERPUNCH","PROTECT"],"FOCUSSASH"],["FLOATZEL",93,"corredor fluvial",["AQUAJET","WATERFALL","ICEPUNCH","TAUNT"],"LIFEORB"],["TALONFLAME",94,"primer regreso aéreo",["BRAVEBIRD","FLAREBLITZ","ROOST","UTURN"],"FOCUSSASH"],["ZOROARK",96,"fauna que aprendió a engañar sensores",["DARKPULSE","FLAMETHROWER","FOCUSBLAST","NASTYPLOT"],"LIFEORB"]]},
 cut:{trigger:"Examinar el mapa de calor sin señales dentro del corredor.",steps:["Eli muestra la ausencia de rastros físicos.","Cora ordena detener todas las nuevas capturas.","Jo revela que las balizas siguen activas.","El jugador elige apagado total o red mínima supervisada.","La red materializa a la Guardiana del Pulso.","La batalla permite objetos y retirada médica.","Jo ejecuta el protocolo elegido y activa el sello.","Un Pokémon cruza el corredor por voluntad propia."],question:"¿Cómo retirar la red?",options:["Apagado total inmediato","Red mínima y observación"],immediate:["El corredor queda libre y la patrulla retrocede.","Solo quedan sensores pasivos lejos de los nidos."],later:["La fauna vuelve en oleadas impredecibles.","El reingreso es más lento pero produce datos para otros rescates."],failure:"Cora ordena retirada médica y ninguna baliza cambia hasta vencer.",reentry:"Eli resume las señales actuales sin repetir la discusión completa."},
 reward:["ABILITYCAPSULE","Sello del Reingreso","Los Rangers añaden autonomía al protocolo de rescate.","Misiones futuras cambian diálogo según apagado inmediato o supervisión.","La Cápsula Habilidad simboliza adaptar una herramienta sin definir para siempre a quien la usa."],flag:712
}
];
function build(d){const npcs=d.npcs.map(n=>({name:n.name,sprite:n.sprite,role:n.role,reasonForBeingHere:n.reason,personalConflict:n.conflict,want:n.want,fear:n.fear,verbalTic:n.tic,dialogue:{before:n.before,during:n.during,after:n.after,optional:n.optional}}));return{
 mapId:d.mapId,tier:1,title:d.title,oneSentencePromise:d.promise,
 biome:{identity:d.biome,visualStorytelling:d.visual,ambientChanges:d.ambient,assetManifest:[...new Map(npcs.map(n=>[n.sprite,{type:"character",id:n.sprite,exists:true}])).values()]},
 narrative:d.narrative,voiceProfile:d.voice,npcs,
 battle:{trainerName:d.trainer.name,trainerType:d.trainer.type,sprite:d.trainer.sprite,storyToldByTeam:d.trainer.story,counterplayHint:d.trainer.hint,canLose:true,bagAllowed:true,doubleBattle:false,team:d.trainer.team.map(([species,level,narrativeRole,moves,item])=>({species,level,narrativeRole,moves,item,whyItBelongs:narrativeRole}))},
 cutscene:{trigger:d.cut.trigger,steps:d.cut.steps.map((action,i)=>({order:i+1,eventCommand:i===3?"Show Choices":i===5?"Trainer Battle canLose":"RMXP event command",actor:i===3?"Jugador":i===5?d.trainer.name:"Escena",action,stateChange:i===6?`switch${d.flag}=true`:i===7?"map_state=resolved":null})),decision:{question:d.cut.question,options:d.cut.options,immediateDifferences:d.cut.immediate,laterDifferences:d.cut.later},failurePath:d.cut.failure,reentryPath:d.cut.reentry},
 reward:{item:d.reward[0],narrativeToken:d.reward[1],globalEffect:d.reward[2],futurePayoff:d.reward[3],whyMeaningful:d.reward[4]},
 flags:{globalSwitches:[{id:d.flag,name:`POKEMOD ATLAS SEAL ${String(d.flag-707).padStart(2,"0")}`,setWhen:"Tras la resolución y victoria.",readWhen:"Archivo Final y NPCs de continuidad."}],variables:[{id:103,name:"POKEMOD ATLAS NARRATIVE SEALS",operation:"Incrementar una vez protegido por self-switch A."}],selfSwitches:[{event:"Conductor de escena",letter:"A",purpose:"Bloquear recompensa repetida."},{event:npcs[0].name,letter:"B",purpose:"Diálogo posterior."}]},
 exits:[{destination:1001,condition:"always",purpose:"Retorno incondicional a Puerto Horizonte."}],qaClaims
};}
const out={batch:2,iteration:1,blueprints:data.map(build)};
fs.writeFileSync(path.join(ROOT,"content","atlas_tier1_blueprints_batch02.json"),JSON.stringify(out,null,2));
console.log(`Batch 02 generado: ${out.blueprints.length} blueprints artesanales.`);
